/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountResponseDto
 */
export interface AccountResponseDto {
    /**
     * Entity unique identifier
     * @type {string}
     * @memberof AccountResponseDto
     */
    id: string;
    /**
     * Account display name
     * @type {string}
     * @memberof AccountResponseDto
     */
    name: string;
    /**
     * Multisig contract address
     * @type {string}
     * @memberof AccountResponseDto
     */
    contract: string;
    /**
     * All account members aggregated from all networks (read access)
     * @type {Array<string>}
     * @memberof AccountResponseDto
     */
    members: Array<string>;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof AccountResponseDto
     */
    createdAt: string;
    /**
     * Initial account configuration for all deployments
     * @type {{ [key: string]: any; }}
     * @memberof AccountResponseDto
     */
    initialConfig: { [key: string]: any; };
    /**
     * Whether the entity relates to Tron (TVM)
     * @type {boolean}
     * @memberof AccountResponseDto
     */
    isTron: boolean;
    /**
     * Composite identifier {version}-{network_type}
     * @type {string}
     * @memberof AccountResponseDto
     */
    smartContractVersionId: string;
    /**
     * TRON network chainId for TRON accounts (derived from smartContractVersionId). Null for EVM accounts.
     * @type {string}
     * @memberof AccountResponseDto
     */
    networkId?: string | null;
    /**
     * true if the account is hidden for the current user; otherwise false
     * @type {boolean}
     * @memberof AccountResponseDto
     */
    isHidden?: boolean;
}

/**
 * Check if a given object implements the AccountResponseDto interface.
 */
export function instanceOfAccountResponseDto(value: object): value is AccountResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('contract' in value) || value['contract'] === undefined) return false;
    if (!('members' in value) || value['members'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('initialConfig' in value) || value['initialConfig'] === undefined) return false;
    if (!('isTron' in value) || value['isTron'] === undefined) return false;
    if (!('smartContractVersionId' in value) || value['smartContractVersionId'] === undefined) return false;
    return true;
}

export function AccountResponseDtoFromJSON(json: any): AccountResponseDto {
    return AccountResponseDtoFromJSONTyped(json, false);
}

export function AccountResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'contract': json['contract'],
        'members': json['members'],
        'createdAt': json['createdAt'],
        'initialConfig': json['initialConfig'],
        'isTron': json['isTron'],
        'smartContractVersionId': json['smartContractVersionId'],
        'networkId': json['networkId'] == null ? undefined : json['networkId'],
        'isHidden': json['isHidden'] == null ? undefined : json['isHidden'],
    };
}

export function AccountResponseDtoToJSON(json: any): AccountResponseDto {
    return AccountResponseDtoToJSONTyped(json, false);
}

export function AccountResponseDtoToJSONTyped(value?: AccountResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'contract': value['contract'],
        'members': value['members'],
        'createdAt': value['createdAt'],
        'initialConfig': value['initialConfig'],
        'isTron': value['isTron'],
        'smartContractVersionId': value['smartContractVersionId'],
        'networkId': value['networkId'],
        'isHidden': value['isHidden'],
    };
}

