/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UniversalAddress } from './universal-address';
import {
    UniversalAddressFromJSON,
    UniversalAddressFromJSONTyped,
    UniversalAddressToJSON,
    UniversalAddressToJSONTyped,
} from './universal-address';

/**
 * 
 * @export
 * @interface AddressBookListResponseDtoItemsInner
 */
export interface AddressBookListResponseDtoItemsInner {
    /**
     * 
     * @type {string}
     * @memberof AddressBookListResponseDtoItemsInner
     */
    label: string;
    /**
     * 
     * @type {UniversalAddress}
     * @memberof AddressBookListResponseDtoItemsInner
     */
    address: UniversalAddress;
    /**
     * 
     * @type {boolean}
     * @memberof AddressBookListResponseDtoItemsInner
     */
    isTron?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AddressBookListResponseDtoItemsInner
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AddressBookListResponseDtoItemsInner
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the AddressBookListResponseDtoItemsInner interface.
 */
export function instanceOfAddressBookListResponseDtoItemsInner(value: object): value is AddressBookListResponseDtoItemsInner {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function AddressBookListResponseDtoItemsInnerFromJSON(json: any): AddressBookListResponseDtoItemsInner {
    return AddressBookListResponseDtoItemsInnerFromJSONTyped(json, false);
}

export function AddressBookListResponseDtoItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressBookListResponseDtoItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
        'address': UniversalAddressFromJSON(json['address']),
        'isTron': json['isTron'] == null ? undefined : json['isTron'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function AddressBookListResponseDtoItemsInnerToJSON(json: any): AddressBookListResponseDtoItemsInner {
    return AddressBookListResponseDtoItemsInnerToJSONTyped(json, false);
}

export function AddressBookListResponseDtoItemsInnerToJSONTyped(value?: AddressBookListResponseDtoItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'address': UniversalAddressToJSON(value['address']),
        'isTron': value['isTron'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

