/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressBookListResponseDtoItemsInner } from './address-book-list-response-dto-items-inner';
import {
    AddressBookListResponseDtoItemsInnerFromJSON,
    AddressBookListResponseDtoItemsInnerFromJSONTyped,
    AddressBookListResponseDtoItemsInnerToJSON,
    AddressBookListResponseDtoItemsInnerToJSONTyped,
} from './address-book-list-response-dto-items-inner';

/**
 * 
 * @export
 * @interface AddressBookListResponseDto
 */
export interface AddressBookListResponseDto {
    /**
     * 
     * @type {number}
     * @memberof AddressBookListResponseDto
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof AddressBookListResponseDto
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof AddressBookListResponseDto
     */
    pageSize: number;
    /**
     * 
     * @type {Array<AddressBookListResponseDtoItemsInner>}
     * @memberof AddressBookListResponseDto
     */
    items: Array<AddressBookListResponseDtoItemsInner>;
}

/**
 * Check if a given object implements the AddressBookListResponseDto interface.
 */
export function instanceOfAddressBookListResponseDto(value: object): value is AddressBookListResponseDto {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function AddressBookListResponseDtoFromJSON(json: any): AddressBookListResponseDto {
    return AddressBookListResponseDtoFromJSONTyped(json, false);
}

export function AddressBookListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressBookListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'items': ((json['items'] as Array<any>).map(AddressBookListResponseDtoItemsInnerFromJSON)),
    };
}

export function AddressBookListResponseDtoToJSON(json: any): AddressBookListResponseDto {
    return AddressBookListResponseDtoToJSONTyped(json, false);
}

export function AddressBookListResponseDtoToJSONTyped(value?: AddressBookListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'items': ((value['items'] as Array<any>).map(AddressBookListResponseDtoItemsInnerToJSON)),
    };
}

