/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiKeyListResponseDtoItemsInner
 */
export interface ApiKeyListResponseDtoItemsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiKeyListResponseDtoItemsInner
     */
    id: string;
    /**
     * Deprecated: use accountId instead
     * @type {string}
     * @memberof ApiKeyListResponseDtoItemsInner
     */
    teamId: string;
    /**
     * Account ID (alias of teamId)
     * @type {string}
     * @memberof ApiKeyListResponseDtoItemsInner
     */
    accountId: string;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyListResponseDtoItemsInner
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyListResponseDtoItemsInner
     */
    apiKeyMask: string;
    /**
     * 
     * @type {Date}
     * @memberof ApiKeyListResponseDtoItemsInner
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ApiKeyListResponseDtoItemsInner
     */
    revokedAt: Date | null;
}

/**
 * Check if a given object implements the ApiKeyListResponseDtoItemsInner interface.
 */
export function instanceOfApiKeyListResponseDtoItemsInner(value: object): value is ApiKeyListResponseDtoItemsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('teamId' in value) || value['teamId'] === undefined) return false;
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('apiKeyMask' in value) || value['apiKeyMask'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('revokedAt' in value) || value['revokedAt'] === undefined) return false;
    return true;
}

export function ApiKeyListResponseDtoItemsInnerFromJSON(json: any): ApiKeyListResponseDtoItemsInner {
    return ApiKeyListResponseDtoItemsInnerFromJSONTyped(json, false);
}

export function ApiKeyListResponseDtoItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyListResponseDtoItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'teamId': json['teamId'],
        'accountId': json['accountId'],
        'name': json['name'] == null ? undefined : json['name'],
        'apiKeyMask': json['apiKeyMask'],
        'createdAt': (new Date(json['createdAt'])),
        'revokedAt': (json['revokedAt'] == null ? null : new Date(json['revokedAt'])),
    };
}

export function ApiKeyListResponseDtoItemsInnerToJSON(json: any): ApiKeyListResponseDtoItemsInner {
    return ApiKeyListResponseDtoItemsInnerToJSONTyped(json, false);
}

export function ApiKeyListResponseDtoItemsInnerToJSONTyped(value?: ApiKeyListResponseDtoItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'teamId': value['teamId'],
        'accountId': value['accountId'],
        'name': value['name'],
        'apiKeyMask': value['apiKeyMask'],
        'createdAt': value['createdAt'].toISOString(),
        'revokedAt': value['revokedAt'] == null ? value['revokedAt'] : value['revokedAt'].toISOString(),
    };
}

