/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssetBalanceDto } from './asset-balance-dto';
import {
    AssetBalanceDtoFromJSON,
    AssetBalanceDtoFromJSONTyped,
    AssetBalanceDtoToJSON,
    AssetBalanceDtoToJSONTyped,
} from './asset-balance-dto';

/**
 * 
 * @export
 * @interface AssetBalancesResponseDto
 */
export interface AssetBalancesResponseDto {
    /**
     * Total number of items across all pages
     * @type {number}
     * @memberof AssetBalancesResponseDto
     */
    total: number;
    /**
     * Current page number (starts from 1)
     * @type {number}
     * @memberof AssetBalancesResponseDto
     */
    page: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof AssetBalancesResponseDto
     */
    pageSize: number;
    /**
     * List of asset balances
     * @type {Array<AssetBalanceDto>}
     * @memberof AssetBalancesResponseDto
     */
    items: Array<AssetBalanceDto>;
}

/**
 * Check if a given object implements the AssetBalancesResponseDto interface.
 */
export function instanceOfAssetBalancesResponseDto(value: object): value is AssetBalancesResponseDto {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function AssetBalancesResponseDtoFromJSON(json: any): AssetBalancesResponseDto {
    return AssetBalancesResponseDtoFromJSONTyped(json, false);
}

export function AssetBalancesResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetBalancesResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'items': ((json['items'] as Array<any>).map(AssetBalanceDtoFromJSON)),
    };
}

export function AssetBalancesResponseDtoToJSON(json: any): AssetBalancesResponseDto {
    return AssetBalancesResponseDtoToJSONTyped(json, false);
}

export function AssetBalancesResponseDtoToJSONTyped(value?: AssetBalancesResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'items': ((value['items'] as Array<any>).map(AssetBalanceDtoToJSON)),
    };
}

