/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssetChainBalanceDto } from './asset-chain-balance-dto';
import {
    AssetChainBalanceDtoFromJSON,
    AssetChainBalanceDtoFromJSONTyped,
    AssetChainBalanceDtoToJSON,
    AssetChainBalanceDtoToJSONTyped,
} from './asset-chain-balance-dto';
import type { AssetAggregatedBalanceResponseDtoCurrency } from './asset-aggregated-balance-response-dto-currency';
import {
    AssetAggregatedBalanceResponseDtoCurrencyFromJSON,
    AssetAggregatedBalanceResponseDtoCurrencyFromJSONTyped,
    AssetAggregatedBalanceResponseDtoCurrencyToJSON,
    AssetAggregatedBalanceResponseDtoCurrencyToJSONTyped,
} from './asset-aggregated-balance-response-dto-currency';

/**
 * 
 * @export
 * @interface AssetAggregatedBalanceResponseDto
 */
export interface AssetAggregatedBalanceResponseDto {
    /**
     * 
     * @type {AssetAggregatedBalanceResponseDtoCurrency}
     * @memberof AssetAggregatedBalanceResponseDto
     */
    currency: AssetAggregatedBalanceResponseDtoCurrency;
    /**
     * Total asset balance summed across all chains
     * @type {string}
     * @memberof AssetAggregatedBalanceResponseDto
     */
    balance: string;
    /**
     * Balance converted to base currency (null if rate unavailable)
     * @type {string}
     * @memberof AssetAggregatedBalanceResponseDto
     */
    convertedBalance: string | null;
    /**
     * Only for JWT users; ignored for API keys
     * @type {boolean}
     * @memberof AssetAggregatedBalanceResponseDto
     */
    isHidden?: boolean;
    /**
     * Per-chain breakdown of this asset
     * @type {Array<AssetChainBalanceDto>}
     * @memberof AssetAggregatedBalanceResponseDto
     */
    chains: Array<AssetChainBalanceDto>;
}

/**
 * Check if a given object implements the AssetAggregatedBalanceResponseDto interface.
 */
export function instanceOfAssetAggregatedBalanceResponseDto(value: object): value is AssetAggregatedBalanceResponseDto {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    if (!('convertedBalance' in value) || value['convertedBalance'] === undefined) return false;
    if (!('chains' in value) || value['chains'] === undefined) return false;
    return true;
}

export function AssetAggregatedBalanceResponseDtoFromJSON(json: any): AssetAggregatedBalanceResponseDto {
    return AssetAggregatedBalanceResponseDtoFromJSONTyped(json, false);
}

export function AssetAggregatedBalanceResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetAggregatedBalanceResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': AssetAggregatedBalanceResponseDtoCurrencyFromJSON(json['currency']),
        'balance': json['balance'],
        'convertedBalance': json['convertedBalance'],
        'isHidden': json['isHidden'] == null ? undefined : json['isHidden'],
        'chains': ((json['chains'] as Array<any>).map(AssetChainBalanceDtoFromJSON)),
    };
}

export function AssetAggregatedBalanceResponseDtoToJSON(json: any): AssetAggregatedBalanceResponseDto {
    return AssetAggregatedBalanceResponseDtoToJSONTyped(json, false);
}

export function AssetAggregatedBalanceResponseDtoToJSONTyped(value?: AssetAggregatedBalanceResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': AssetAggregatedBalanceResponseDtoCurrencyToJSON(value['currency']),
        'balance': value['balance'],
        'convertedBalance': value['convertedBalance'],
        'isHidden': value['isHidden'],
        'chains': ((value['chains'] as Array<any>).map(AssetChainBalanceDtoToJSON)),
    };
}

