/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BalanceHistoryResponseDtoItemsInner } from './balance-history-response-dto-items-inner';
import {
    BalanceHistoryResponseDtoItemsInnerFromJSON,
    BalanceHistoryResponseDtoItemsInnerFromJSONTyped,
    BalanceHistoryResponseDtoItemsInnerToJSON,
    BalanceHistoryResponseDtoItemsInnerToJSONTyped,
} from './balance-history-response-dto-items-inner';

/**
 * 
 * @export
 * @interface BalanceHistoryResponseDto
 */
export interface BalanceHistoryResponseDto {
    /**
     * 
     * @type {Array<BalanceHistoryResponseDtoItemsInner>}
     * @memberof BalanceHistoryResponseDto
     */
    items: Array<BalanceHistoryResponseDtoItemsInner>;
}

/**
 * Check if a given object implements the BalanceHistoryResponseDto interface.
 */
export function instanceOfBalanceHistoryResponseDto(value: object): value is BalanceHistoryResponseDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function BalanceHistoryResponseDtoFromJSON(json: any): BalanceHistoryResponseDto {
    return BalanceHistoryResponseDtoFromJSONTyped(json, false);
}

export function BalanceHistoryResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BalanceHistoryResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(BalanceHistoryResponseDtoItemsInnerFromJSON)),
    };
}

export function BalanceHistoryResponseDtoToJSON(json: any): BalanceHistoryResponseDto {
    return BalanceHistoryResponseDtoToJSONTyped(json, false);
}

export function BalanceHistoryResponseDtoToJSONTyped(value?: BalanceHistoryResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(BalanceHistoryResponseDtoItemsInnerToJSON)),
    };
}

