/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BalanceSummaryResponseDto
 */
export interface BalanceSummaryResponseDto {
    /**
     * Total balance in base currency
     * @type {number}
     * @memberof BalanceSummaryResponseDto
     */
    totalBalance: number;
    /**
     * Uncollected balance in base currency
     * @type {number}
     * @memberof BalanceSummaryResponseDto
     */
    uncollectedBalance: number;
    /**
     * Count of uncollected invoices
     * @type {number}
     * @memberof BalanceSummaryResponseDto
     */
    uncollectedInvoices: number;
    /**
     * Whether all currency rates were available
     * @type {boolean}
     * @memberof BalanceSummaryResponseDto
     */
    allRatesReceived: boolean;
}

/**
 * Check if a given object implements the BalanceSummaryResponseDto interface.
 */
export function instanceOfBalanceSummaryResponseDto(value: object): value is BalanceSummaryResponseDto {
    if (!('totalBalance' in value) || value['totalBalance'] === undefined) return false;
    if (!('uncollectedBalance' in value) || value['uncollectedBalance'] === undefined) return false;
    if (!('uncollectedInvoices' in value) || value['uncollectedInvoices'] === undefined) return false;
    if (!('allRatesReceived' in value) || value['allRatesReceived'] === undefined) return false;
    return true;
}

export function BalanceSummaryResponseDtoFromJSON(json: any): BalanceSummaryResponseDto {
    return BalanceSummaryResponseDtoFromJSONTyped(json, false);
}

export function BalanceSummaryResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BalanceSummaryResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalBalance': json['totalBalance'],
        'uncollectedBalance': json['uncollectedBalance'],
        'uncollectedInvoices': json['uncollectedInvoices'],
        'allRatesReceived': json['allRatesReceived'],
    };
}

export function BalanceSummaryResponseDtoToJSON(json: any): BalanceSummaryResponseDto {
    return BalanceSummaryResponseDtoToJSONTyped(json, false);
}

export function BalanceSummaryResponseDtoToJSONTyped(value?: BalanceSummaryResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalBalance': value['totalBalance'],
        'uncollectedBalance': value['uncollectedBalance'],
        'uncollectedInvoices': value['uncollectedInvoices'],
        'allRatesReceived': value['allRatesReceived'],
    };
}

