/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ClaimToRefundPayload } from './claim-to-refund-payload';
import {
    instanceOfClaimToRefundPayload,
    ClaimToRefundPayloadFromJSON,
    ClaimToRefundPayloadFromJSONTyped,
    ClaimToRefundPayloadToJSON,
} from './claim-to-refund-payload';
import type { CrossChainTransferPayload } from './cross-chain-transfer-payload';
import {
    instanceOfCrossChainTransferPayload,
    CrossChainTransferPayloadFromJSON,
    CrossChainTransferPayloadFromJSONTyped,
    CrossChainTransferPayloadToJSON,
} from './cross-chain-transfer-payload';
import type { DappTransactionPayload } from './dapp-transaction-payload';
import {
    instanceOfDappTransactionPayload,
    DappTransactionPayloadFromJSON,
    DappTransactionPayloadFromJSONTyped,
    DappTransactionPayloadToJSON,
} from './dapp-transaction-payload';
import type { DelegatePayload } from './delegate-payload';
import {
    instanceOfDelegatePayload,
    DelegatePayloadFromJSON,
    DelegatePayloadFromJSONTyped,
    DelegatePayloadToJSON,
} from './delegate-payload';
import type { MultisigConfigChangePayload } from './multisig-config-change-payload';
import {
    instanceOfMultisigConfigChangePayload,
    MultisigConfigChangePayloadFromJSON,
    MultisigConfigChangePayloadFromJSONTyped,
    MultisigConfigChangePayloadToJSON,
} from './multisig-config-change-payload';
import type { PayoutPayload } from './payout-payload';
import {
    instanceOfPayoutPayload,
    PayoutPayloadFromJSON,
    PayoutPayloadFromJSONTyped,
    PayoutPayloadToJSON,
} from './payout-payload';
import type { ReclaimPayload } from './reclaim-payload';
import {
    instanceOfReclaimPayload,
    ReclaimPayloadFromJSON,
    ReclaimPayloadFromJSONTyped,
    ReclaimPayloadToJSON,
} from './reclaim-payload';
import type { StakeResourcePayload } from './stake-resource-payload';
import {
    instanceOfStakeResourcePayload,
    StakeResourcePayloadFromJSON,
    StakeResourcePayloadFromJSONTyped,
    StakeResourcePayloadToJSON,
} from './stake-resource-payload';
import type { VotePayload } from './vote-payload';
import {
    instanceOfVotePayload,
    VotePayloadFromJSON,
    VotePayloadFromJSONTyped,
    VotePayloadToJSON,
} from './vote-payload';

/**
 * @type BatchCandidatesResponseDtoCandidatesInnerOperationsInnerPayload
 * Operation-specific data (team config changes, reject details, etc.)
 * @export
 */
export type BatchCandidatesResponseDtoCandidatesInnerOperationsInnerPayload = ClaimToRefundPayload | CrossChainTransferPayload | DappTransactionPayload | DelegatePayload | MultisigConfigChangePayload | PayoutPayload | ReclaimPayload | StakeResourcePayload | VotePayload | object;

export function BatchCandidatesResponseDtoCandidatesInnerOperationsInnerPayloadFromJSON(json: any): BatchCandidatesResponseDtoCandidatesInnerOperationsInnerPayload {
    return BatchCandidatesResponseDtoCandidatesInnerOperationsInnerPayloadFromJSONTyped(json, false);
}

export function BatchCandidatesResponseDtoCandidatesInnerOperationsInnerPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchCandidatesResponseDtoCandidatesInnerOperationsInnerPayload {
    if (json == null) {
        return json;
    }
    return json;
}

export function BatchCandidatesResponseDtoCandidatesInnerOperationsInnerPayloadToJSON(json: any): any {
    return BatchCandidatesResponseDtoCandidatesInnerOperationsInnerPayloadToJSONTyped(json, false);
}

export function BatchCandidatesResponseDtoCandidatesInnerOperationsInnerPayloadToJSONTyped(value?: BatchCandidatesResponseDtoCandidatesInnerOperationsInnerPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    return value;
}

