/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BatchCandidatesResponseDtoCandidatesInnerOperationsInner } from './batch-candidates-response-dto-candidates-inner-operations-inner';
import {
    BatchCandidatesResponseDtoCandidatesInnerOperationsInnerFromJSON,
    BatchCandidatesResponseDtoCandidatesInnerOperationsInnerFromJSONTyped,
    BatchCandidatesResponseDtoCandidatesInnerOperationsInnerToJSON,
    BatchCandidatesResponseDtoCandidatesInnerOperationsInnerToJSONTyped,
} from './batch-candidates-response-dto-candidates-inner-operations-inner';

/**
 * 
 * @export
 * @interface BatchCandidatesResponseDtoCandidatesInner
 */
export interface BatchCandidatesResponseDtoCandidatesInner {
    /**
     * Network-specific transaction nonce
     * @type {string}
     * @memberof BatchCandidatesResponseDtoCandidatesInner
     */
    nonce: string;
    /**
     * True when more than one operation competes for this nonce (including a REJECT). Only one can execute.
     * @type {boolean}
     * @memberof BatchCandidatesResponseDtoCandidatesInner
     */
    conflict: boolean;
    /**
     * Live candidates for this nonce. At least one is `batchEligible`; competitors may still be collecting signatures.
     * @type {Array<BatchCandidatesResponseDtoCandidatesInnerOperationsInner>}
     * @memberof BatchCandidatesResponseDtoCandidatesInner
     */
    operations: Array<BatchCandidatesResponseDtoCandidatesInnerOperationsInner>;
}

/**
 * Check if a given object implements the BatchCandidatesResponseDtoCandidatesInner interface.
 */
export function instanceOfBatchCandidatesResponseDtoCandidatesInner(value: object): value is BatchCandidatesResponseDtoCandidatesInner {
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    if (!('conflict' in value) || value['conflict'] === undefined) return false;
    if (!('operations' in value) || value['operations'] === undefined) return false;
    return true;
}

export function BatchCandidatesResponseDtoCandidatesInnerFromJSON(json: any): BatchCandidatesResponseDtoCandidatesInner {
    return BatchCandidatesResponseDtoCandidatesInnerFromJSONTyped(json, false);
}

export function BatchCandidatesResponseDtoCandidatesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchCandidatesResponseDtoCandidatesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'nonce': json['nonce'],
        'conflict': json['conflict'],
        'operations': ((json['operations'] as Array<any>).map(BatchCandidatesResponseDtoCandidatesInnerOperationsInnerFromJSON)),
    };
}

export function BatchCandidatesResponseDtoCandidatesInnerToJSON(json: any): BatchCandidatesResponseDtoCandidatesInner {
    return BatchCandidatesResponseDtoCandidatesInnerToJSONTyped(json, false);
}

export function BatchCandidatesResponseDtoCandidatesInnerToJSONTyped(value?: BatchCandidatesResponseDtoCandidatesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nonce': value['nonce'],
        'conflict': value['conflict'],
        'operations': ((value['operations'] as Array<any>).map(BatchCandidatesResponseDtoCandidatesInnerOperationsInnerToJSON)),
    };
}

