/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UniversalAddress } from './universal-address';
import {
    UniversalAddressFromJSON,
    UniversalAddressFromJSONTyped,
    UniversalAddressToJSON,
    UniversalAddressToJSONTyped,
} from './universal-address';
import type { CurrencyResponseDto } from './currency-response-dto';
import {
    CurrencyResponseDtoFromJSON,
    CurrencyResponseDtoFromJSONTyped,
    CurrencyResponseDtoToJSON,
    CurrencyResponseDtoToJSONTyped,
} from './currency-response-dto';

/**
 * 
 * @export
 * @interface BlockchainDelegateOperationResponseDto
 */
export interface BlockchainDelegateOperationResponseDto {
    /**
     * Entity unique identifier
     * @type {string}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    id: string;
    /**
     * Chain ID
     * @type {string}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    chainId: string;
    /**
     * Deployment that owns the operation (null for legacy rows without deployment_id)
     * @type {string}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    deploymentId: string | null;
    /**
     * V2 operation type
     * @type {BlockchainDelegateOperationResponseDtoOperationTypeEnum}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    operationType: BlockchainDelegateOperationResponseDtoOperationTypeEnum;
    /**
     * V2 operation status
     * @type {BlockchainDelegateOperationResponseDtoStatusEnum}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    status: BlockchainDelegateOperationResponseDtoStatusEnum;
    /**
     * 
     * @type {UniversalAddress}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    fromAddress: UniversalAddress | null;
    /**
     * 
     * @type {UniversalAddress}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    toAddress: UniversalAddress | null;
    /**
     * Entity unique identifier
     * @type {string}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    txId: string | null;
    /**
     * Blockchain transaction hash (EVM 0x + 64 hex; TVM 64 hex)
     * @type {string}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    txHash: string | null;
    /**
     * Block number of the transaction
     * @type {string}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    blockNumber: string | null;
    /**
     * Blockchain transaction fee
     * @type {string}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    blockchainFee: string;
    /**
     * Number of blockchain confirmations
     * @type {number}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    confirmations: number;
    /**
     * Confirmation timestamp (null if not confirmed yet)
     * @type {string}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    confirmedAt: string | null;
    /**
     * The unique ID of the currency, ("{chainId}" or "{chainId}-{contractAddress}")
     * @type {string}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    currencyId: string | null;
    /**
     * Delegated TRX amount
     * @type {string}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    amount: string;
    /**
     * 
     * @type {CurrencyResponseDto}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    currency: CurrencyResponseDto | null;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    createdAt: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    updatedAt: string;
    /**
     * Resource type
     * @type {BlockchainDelegateOperationResponseDtoResourceTypeEnum}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    resourceType: BlockchainDelegateOperationResponseDtoResourceTypeEnum;
    /**
     * TRON base58 address the resource is delegated to
     * @type {string}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    recipient: string;
    /**
     * Whether the delegation used the lock period
     * @type {boolean}
     * @memberof BlockchainDelegateOperationResponseDto
     */
    isLocked: boolean;
}


/**
 * @export
 */
export const BlockchainDelegateOperationResponseDtoOperationTypeEnum = {
    Payout: 'PAYOUT',
    InvoiceDeposit: 'INVOICE_DEPOSIT',
    Claim: 'CLAIM',
    Deploy: 'DEPLOY',
    DirectDeposit: 'DIRECT_DEPOSIT',
    Reject: 'REJECT',
    SetConfig: 'SET_CONFIG',
    DappTransaction: 'DAPP_TRANSACTION',
    CrossChainTransfer: 'CROSS_CHAIN_TRANSFER',
    Stake: 'STAKE',
    Unstake: 'UNSTAKE',
    CancelUnstaking: 'CANCEL_UNSTAKING',
    StakingWithdraw: 'STAKING_WITHDRAW',
    Vote: 'VOTE',
    ClaimRewards: 'CLAIM_REWARDS',
    Delegate: 'DELEGATE',
    Reclaim: 'RECLAIM'
} as const;
export type BlockchainDelegateOperationResponseDtoOperationTypeEnum = typeof BlockchainDelegateOperationResponseDtoOperationTypeEnum[keyof typeof BlockchainDelegateOperationResponseDtoOperationTypeEnum];

/**
 * @export
 */
export const BlockchainDelegateOperationResponseDtoStatusEnum = {
    Created: 'CREATED',
    Pending: 'PENDING',
    Confirmed: 'CONFIRMED',
    Failed: 'FAILED',
    Cancelled: 'CANCELLED'
} as const;
export type BlockchainDelegateOperationResponseDtoStatusEnum = typeof BlockchainDelegateOperationResponseDtoStatusEnum[keyof typeof BlockchainDelegateOperationResponseDtoStatusEnum];

/**
 * @export
 */
export const BlockchainDelegateOperationResponseDtoResourceTypeEnum = {
    Bandwidth: 'BANDWIDTH',
    Energy: 'ENERGY'
} as const;
export type BlockchainDelegateOperationResponseDtoResourceTypeEnum = typeof BlockchainDelegateOperationResponseDtoResourceTypeEnum[keyof typeof BlockchainDelegateOperationResponseDtoResourceTypeEnum];


/**
 * Check if a given object implements the BlockchainDelegateOperationResponseDto interface.
 */
export function instanceOfBlockchainDelegateOperationResponseDto(value: object): value is BlockchainDelegateOperationResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    if (!('deploymentId' in value) || value['deploymentId'] === undefined) return false;
    if (!('operationType' in value) || value['operationType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('fromAddress' in value) || value['fromAddress'] === undefined) return false;
    if (!('toAddress' in value) || value['toAddress'] === undefined) return false;
    if (!('txId' in value) || value['txId'] === undefined) return false;
    if (!('txHash' in value) || value['txHash'] === undefined) return false;
    if (!('blockNumber' in value) || value['blockNumber'] === undefined) return false;
    if (!('blockchainFee' in value) || value['blockchainFee'] === undefined) return false;
    if (!('confirmations' in value) || value['confirmations'] === undefined) return false;
    if (!('confirmedAt' in value) || value['confirmedAt'] === undefined) return false;
    if (!('currencyId' in value) || value['currencyId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('resourceType' in value) || value['resourceType'] === undefined) return false;
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    if (!('isLocked' in value) || value['isLocked'] === undefined) return false;
    return true;
}

export function BlockchainDelegateOperationResponseDtoFromJSON(json: any): BlockchainDelegateOperationResponseDto {
    return BlockchainDelegateOperationResponseDtoFromJSONTyped(json, false);
}

export function BlockchainDelegateOperationResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainDelegateOperationResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'chainId': json['chainId'],
        'deploymentId': json['deploymentId'],
        'operationType': json['operationType'],
        'status': json['status'],
        'fromAddress': UniversalAddressFromJSON(json['fromAddress']),
        'toAddress': UniversalAddressFromJSON(json['toAddress']),
        'txId': json['txId'],
        'txHash': json['txHash'],
        'blockNumber': json['blockNumber'],
        'blockchainFee': json['blockchainFee'],
        'confirmations': json['confirmations'],
        'confirmedAt': json['confirmedAt'],
        'currencyId': json['currencyId'],
        'amount': json['amount'],
        'currency': CurrencyResponseDtoFromJSON(json['currency']),
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'resourceType': json['resourceType'],
        'recipient': json['recipient'],
        'isLocked': json['isLocked'],
    };
}

export function BlockchainDelegateOperationResponseDtoToJSON(json: any): BlockchainDelegateOperationResponseDto {
    return BlockchainDelegateOperationResponseDtoToJSONTyped(json, false);
}

export function BlockchainDelegateOperationResponseDtoToJSONTyped(value?: BlockchainDelegateOperationResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'chainId': value['chainId'],
        'deploymentId': value['deploymentId'],
        'operationType': value['operationType'],
        'status': value['status'],
        'fromAddress': UniversalAddressToJSON(value['fromAddress']),
        'toAddress': UniversalAddressToJSON(value['toAddress']),
        'txId': value['txId'],
        'txHash': value['txHash'],
        'blockNumber': value['blockNumber'],
        'blockchainFee': value['blockchainFee'],
        'confirmations': value['confirmations'],
        'confirmedAt': value['confirmedAt'],
        'currencyId': value['currencyId'],
        'amount': value['amount'],
        'currency': CurrencyResponseDtoToJSON(value['currency']),
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'resourceType': value['resourceType'],
        'recipient': value['recipient'],
        'isLocked': value['isLocked'],
    };
}

