/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockchainDeployOperationResponseDto } from './blockchain-deploy-operation-response-dto';
import {
    BlockchainDeployOperationResponseDtoFromJSON,
    BlockchainDeployOperationResponseDtoFromJSONTyped,
    BlockchainDeployOperationResponseDtoToJSON,
    BlockchainDeployOperationResponseDtoToJSONTyped,
} from './blockchain-deploy-operation-response-dto';

/**
 * 
 * @export
 * @interface BlockchainDeployOperationListResponseDto
 */
export interface BlockchainDeployOperationListResponseDto {
    /**
     * Total number of items across all pages
     * @type {number}
     * @memberof BlockchainDeployOperationListResponseDto
     */
    total: number;
    /**
     * Current page number (starts from 1)
     * @type {number}
     * @memberof BlockchainDeployOperationListResponseDto
     */
    page: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof BlockchainDeployOperationListResponseDto
     */
    pageSize: number;
    /**
     * 
     * @type {Array<BlockchainDeployOperationResponseDto>}
     * @memberof BlockchainDeployOperationListResponseDto
     */
    items: Array<BlockchainDeployOperationResponseDto>;
}

/**
 * Check if a given object implements the BlockchainDeployOperationListResponseDto interface.
 */
export function instanceOfBlockchainDeployOperationListResponseDto(value: object): value is BlockchainDeployOperationListResponseDto {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function BlockchainDeployOperationListResponseDtoFromJSON(json: any): BlockchainDeployOperationListResponseDto {
    return BlockchainDeployOperationListResponseDtoFromJSONTyped(json, false);
}

export function BlockchainDeployOperationListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainDeployOperationListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'items': ((json['items'] as Array<any>).map(BlockchainDeployOperationResponseDtoFromJSON)),
    };
}

export function BlockchainDeployOperationListResponseDtoToJSON(json: any): BlockchainDeployOperationListResponseDto {
    return BlockchainDeployOperationListResponseDtoToJSONTyped(json, false);
}

export function BlockchainDeployOperationListResponseDtoToJSONTyped(value?: BlockchainDeployOperationListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'items': ((value['items'] as Array<any>).map(BlockchainDeployOperationResponseDtoToJSON)),
    };
}

