/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockchainUnstakeOperationResponseDto } from './blockchain-unstake-operation-response-dto';
import {
    BlockchainUnstakeOperationResponseDtoFromJSON,
    BlockchainUnstakeOperationResponseDtoFromJSONTyped,
    BlockchainUnstakeOperationResponseDtoToJSON,
    BlockchainUnstakeOperationResponseDtoToJSONTyped,
} from './blockchain-unstake-operation-response-dto';

/**
 * 
 * @export
 * @interface BlockchainUnstakeOperationListResponseDto
 */
export interface BlockchainUnstakeOperationListResponseDto {
    /**
     * Total number of items across all pages
     * @type {number}
     * @memberof BlockchainUnstakeOperationListResponseDto
     */
    total: number;
    /**
     * Current page number (starts from 1)
     * @type {number}
     * @memberof BlockchainUnstakeOperationListResponseDto
     */
    page: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof BlockchainUnstakeOperationListResponseDto
     */
    pageSize: number;
    /**
     * 
     * @type {Array<BlockchainUnstakeOperationResponseDto>}
     * @memberof BlockchainUnstakeOperationListResponseDto
     */
    items: Array<BlockchainUnstakeOperationResponseDto>;
}

/**
 * Check if a given object implements the BlockchainUnstakeOperationListResponseDto interface.
 */
export function instanceOfBlockchainUnstakeOperationListResponseDto(value: object): value is BlockchainUnstakeOperationListResponseDto {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function BlockchainUnstakeOperationListResponseDtoFromJSON(json: any): BlockchainUnstakeOperationListResponseDto {
    return BlockchainUnstakeOperationListResponseDtoFromJSONTyped(json, false);
}

export function BlockchainUnstakeOperationListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainUnstakeOperationListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'items': ((json['items'] as Array<any>).map(BlockchainUnstakeOperationResponseDtoFromJSON)),
    };
}

export function BlockchainUnstakeOperationListResponseDtoToJSON(json: any): BlockchainUnstakeOperationListResponseDto {
    return BlockchainUnstakeOperationListResponseDtoToJSONTyped(json, false);
}

export function BlockchainUnstakeOperationListResponseDtoToJSONTyped(value?: BlockchainUnstakeOperationListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'items': ((value['items'] as Array<any>).map(BlockchainUnstakeOperationResponseDtoToJSON)),
    };
}

