/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockchainRejectOperationResponseDto } from './blockchain-reject-operation-response-dto';
import {
    BlockchainRejectOperationResponseDtoFromJSON,
    BlockchainRejectOperationResponseDtoFromJSONTyped,
    BlockchainRejectOperationResponseDtoToJSON,
    BlockchainRejectOperationResponseDtoToJSONTyped,
} from './blockchain-reject-operation-response-dto';

/**
 * 
 * @export
 * @interface BlockchainRejectOperationListResponseDto
 */
export interface BlockchainRejectOperationListResponseDto {
    /**
     * Total number of items across all pages
     * @type {number}
     * @memberof BlockchainRejectOperationListResponseDto
     */
    total: number;
    /**
     * Current page number (starts from 1)
     * @type {number}
     * @memberof BlockchainRejectOperationListResponseDto
     */
    page: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof BlockchainRejectOperationListResponseDto
     */
    pageSize: number;
    /**
     * 
     * @type {Array<BlockchainRejectOperationResponseDto>}
     * @memberof BlockchainRejectOperationListResponseDto
     */
    items: Array<BlockchainRejectOperationResponseDto>;
}

/**
 * Check if a given object implements the BlockchainRejectOperationListResponseDto interface.
 */
export function instanceOfBlockchainRejectOperationListResponseDto(value: object): value is BlockchainRejectOperationListResponseDto {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function BlockchainRejectOperationListResponseDtoFromJSON(json: any): BlockchainRejectOperationListResponseDto {
    return BlockchainRejectOperationListResponseDtoFromJSONTyped(json, false);
}

export function BlockchainRejectOperationListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainRejectOperationListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'items': ((json['items'] as Array<any>).map(BlockchainRejectOperationResponseDtoFromJSON)),
    };
}

export function BlockchainRejectOperationListResponseDtoToJSON(json: any): BlockchainRejectOperationListResponseDto {
    return BlockchainRejectOperationListResponseDtoToJSONTyped(json, false);
}

export function BlockchainRejectOperationListResponseDtoToJSONTyped(value?: BlockchainRejectOperationListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'items': ((value['items'] as Array<any>).map(BlockchainRejectOperationResponseDtoToJSON)),
    };
}

