/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockchainClaimToOperationResponseDto } from './blockchain-claim-to-operation-response-dto';
import {
    BlockchainClaimToOperationResponseDtoFromJSON,
    BlockchainClaimToOperationResponseDtoFromJSONTyped,
    BlockchainClaimToOperationResponseDtoToJSON,
    BlockchainClaimToOperationResponseDtoToJSONTyped,
} from './blockchain-claim-to-operation-response-dto';

/**
 * 
 * @export
 * @interface BlockchainClaimToOperationListResponseDto
 */
export interface BlockchainClaimToOperationListResponseDto {
    /**
     * Total number of items across all pages
     * @type {number}
     * @memberof BlockchainClaimToOperationListResponseDto
     */
    total: number;
    /**
     * Current page number (starts from 1)
     * @type {number}
     * @memberof BlockchainClaimToOperationListResponseDto
     */
    page: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof BlockchainClaimToOperationListResponseDto
     */
    pageSize: number;
    /**
     * 
     * @type {Array<BlockchainClaimToOperationResponseDto>}
     * @memberof BlockchainClaimToOperationListResponseDto
     */
    items: Array<BlockchainClaimToOperationResponseDto>;
}

/**
 * Check if a given object implements the BlockchainClaimToOperationListResponseDto interface.
 */
export function instanceOfBlockchainClaimToOperationListResponseDto(value: object): value is BlockchainClaimToOperationListResponseDto {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function BlockchainClaimToOperationListResponseDtoFromJSON(json: any): BlockchainClaimToOperationListResponseDto {
    return BlockchainClaimToOperationListResponseDtoFromJSONTyped(json, false);
}

export function BlockchainClaimToOperationListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainClaimToOperationListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'items': ((json['items'] as Array<any>).map(BlockchainClaimToOperationResponseDtoFromJSON)),
    };
}

export function BlockchainClaimToOperationListResponseDtoToJSON(json: any): BlockchainClaimToOperationListResponseDto {
    return BlockchainClaimToOperationListResponseDtoToJSONTyped(json, false);
}

export function BlockchainClaimToOperationListResponseDtoToJSONTyped(value?: BlockchainClaimToOperationListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'items': ((value['items'] as Array<any>).map(BlockchainClaimToOperationResponseDtoToJSON)),
    };
}

