/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UniversalAddress } from './universal-address';
import {
    UniversalAddressFromJSON,
    UniversalAddressFromJSONTyped,
    UniversalAddressToJSON,
    UniversalAddressToJSONTyped,
} from './universal-address';
import type { CurrencyResponseDto } from './currency-response-dto';
import {
    CurrencyResponseDtoFromJSON,
    CurrencyResponseDtoFromJSONTyped,
    CurrencyResponseDtoToJSON,
    CurrencyResponseDtoToJSONTyped,
} from './currency-response-dto';

/**
 * 
 * @export
 * @interface BlockchainClaimRewardsOperationResponseDto
 */
export interface BlockchainClaimRewardsOperationResponseDto {
    /**
     * Entity unique identifier
     * @type {string}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    id: string;
    /**
     * Chain ID
     * @type {string}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    chainId: string;
    /**
     * Deployment that owns the operation (null for legacy rows without deployment_id)
     * @type {string}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    deploymentId: string | null;
    /**
     * V2 operation type
     * @type {BlockchainClaimRewardsOperationResponseDtoOperationTypeEnum}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    operationType: BlockchainClaimRewardsOperationResponseDtoOperationTypeEnum;
    /**
     * V2 operation status
     * @type {BlockchainClaimRewardsOperationResponseDtoStatusEnum}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    status: BlockchainClaimRewardsOperationResponseDtoStatusEnum;
    /**
     * 
     * @type {UniversalAddress}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    fromAddress: UniversalAddress | null;
    /**
     * 
     * @type {UniversalAddress}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    toAddress: UniversalAddress | null;
    /**
     * Entity unique identifier
     * @type {string}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    txId: string | null;
    /**
     * Blockchain transaction hash (EVM 0x + 64 hex; TVM 64 hex)
     * @type {string}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    txHash: string | null;
    /**
     * Block number of the transaction
     * @type {string}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    blockNumber: string | null;
    /**
     * Blockchain transaction fee
     * @type {string}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    blockchainFee: string;
    /**
     * Number of blockchain confirmations
     * @type {number}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    confirmations: number;
    /**
     * Confirmation timestamp (null if not confirmed yet)
     * @type {string}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    confirmedAt: string | null;
    /**
     * The unique ID of the currency, ("{chainId}" or "{chainId}-{contractAddress}")
     * @type {string}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    currencyId: string | null;
    /**
     * Claimed reward TRX amount (null until the on-chain amount is observed)
     * @type {string}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    amount: string | null;
    /**
     * 
     * @type {CurrencyResponseDto}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    currency: CurrencyResponseDto | null;
    /**
     * Nonce (transaction ordering) as a non-negative integer string
     * @type {string}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    nonce: string | null;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    createdAt: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    updatedAt: string;
    /**
     * AML risk score (0–100); null when the operation has not been scored
     * @type {number}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    riskScore: number | null;
    /**
     * AML severity bucket (low/medium/high/severe); null when not scored
     * @type {BlockchainClaimRewardsOperationResponseDtoSeverityEnum}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    severity: BlockchainClaimRewardsOperationResponseDtoSeverityEnum | null;
    /**
     * AML decision reason; null when not scored or not applicable
     * @type {BlockchainClaimRewardsOperationResponseDtoReasonEnum}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    reason: BlockchainClaimRewardsOperationResponseDtoReasonEnum | null;
    /**
     * AML scoring provider ('crystal' when scored); null when operation has not been AML-scored
     * @type {BlockchainClaimRewardsOperationResponseDtoAmlProviderEnum}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    amlProvider: BlockchainClaimRewardsOperationResponseDtoAmlProviderEnum | null;
    /**
     * ISO 8601 of the latest concluded AML check; null when not scored
     * @type {string}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    amlScoredAt: string | null;
    /**
     * True while an AML check (initial scoring or rescore) is in flight for this operation
     * @type {boolean}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    amlCheckInProgress: boolean;
    /**
     * Id of the most recent AML check row for this operation; null when never checked
     * @type {string}
     * @memberof BlockchainClaimRewardsOperationResponseDto
     */
    latestAmlCheckId: string | null;
}


/**
 * @export
 */
export const BlockchainClaimRewardsOperationResponseDtoOperationTypeEnum = {
    Payout: 'PAYOUT',
    InvoiceDeposit: 'INVOICE_DEPOSIT',
    Claim: 'CLAIM',
    ClaimTo: 'CLAIM_TO',
    Deploy: 'DEPLOY',
    DirectDeposit: 'DIRECT_DEPOSIT',
    Reject: 'REJECT',
    SetConfig: 'SET_CONFIG',
    DappTransaction: 'DAPP_TRANSACTION',
    CrossChainTransfer: 'CROSS_CHAIN_TRANSFER',
    Cowswap: 'COWSWAP',
    SetWhitelist: 'SET_WHITELIST',
    Stake: 'STAKE',
    Unstake: 'UNSTAKE',
    CancelUnstaking: 'CANCEL_UNSTAKING',
    StakingWithdraw: 'STAKING_WITHDRAW',
    Vote: 'VOTE',
    ClaimRewards: 'CLAIM_REWARDS',
    Delegate: 'DELEGATE',
    Reclaim: 'RECLAIM'
} as const;
export type BlockchainClaimRewardsOperationResponseDtoOperationTypeEnum = typeof BlockchainClaimRewardsOperationResponseDtoOperationTypeEnum[keyof typeof BlockchainClaimRewardsOperationResponseDtoOperationTypeEnum];

/**
 * @export
 */
export const BlockchainClaimRewardsOperationResponseDtoStatusEnum = {
    Created: 'CREATED',
    AmlCheck: 'AML_CHECK',
    Pending: 'PENDING',
    Confirmed: 'CONFIRMED',
    Blocked: 'BLOCKED',
    Refunded: 'REFUNDED',
    Failed: 'FAILED',
    Cancelled: 'CANCELLED'
} as const;
export type BlockchainClaimRewardsOperationResponseDtoStatusEnum = typeof BlockchainClaimRewardsOperationResponseDtoStatusEnum[keyof typeof BlockchainClaimRewardsOperationResponseDtoStatusEnum];

/**
 * @export
 */
export const BlockchainClaimRewardsOperationResponseDtoSeverityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Severe: 'severe'
} as const;
export type BlockchainClaimRewardsOperationResponseDtoSeverityEnum = typeof BlockchainClaimRewardsOperationResponseDtoSeverityEnum[keyof typeof BlockchainClaimRewardsOperationResponseDtoSeverityEnum];

/**
 * @export
 */
export const BlockchainClaimRewardsOperationResponseDtoReasonEnum = {
    ThresholdExceeded: 'threshold_exceeded',
    SevereAlert: 'severe_alert',
    BudgetExhausted: 'budget_exhausted',
    ProviderFailed: 'provider_failed',
    CurrencyUnsupported: 'currency_unsupported'
} as const;
export type BlockchainClaimRewardsOperationResponseDtoReasonEnum = typeof BlockchainClaimRewardsOperationResponseDtoReasonEnum[keyof typeof BlockchainClaimRewardsOperationResponseDtoReasonEnum];

/**
 * @export
 */
export const BlockchainClaimRewardsOperationResponseDtoAmlProviderEnum = {
    Crystal: 'crystal'
} as const;
export type BlockchainClaimRewardsOperationResponseDtoAmlProviderEnum = typeof BlockchainClaimRewardsOperationResponseDtoAmlProviderEnum[keyof typeof BlockchainClaimRewardsOperationResponseDtoAmlProviderEnum];


/**
 * Check if a given object implements the BlockchainClaimRewardsOperationResponseDto interface.
 */
export function instanceOfBlockchainClaimRewardsOperationResponseDto(value: object): value is BlockchainClaimRewardsOperationResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    if (!('deploymentId' in value) || value['deploymentId'] === undefined) return false;
    if (!('operationType' in value) || value['operationType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('fromAddress' in value) || value['fromAddress'] === undefined) return false;
    if (!('toAddress' in value) || value['toAddress'] === undefined) return false;
    if (!('txId' in value) || value['txId'] === undefined) return false;
    if (!('txHash' in value) || value['txHash'] === undefined) return false;
    if (!('blockNumber' in value) || value['blockNumber'] === undefined) return false;
    if (!('blockchainFee' in value) || value['blockchainFee'] === undefined) return false;
    if (!('confirmations' in value) || value['confirmations'] === undefined) return false;
    if (!('confirmedAt' in value) || value['confirmedAt'] === undefined) return false;
    if (!('currencyId' in value) || value['currencyId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('riskScore' in value) || value['riskScore'] === undefined) return false;
    if (!('severity' in value) || value['severity'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('amlProvider' in value) || value['amlProvider'] === undefined) return false;
    if (!('amlScoredAt' in value) || value['amlScoredAt'] === undefined) return false;
    if (!('amlCheckInProgress' in value) || value['amlCheckInProgress'] === undefined) return false;
    if (!('latestAmlCheckId' in value) || value['latestAmlCheckId'] === undefined) return false;
    return true;
}

export function BlockchainClaimRewardsOperationResponseDtoFromJSON(json: any): BlockchainClaimRewardsOperationResponseDto {
    return BlockchainClaimRewardsOperationResponseDtoFromJSONTyped(json, false);
}

export function BlockchainClaimRewardsOperationResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainClaimRewardsOperationResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'chainId': json['chainId'],
        'deploymentId': json['deploymentId'],
        'operationType': json['operationType'],
        'status': json['status'],
        'fromAddress': UniversalAddressFromJSON(json['fromAddress']),
        'toAddress': UniversalAddressFromJSON(json['toAddress']),
        'txId': json['txId'],
        'txHash': json['txHash'],
        'blockNumber': json['blockNumber'],
        'blockchainFee': json['blockchainFee'],
        'confirmations': json['confirmations'],
        'confirmedAt': json['confirmedAt'],
        'currencyId': json['currencyId'],
        'amount': json['amount'],
        'currency': CurrencyResponseDtoFromJSON(json['currency']),
        'nonce': json['nonce'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'riskScore': json['riskScore'],
        'severity': json['severity'],
        'reason': json['reason'],
        'amlProvider': json['amlProvider'],
        'amlScoredAt': json['amlScoredAt'],
        'amlCheckInProgress': json['amlCheckInProgress'],
        'latestAmlCheckId': json['latestAmlCheckId'],
    };
}

export function BlockchainClaimRewardsOperationResponseDtoToJSON(json: any): BlockchainClaimRewardsOperationResponseDto {
    return BlockchainClaimRewardsOperationResponseDtoToJSONTyped(json, false);
}

export function BlockchainClaimRewardsOperationResponseDtoToJSONTyped(value?: BlockchainClaimRewardsOperationResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'chainId': value['chainId'],
        'deploymentId': value['deploymentId'],
        'operationType': value['operationType'],
        'status': value['status'],
        'fromAddress': UniversalAddressToJSON(value['fromAddress']),
        'toAddress': UniversalAddressToJSON(value['toAddress']),
        'txId': value['txId'],
        'txHash': value['txHash'],
        'blockNumber': value['blockNumber'],
        'blockchainFee': value['blockchainFee'],
        'confirmations': value['confirmations'],
        'confirmedAt': value['confirmedAt'],
        'currencyId': value['currencyId'],
        'amount': value['amount'],
        'currency': CurrencyResponseDtoToJSON(value['currency']),
        'nonce': value['nonce'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'riskScore': value['riskScore'],
        'severity': value['severity'],
        'reason': value['reason'],
        'amlProvider': value['amlProvider'],
        'amlScoredAt': value['amlScoredAt'],
        'amlCheckInProgress': value['amlCheckInProgress'],
        'latestAmlCheckId': value['latestAmlCheckId'],
    };
}

