/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockchainReclaimOperationResponseDto } from './blockchain-reclaim-operation-response-dto';
import {
    BlockchainReclaimOperationResponseDtoFromJSON,
    BlockchainReclaimOperationResponseDtoFromJSONTyped,
    BlockchainReclaimOperationResponseDtoToJSON,
    BlockchainReclaimOperationResponseDtoToJSONTyped,
} from './blockchain-reclaim-operation-response-dto';

/**
 * 
 * @export
 * @interface BlockchainReclaimOperationListResponseDto
 */
export interface BlockchainReclaimOperationListResponseDto {
    /**
     * Total number of items across all pages
     * @type {number}
     * @memberof BlockchainReclaimOperationListResponseDto
     */
    total: number;
    /**
     * Current page number (starts from 1)
     * @type {number}
     * @memberof BlockchainReclaimOperationListResponseDto
     */
    page: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof BlockchainReclaimOperationListResponseDto
     */
    pageSize: number;
    /**
     * 
     * @type {Array<BlockchainReclaimOperationResponseDto>}
     * @memberof BlockchainReclaimOperationListResponseDto
     */
    items: Array<BlockchainReclaimOperationResponseDto>;
}

/**
 * Check if a given object implements the BlockchainReclaimOperationListResponseDto interface.
 */
export function instanceOfBlockchainReclaimOperationListResponseDto(value: object): value is BlockchainReclaimOperationListResponseDto {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function BlockchainReclaimOperationListResponseDtoFromJSON(json: any): BlockchainReclaimOperationListResponseDto {
    return BlockchainReclaimOperationListResponseDtoFromJSONTyped(json, false);
}

export function BlockchainReclaimOperationListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainReclaimOperationListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'items': ((json['items'] as Array<any>).map(BlockchainReclaimOperationResponseDtoFromJSON)),
    };
}

export function BlockchainReclaimOperationListResponseDtoToJSON(json: any): BlockchainReclaimOperationListResponseDto {
    return BlockchainReclaimOperationListResponseDtoToJSONTyped(json, false);
}

export function BlockchainReclaimOperationListResponseDtoToJSONTyped(value?: BlockchainReclaimOperationListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'items': ((value['items'] as Array<any>).map(BlockchainReclaimOperationResponseDtoToJSON)),
    };
}

