/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UniversalAddress } from './universal-address';
import {
    UniversalAddressFromJSON,
    UniversalAddressFromJSONTyped,
    UniversalAddressToJSON,
    UniversalAddressToJSONTyped,
} from './universal-address';
import type { CurrencyResponseDto } from './currency-response-dto';
import {
    CurrencyResponseDtoFromJSON,
    CurrencyResponseDtoFromJSONTyped,
    CurrencyResponseDtoToJSON,
    CurrencyResponseDtoToJSONTyped,
} from './currency-response-dto';

/**
 * 
 * @export
 * @interface BlockchainStakingWithdrawOperationResponseDto
 */
export interface BlockchainStakingWithdrawOperationResponseDto {
    /**
     * Entity unique identifier
     * @type {string}
     * @memberof BlockchainStakingWithdrawOperationResponseDto
     */
    id: string;
    /**
     * Chain ID
     * @type {string}
     * @memberof BlockchainStakingWithdrawOperationResponseDto
     */
    chainId: string;
    /**
     * Deployment that owns the operation (null for legacy rows without deployment_id)
     * @type {string}
     * @memberof BlockchainStakingWithdrawOperationResponseDto
     */
    deploymentId: string | null;
    /**
     * V2 operation type
     * @type {BlockchainStakingWithdrawOperationResponseDtoOperationTypeEnum}
     * @memberof BlockchainStakingWithdrawOperationResponseDto
     */
    operationType: BlockchainStakingWithdrawOperationResponseDtoOperationTypeEnum;
    /**
     * V2 operation status
     * @type {BlockchainStakingWithdrawOperationResponseDtoStatusEnum}
     * @memberof BlockchainStakingWithdrawOperationResponseDto
     */
    status: BlockchainStakingWithdrawOperationResponseDtoStatusEnum;
    /**
     * 
     * @type {UniversalAddress}
     * @memberof BlockchainStakingWithdrawOperationResponseDto
     */
    fromAddress: UniversalAddress | null;
    /**
     * 
     * @type {UniversalAddress}
     * @memberof BlockchainStakingWithdrawOperationResponseDto
     */
    toAddress: UniversalAddress | null;
    /**
     * Entity unique identifier
     * @type {string}
     * @memberof BlockchainStakingWithdrawOperationResponseDto
     */
    txId: string | null;
    /**
     * Blockchain transaction hash (EVM 0x + 64 hex; TVM 64 hex)
     * @type {string}
     * @memberof BlockchainStakingWithdrawOperationResponseDto
     */
    txHash: string | null;
    /**
     * Block number of the transaction
     * @type {string}
     * @memberof BlockchainStakingWithdrawOperationResponseDto
     */
    blockNumber: string | null;
    /**
     * Blockchain transaction fee
     * @type {string}
     * @memberof BlockchainStakingWithdrawOperationResponseDto
     */
    blockchainFee: string;
    /**
     * Number of blockchain confirmations
     * @type {number}
     * @memberof BlockchainStakingWithdrawOperationResponseDto
     */
    confirmations: number;
    /**
     * Confirmation timestamp (null if not confirmed yet)
     * @type {string}
     * @memberof BlockchainStakingWithdrawOperationResponseDto
     */
    confirmedAt: string | null;
    /**
     * The unique ID of the currency, ("{chainId}" or "{chainId}-{contractAddress}")
     * @type {string}
     * @memberof BlockchainStakingWithdrawOperationResponseDto
     */
    currencyId: string | null;
    /**
     * Withdrawn TRX amount (null until the on-chain amount is observed)
     * @type {string}
     * @memberof BlockchainStakingWithdrawOperationResponseDto
     */
    amount: string | null;
    /**
     * 
     * @type {CurrencyResponseDto}
     * @memberof BlockchainStakingWithdrawOperationResponseDto
     */
    currency: CurrencyResponseDto | null;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof BlockchainStakingWithdrawOperationResponseDto
     */
    createdAt: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof BlockchainStakingWithdrawOperationResponseDto
     */
    updatedAt: string;
}


/**
 * @export
 */
export const BlockchainStakingWithdrawOperationResponseDtoOperationTypeEnum = {
    Payout: 'PAYOUT',
    InvoiceDeposit: 'INVOICE_DEPOSIT',
    Claim: 'CLAIM',
    Deploy: 'DEPLOY',
    DirectDeposit: 'DIRECT_DEPOSIT',
    Reject: 'REJECT',
    SetConfig: 'SET_CONFIG',
    DappTransaction: 'DAPP_TRANSACTION',
    CrossChainTransfer: 'CROSS_CHAIN_TRANSFER',
    Stake: 'STAKE',
    Unstake: 'UNSTAKE',
    CancelUnstaking: 'CANCEL_UNSTAKING',
    StakingWithdraw: 'STAKING_WITHDRAW',
    Vote: 'VOTE',
    ClaimRewards: 'CLAIM_REWARDS',
    Delegate: 'DELEGATE',
    Reclaim: 'RECLAIM'
} as const;
export type BlockchainStakingWithdrawOperationResponseDtoOperationTypeEnum = typeof BlockchainStakingWithdrawOperationResponseDtoOperationTypeEnum[keyof typeof BlockchainStakingWithdrawOperationResponseDtoOperationTypeEnum];

/**
 * @export
 */
export const BlockchainStakingWithdrawOperationResponseDtoStatusEnum = {
    Created: 'CREATED',
    Pending: 'PENDING',
    Confirmed: 'CONFIRMED',
    Failed: 'FAILED',
    Cancelled: 'CANCELLED'
} as const;
export type BlockchainStakingWithdrawOperationResponseDtoStatusEnum = typeof BlockchainStakingWithdrawOperationResponseDtoStatusEnum[keyof typeof BlockchainStakingWithdrawOperationResponseDtoStatusEnum];


/**
 * Check if a given object implements the BlockchainStakingWithdrawOperationResponseDto interface.
 */
export function instanceOfBlockchainStakingWithdrawOperationResponseDto(value: object): value is BlockchainStakingWithdrawOperationResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    if (!('deploymentId' in value) || value['deploymentId'] === undefined) return false;
    if (!('operationType' in value) || value['operationType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('fromAddress' in value) || value['fromAddress'] === undefined) return false;
    if (!('toAddress' in value) || value['toAddress'] === undefined) return false;
    if (!('txId' in value) || value['txId'] === undefined) return false;
    if (!('txHash' in value) || value['txHash'] === undefined) return false;
    if (!('blockNumber' in value) || value['blockNumber'] === undefined) return false;
    if (!('blockchainFee' in value) || value['blockchainFee'] === undefined) return false;
    if (!('confirmations' in value) || value['confirmations'] === undefined) return false;
    if (!('confirmedAt' in value) || value['confirmedAt'] === undefined) return false;
    if (!('currencyId' in value) || value['currencyId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function BlockchainStakingWithdrawOperationResponseDtoFromJSON(json: any): BlockchainStakingWithdrawOperationResponseDto {
    return BlockchainStakingWithdrawOperationResponseDtoFromJSONTyped(json, false);
}

export function BlockchainStakingWithdrawOperationResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainStakingWithdrawOperationResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'chainId': json['chainId'],
        'deploymentId': json['deploymentId'],
        'operationType': json['operationType'],
        'status': json['status'],
        'fromAddress': UniversalAddressFromJSON(json['fromAddress']),
        'toAddress': UniversalAddressFromJSON(json['toAddress']),
        'txId': json['txId'],
        'txHash': json['txHash'],
        'blockNumber': json['blockNumber'],
        'blockchainFee': json['blockchainFee'],
        'confirmations': json['confirmations'],
        'confirmedAt': json['confirmedAt'],
        'currencyId': json['currencyId'],
        'amount': json['amount'],
        'currency': CurrencyResponseDtoFromJSON(json['currency']),
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function BlockchainStakingWithdrawOperationResponseDtoToJSON(json: any): BlockchainStakingWithdrawOperationResponseDto {
    return BlockchainStakingWithdrawOperationResponseDtoToJSONTyped(json, false);
}

export function BlockchainStakingWithdrawOperationResponseDtoToJSONTyped(value?: BlockchainStakingWithdrawOperationResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'chainId': value['chainId'],
        'deploymentId': value['deploymentId'],
        'operationType': value['operationType'],
        'status': value['status'],
        'fromAddress': UniversalAddressToJSON(value['fromAddress']),
        'toAddress': UniversalAddressToJSON(value['toAddress']),
        'txId': value['txId'],
        'txHash': value['txHash'],
        'blockNumber': value['blockNumber'],
        'blockchainFee': value['blockchainFee'],
        'confirmations': value['confirmations'],
        'confirmedAt': value['confirmedAt'],
        'currencyId': value['currencyId'],
        'amount': value['amount'],
        'currency': CurrencyResponseDtoToJSON(value['currency']),
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

