/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockchainTransactionOperationPreview
 */
export interface BlockchainTransactionOperationPreview {
    /**
     * Entity unique identifier
     * @type {string}
     * @memberof BlockchainTransactionOperationPreview
     */
    id: string;
    /**
     * Operation type
     * @type {BlockchainTransactionOperationPreviewTypeEnum}
     * @memberof BlockchainTransactionOperationPreview
     */
    type: BlockchainTransactionOperationPreviewTypeEnum;
    /**
     * The unique ID of the currency, ("{chainId}" or "{chainId}-{contractAddress}")
     * @type {string}
     * @memberof BlockchainTransactionOperationPreview
     */
    currencyId: string | null;
    /**
     * Operation amount; null when the type carries no amount (DEPLOY/REJECT/SET_CONFIG/DAPP_TRANSACTION)
     * @type {string}
     * @memberof BlockchainTransactionOperationPreview
     */
    amount: string | null;
}


/**
 * @export
 */
export const BlockchainTransactionOperationPreviewTypeEnum = {
    Payout: 'PAYOUT',
    InvoiceDeposit: 'INVOICE_DEPOSIT',
    Claim: 'CLAIM',
    Deploy: 'DEPLOY',
    DirectDeposit: 'DIRECT_DEPOSIT',
    Reject: 'REJECT',
    SetConfig: 'SET_CONFIG',
    DappTransaction: 'DAPP_TRANSACTION',
    CrossChainTransfer: 'CROSS_CHAIN_TRANSFER',
    Stake: 'STAKE',
    Unstake: 'UNSTAKE',
    CancelUnstaking: 'CANCEL_UNSTAKING',
    StakingWithdraw: 'STAKING_WITHDRAW',
    Vote: 'VOTE',
    ClaimRewards: 'CLAIM_REWARDS',
    Delegate: 'DELEGATE',
    Reclaim: 'RECLAIM'
} as const;
export type BlockchainTransactionOperationPreviewTypeEnum = typeof BlockchainTransactionOperationPreviewTypeEnum[keyof typeof BlockchainTransactionOperationPreviewTypeEnum];


/**
 * Check if a given object implements the BlockchainTransactionOperationPreview interface.
 */
export function instanceOfBlockchainTransactionOperationPreview(value: object): value is BlockchainTransactionOperationPreview {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('currencyId' in value) || value['currencyId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function BlockchainTransactionOperationPreviewFromJSON(json: any): BlockchainTransactionOperationPreview {
    return BlockchainTransactionOperationPreviewFromJSONTyped(json, false);
}

export function BlockchainTransactionOperationPreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainTransactionOperationPreview {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'currencyId': json['currencyId'],
        'amount': json['amount'],
    };
}

export function BlockchainTransactionOperationPreviewToJSON(json: any): BlockchainTransactionOperationPreview {
    return BlockchainTransactionOperationPreviewToJSONTyped(json, false);
}

export function BlockchainTransactionOperationPreviewToJSONTyped(value?: BlockchainTransactionOperationPreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'currencyId': value['currencyId'],
        'amount': value['amount'],
    };
}

