/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockchainClaimRewardsOperationResponseDto } from './blockchain-claim-rewards-operation-response-dto';
import {
    BlockchainClaimRewardsOperationResponseDtoFromJSON,
    BlockchainClaimRewardsOperationResponseDtoFromJSONTyped,
    BlockchainClaimRewardsOperationResponseDtoToJSON,
    BlockchainClaimRewardsOperationResponseDtoToJSONTyped,
} from './blockchain-claim-rewards-operation-response-dto';

/**
 * 
 * @export
 * @interface BlockchainClaimRewardsOperationListResponseDto
 */
export interface BlockchainClaimRewardsOperationListResponseDto {
    /**
     * Total number of items across all pages
     * @type {number}
     * @memberof BlockchainClaimRewardsOperationListResponseDto
     */
    total: number;
    /**
     * Current page number (starts from 1)
     * @type {number}
     * @memberof BlockchainClaimRewardsOperationListResponseDto
     */
    page: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof BlockchainClaimRewardsOperationListResponseDto
     */
    pageSize: number;
    /**
     * 
     * @type {Array<BlockchainClaimRewardsOperationResponseDto>}
     * @memberof BlockchainClaimRewardsOperationListResponseDto
     */
    items: Array<BlockchainClaimRewardsOperationResponseDto>;
}

/**
 * Check if a given object implements the BlockchainClaimRewardsOperationListResponseDto interface.
 */
export function instanceOfBlockchainClaimRewardsOperationListResponseDto(value: object): value is BlockchainClaimRewardsOperationListResponseDto {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function BlockchainClaimRewardsOperationListResponseDtoFromJSON(json: any): BlockchainClaimRewardsOperationListResponseDto {
    return BlockchainClaimRewardsOperationListResponseDtoFromJSONTyped(json, false);
}

export function BlockchainClaimRewardsOperationListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainClaimRewardsOperationListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'items': ((json['items'] as Array<any>).map(BlockchainClaimRewardsOperationResponseDtoFromJSON)),
    };
}

export function BlockchainClaimRewardsOperationListResponseDtoToJSON(json: any): BlockchainClaimRewardsOperationListResponseDto {
    return BlockchainClaimRewardsOperationListResponseDtoToJSONTyped(json, false);
}

export function BlockchainClaimRewardsOperationListResponseDtoToJSONTyped(value?: BlockchainClaimRewardsOperationListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'items': ((value['items'] as Array<any>).map(BlockchainClaimRewardsOperationResponseDtoToJSON)),
    };
}

