/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockchainDappTransactionOperationResponseDto } from './blockchain-dapp-transaction-operation-response-dto';
import {
    BlockchainDappTransactionOperationResponseDtoFromJSON,
    BlockchainDappTransactionOperationResponseDtoFromJSONTyped,
    BlockchainDappTransactionOperationResponseDtoToJSON,
    BlockchainDappTransactionOperationResponseDtoToJSONTyped,
} from './blockchain-dapp-transaction-operation-response-dto';

/**
 * 
 * @export
 * @interface BlockchainDappTransactionOperationListResponseDto
 */
export interface BlockchainDappTransactionOperationListResponseDto {
    /**
     * Total number of items across all pages
     * @type {number}
     * @memberof BlockchainDappTransactionOperationListResponseDto
     */
    total: number;
    /**
     * Current page number (starts from 1)
     * @type {number}
     * @memberof BlockchainDappTransactionOperationListResponseDto
     */
    page: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof BlockchainDappTransactionOperationListResponseDto
     */
    pageSize: number;
    /**
     * 
     * @type {Array<BlockchainDappTransactionOperationResponseDto>}
     * @memberof BlockchainDappTransactionOperationListResponseDto
     */
    items: Array<BlockchainDappTransactionOperationResponseDto>;
}

/**
 * Check if a given object implements the BlockchainDappTransactionOperationListResponseDto interface.
 */
export function instanceOfBlockchainDappTransactionOperationListResponseDto(value: object): value is BlockchainDappTransactionOperationListResponseDto {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function BlockchainDappTransactionOperationListResponseDtoFromJSON(json: any): BlockchainDappTransactionOperationListResponseDto {
    return BlockchainDappTransactionOperationListResponseDtoFromJSONTyped(json, false);
}

export function BlockchainDappTransactionOperationListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainDappTransactionOperationListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'items': ((json['items'] as Array<any>).map(BlockchainDappTransactionOperationResponseDtoFromJSON)),
    };
}

export function BlockchainDappTransactionOperationListResponseDtoToJSON(json: any): BlockchainDappTransactionOperationListResponseDto {
    return BlockchainDappTransactionOperationListResponseDtoToJSONTyped(json, false);
}

export function BlockchainDappTransactionOperationListResponseDtoToJSONTyped(value?: BlockchainDappTransactionOperationListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'items': ((value['items'] as Array<any>).map(BlockchainDappTransactionOperationResponseDtoToJSON)),
    };
}

