/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockchainVoteOperationResponseDto } from './blockchain-vote-operation-response-dto';
import {
    BlockchainVoteOperationResponseDtoFromJSON,
    BlockchainVoteOperationResponseDtoFromJSONTyped,
    BlockchainVoteOperationResponseDtoToJSON,
    BlockchainVoteOperationResponseDtoToJSONTyped,
} from './blockchain-vote-operation-response-dto';

/**
 * 
 * @export
 * @interface BlockchainVoteOperationListResponseDto
 */
export interface BlockchainVoteOperationListResponseDto {
    /**
     * Total number of items across all pages
     * @type {number}
     * @memberof BlockchainVoteOperationListResponseDto
     */
    total: number;
    /**
     * Current page number (starts from 1)
     * @type {number}
     * @memberof BlockchainVoteOperationListResponseDto
     */
    page: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof BlockchainVoteOperationListResponseDto
     */
    pageSize: number;
    /**
     * 
     * @type {Array<BlockchainVoteOperationResponseDto>}
     * @memberof BlockchainVoteOperationListResponseDto
     */
    items: Array<BlockchainVoteOperationResponseDto>;
}

/**
 * Check if a given object implements the BlockchainVoteOperationListResponseDto interface.
 */
export function instanceOfBlockchainVoteOperationListResponseDto(value: object): value is BlockchainVoteOperationListResponseDto {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function BlockchainVoteOperationListResponseDtoFromJSON(json: any): BlockchainVoteOperationListResponseDto {
    return BlockchainVoteOperationListResponseDtoFromJSONTyped(json, false);
}

export function BlockchainVoteOperationListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainVoteOperationListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'items': ((json['items'] as Array<any>).map(BlockchainVoteOperationResponseDtoFromJSON)),
    };
}

export function BlockchainVoteOperationListResponseDtoToJSON(json: any): BlockchainVoteOperationListResponseDto {
    return BlockchainVoteOperationListResponseDtoToJSONTyped(json, false);
}

export function BlockchainVoteOperationListResponseDtoToJSONTyped(value?: BlockchainVoteOperationListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'items': ((value['items'] as Array<any>).map(BlockchainVoteOperationResponseDtoToJSON)),
    };
}

