/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UniversalAddress } from './universal-address';
import {
    UniversalAddressFromJSON,
    UniversalAddressFromJSONTyped,
    UniversalAddressToJSON,
    UniversalAddressToJSONTyped,
} from './universal-address';
import type { BlockchainTransactionOperationPreview } from './blockchain-transaction-operation-preview';
import {
    BlockchainTransactionOperationPreviewFromJSON,
    BlockchainTransactionOperationPreviewFromJSONTyped,
    BlockchainTransactionOperationPreviewToJSON,
    BlockchainTransactionOperationPreviewToJSONTyped,
} from './blockchain-transaction-operation-preview';

/**
 * 
 * @export
 * @interface BlockchainTransactionResponseDto
 */
export interface BlockchainTransactionResponseDto {
    /**
     * Entity unique identifier
     * @type {string}
     * @memberof BlockchainTransactionResponseDto
     */
    id: string;
    /**
     * Chain ID
     * @type {string}
     * @memberof BlockchainTransactionResponseDto
     */
    chainId: string;
    /**
     * Blockchain transaction hash (EVM 0x + 64 hex; TVM 64 hex)
     * @type {string}
     * @memberof BlockchainTransactionResponseDto
     */
    txHash: string;
    /**
     * 
     * @type {UniversalAddress}
     * @memberof BlockchainTransactionResponseDto
     */
    fromAddress: UniversalAddress;
    /**
     * 
     * @type {UniversalAddress}
     * @memberof BlockchainTransactionResponseDto
     */
    toAddress: UniversalAddress | null;
    /**
     * Native value transferred with the transaction (wei / sun, integer string)
     * @type {string}
     * @memberof BlockchainTransactionResponseDto
     */
    value: string;
    /**
     * Blockchain transaction fee
     * @type {string}
     * @memberof BlockchainTransactionResponseDto
     */
    blockchainFee: string;
    /**
     * Block hash containing the transaction (null while pending)
     * @type {string}
     * @memberof BlockchainTransactionResponseDto
     */
    blockHash: string | null;
    /**
     * Block number of the transaction
     * @type {string}
     * @memberof BlockchainTransactionResponseDto
     */
    blockNumber: string | null;
    /**
     * Blockchain transaction status
     * @type {BlockchainTransactionResponseDtoStatusEnum}
     * @memberof BlockchainTransactionResponseDto
     */
    status: BlockchainTransactionResponseDtoStatusEnum;
    /**
     * Number of blockchain confirmations
     * @type {number}
     * @memberof BlockchainTransactionResponseDto
     */
    confirmations: number;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof BlockchainTransactionResponseDto
     */
    createdAt: string;
    /**
     * Timestamp when the transaction reached confirmation threshold (null if not confirmed yet)
     * @type {string}
     * @memberof BlockchainTransactionResponseDto
     */
    confirmedAt: string | null;
    /**
     * Operations attached to this blockchain transaction (deployment-scoped preview, typically 1-3)
     * @type {Array<BlockchainTransactionOperationPreview>}
     * @memberof BlockchainTransactionResponseDto
     */
    operations: Array<BlockchainTransactionOperationPreview>;
}


/**
 * @export
 */
export const BlockchainTransactionResponseDtoStatusEnum = {
    Executing: 'executing',
    Pending: 'pending',
    Confirmed: 'confirmed',
    Failed: 'failed'
} as const;
export type BlockchainTransactionResponseDtoStatusEnum = typeof BlockchainTransactionResponseDtoStatusEnum[keyof typeof BlockchainTransactionResponseDtoStatusEnum];


/**
 * Check if a given object implements the BlockchainTransactionResponseDto interface.
 */
export function instanceOfBlockchainTransactionResponseDto(value: object): value is BlockchainTransactionResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    if (!('txHash' in value) || value['txHash'] === undefined) return false;
    if (!('fromAddress' in value) || value['fromAddress'] === undefined) return false;
    if (!('toAddress' in value) || value['toAddress'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('blockchainFee' in value) || value['blockchainFee'] === undefined) return false;
    if (!('blockHash' in value) || value['blockHash'] === undefined) return false;
    if (!('blockNumber' in value) || value['blockNumber'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('confirmations' in value) || value['confirmations'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('confirmedAt' in value) || value['confirmedAt'] === undefined) return false;
    if (!('operations' in value) || value['operations'] === undefined) return false;
    return true;
}

export function BlockchainTransactionResponseDtoFromJSON(json: any): BlockchainTransactionResponseDto {
    return BlockchainTransactionResponseDtoFromJSONTyped(json, false);
}

export function BlockchainTransactionResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainTransactionResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'chainId': json['chainId'],
        'txHash': json['txHash'],
        'fromAddress': UniversalAddressFromJSON(json['fromAddress']),
        'toAddress': UniversalAddressFromJSON(json['toAddress']),
        'value': json['value'],
        'blockchainFee': json['blockchainFee'],
        'blockHash': json['blockHash'],
        'blockNumber': json['blockNumber'],
        'status': json['status'],
        'confirmations': json['confirmations'],
        'createdAt': json['createdAt'],
        'confirmedAt': json['confirmedAt'],
        'operations': ((json['operations'] as Array<any>).map(BlockchainTransactionOperationPreviewFromJSON)),
    };
}

export function BlockchainTransactionResponseDtoToJSON(json: any): BlockchainTransactionResponseDto {
    return BlockchainTransactionResponseDtoToJSONTyped(json, false);
}

export function BlockchainTransactionResponseDtoToJSONTyped(value?: BlockchainTransactionResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'chainId': value['chainId'],
        'txHash': value['txHash'],
        'fromAddress': UniversalAddressToJSON(value['fromAddress']),
        'toAddress': UniversalAddressToJSON(value['toAddress']),
        'value': value['value'],
        'blockchainFee': value['blockchainFee'],
        'blockHash': value['blockHash'],
        'blockNumber': value['blockNumber'],
        'status': value['status'],
        'confirmations': value['confirmations'],
        'createdAt': value['createdAt'],
        'confirmedAt': value['confirmedAt'],
        'operations': ((value['operations'] as Array<any>).map(BlockchainTransactionOperationPreviewToJSON)),
    };
}

