/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockchainPayoutOperationResponseDto } from './blockchain-payout-operation-response-dto';
import {
    BlockchainPayoutOperationResponseDtoFromJSON,
    BlockchainPayoutOperationResponseDtoFromJSONTyped,
    BlockchainPayoutOperationResponseDtoToJSON,
    BlockchainPayoutOperationResponseDtoToJSONTyped,
} from './blockchain-payout-operation-response-dto';

/**
 * 
 * @export
 * @interface BlockchainPayoutOperationListResponseDto
 */
export interface BlockchainPayoutOperationListResponseDto {
    /**
     * Total number of items across all pages
     * @type {number}
     * @memberof BlockchainPayoutOperationListResponseDto
     */
    total: number;
    /**
     * Current page number (starts from 1)
     * @type {number}
     * @memberof BlockchainPayoutOperationListResponseDto
     */
    page: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof BlockchainPayoutOperationListResponseDto
     */
    pageSize: number;
    /**
     * 
     * @type {Array<BlockchainPayoutOperationResponseDto>}
     * @memberof BlockchainPayoutOperationListResponseDto
     */
    items: Array<BlockchainPayoutOperationResponseDto>;
}

/**
 * Check if a given object implements the BlockchainPayoutOperationListResponseDto interface.
 */
export function instanceOfBlockchainPayoutOperationListResponseDto(value: object): value is BlockchainPayoutOperationListResponseDto {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function BlockchainPayoutOperationListResponseDtoFromJSON(json: any): BlockchainPayoutOperationListResponseDto {
    return BlockchainPayoutOperationListResponseDtoFromJSONTyped(json, false);
}

export function BlockchainPayoutOperationListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainPayoutOperationListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'items': ((json['items'] as Array<any>).map(BlockchainPayoutOperationResponseDtoFromJSON)),
    };
}

export function BlockchainPayoutOperationListResponseDtoToJSON(json: any): BlockchainPayoutOperationListResponseDto {
    return BlockchainPayoutOperationListResponseDtoToJSONTyped(json, false);
}

export function BlockchainPayoutOperationListResponseDtoToJSONTyped(value?: BlockchainPayoutOperationListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'items': ((value['items'] as Array<any>).map(BlockchainPayoutOperationResponseDtoToJSON)),
    };
}

