/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CallbackSecretResponseDto
 */
export interface CallbackSecretResponseDto {
    /**
     * Generated callback secret for HMAC signing (shown only once)
     * @type {string}
     * @memberof CallbackSecretResponseDto
     */
    secret: string;
}

/**
 * Check if a given object implements the CallbackSecretResponseDto interface.
 */
export function instanceOfCallbackSecretResponseDto(value: object): value is CallbackSecretResponseDto {
    if (!('secret' in value) || value['secret'] === undefined) return false;
    return true;
}

export function CallbackSecretResponseDtoFromJSON(json: any): CallbackSecretResponseDto {
    return CallbackSecretResponseDtoFromJSONTyped(json, false);
}

export function CallbackSecretResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CallbackSecretResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'secret': json['secret'],
    };
}

export function CallbackSecretResponseDtoToJSON(json: any): CallbackSecretResponseDto {
    return CallbackSecretResponseDtoToJSONTyped(json, false);
}

export function CallbackSecretResponseDtoToJSONTyped(value?: CallbackSecretResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'secret': value['secret'],
    };
}

