/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Callback
 */
export interface Callback {
    /**
     * Entity unique identifier
     * @type {string}
     * @memberof Callback
     */
    id: string;
    /**
     * URL to send the callback to
     * @type {string}
     * @memberof Callback
     */
    url: string;
    /**
     * Type of callback event
     * @type {string}
     * @memberof Callback
     */
    type: CallbackTypeEnum;
    /**
     * Current status of the callback
     * @type {string}
     * @memberof Callback
     */
    status: CallbackStatusEnum;
    /**
     * ID of the operation (invoice or payout)
     * @type {string}
     * @memberof Callback
     */
    operationId: string;
    /**
     * Type of operation
     * @type {string}
     * @memberof Callback
     */
    operationType: CallbackOperationTypeEnum;
    /**
     * Number of attempts made to send this callback
     * @type {number}
     * @memberof Callback
     */
    attempt: number;
    /**
     * Timestamp when the callback was last sent
     * @type {Date}
     * @memberof Callback
     */
    timeSent: Date | null;
    /**
     * HTTP response code from the callback endpoint
     * @type {number}
     * @memberof Callback
     */
    responseCode: number | null;
    /**
     * HTTP response body from the callback endpoint
     * @type {object}
     * @memberof Callback
     */
    responseBody: object | null;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof Callback
     */
    createdAt: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof Callback
     */
    updatedAt: string;
}


/**
 * @export
 */
export const CallbackTypeEnum = {
    InvoiceCreated: 'INVOICE_CREATED',
    InvoiceDepositReceived: 'INVOICE_DEPOSIT_RECEIVED',
    InvoiceDepositConfirmed: 'INVOICE_DEPOSIT_CONFIRMED',
    InvoicePaid: 'INVOICE_PAID',
    InvoiceUnresolved: 'INVOICE_UNRESOLVED',
    InvoiceClaimed: 'INVOICE_CLAIMED',
    PayoutCreated: 'PAYOUT_CREATED',
    PayoutSent: 'PAYOUT_SENT',
    PayoutExecuted: 'PAYOUT_EXECUTED',
    PayoutConfirmed: 'PAYOUT_CONFIRMED',
    PayoutFailed: 'PAYOUT_FAILED',
    PayoutCancelled: 'PAYOUT_CANCELLED'
} as const;
export type CallbackTypeEnum = typeof CallbackTypeEnum[keyof typeof CallbackTypeEnum];

/**
 * @export
 */
export const CallbackStatusEnum = {
    Created: 'CREATED',
    Retry: 'RETRY',
    Sent: 'SENT',
    Failed: 'FAILED'
} as const;
export type CallbackStatusEnum = typeof CallbackStatusEnum[keyof typeof CallbackStatusEnum];

/**
 * @export
 */
export const CallbackOperationTypeEnum = {
    Invoice: 'invoice',
    Payout: 'payout'
} as const;
export type CallbackOperationTypeEnum = typeof CallbackOperationTypeEnum[keyof typeof CallbackOperationTypeEnum];


/**
 * Check if a given object implements the Callback interface.
 */
export function instanceOfCallback(value: object): value is Callback {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('operationId' in value) || value['operationId'] === undefined) return false;
    if (!('operationType' in value) || value['operationType'] === undefined) return false;
    if (!('attempt' in value) || value['attempt'] === undefined) return false;
    if (!('timeSent' in value) || value['timeSent'] === undefined) return false;
    if (!('responseCode' in value) || value['responseCode'] === undefined) return false;
    if (!('responseBody' in value) || value['responseBody'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CallbackFromJSON(json: any): Callback {
    return CallbackFromJSONTyped(json, false);
}

export function CallbackFromJSONTyped(json: any, ignoreDiscriminator: boolean): Callback {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'type': json['type'],
        'status': json['status'],
        'operationId': json['operationId'],
        'operationType': json['operationType'],
        'attempt': json['attempt'],
        'timeSent': (json['timeSent'] == null ? null : new Date(json['timeSent'])),
        'responseCode': json['responseCode'],
        'responseBody': json['responseBody'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function CallbackToJSON(json: any): Callback {
    return CallbackToJSONTyped(json, false);
}

export function CallbackToJSONTyped(value?: Callback | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
        'type': value['type'],
        'status': value['status'],
        'operationId': value['operationId'],
        'operationType': value['operationType'],
        'attempt': value['attempt'],
        'timeSent': value['timeSent'] == null ? value['timeSent'] : value['timeSent'].toISOString(),
        'responseCode': value['responseCode'],
        'responseBody': value['responseBody'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

