/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClaimToRefundPayload
 */
export interface ClaimToRefundPayload {
    /**
     * Credit top-up being refunded by this CLAIM_TO
     * @type {string}
     * @memberof ClaimToRefundPayload
     */
    topUpId: string;
    /**
     * Invoice whose address the CLAIM_TO drains
     * @type {string}
     * @memberof ClaimToRefundPayload
     */
    invoiceId: string;
}

/**
 * Check if a given object implements the ClaimToRefundPayload interface.
 */
export function instanceOfClaimToRefundPayload(value: object): value is ClaimToRefundPayload {
    if (!('topUpId' in value) || value['topUpId'] === undefined) return false;
    if (!('invoiceId' in value) || value['invoiceId'] === undefined) return false;
    return true;
}

export function ClaimToRefundPayloadFromJSON(json: any): ClaimToRefundPayload {
    return ClaimToRefundPayloadFromJSONTyped(json, false);
}

export function ClaimToRefundPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimToRefundPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'topUpId': json['topUpId'],
        'invoiceId': json['invoiceId'],
    };
}

export function ClaimToRefundPayloadToJSON(json: any): ClaimToRefundPayload {
    return ClaimToRefundPayloadToJSONTyped(json, false);
}

export function ClaimToRefundPayloadToJSONTyped(value?: ClaimToRefundPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'topUpId': value['topUpId'],
        'invoiceId': value['invoiceId'],
    };
}

