/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateApiKeyDto
 */
export interface CreateApiKeyDto {
    /**
     * 
     * @type {string}
     * @memberof CreateApiKeyDto
     */
    name?: string | null;
}

/**
 * Check if a given object implements the CreateApiKeyDto interface.
 */
export function instanceOfCreateApiKeyDto(value: object): value is CreateApiKeyDto {
    return true;
}

export function CreateApiKeyDtoFromJSON(json: any): CreateApiKeyDto {
    return CreateApiKeyDtoFromJSONTyped(json, false);
}

export function CreateApiKeyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApiKeyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CreateApiKeyDtoToJSON(json: any): CreateApiKeyDto {
    return CreateApiKeyDtoToJSONTyped(json, false);
}

export function CreateApiKeyDtoToJSONTyped(value?: CreateApiKeyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

