/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMultisigConfigChangeOperationDtoCallsInner
 */
export interface CreateMultisigConfigChangeOperationDtoCallsInner {
    /**
     * Ethereum address in lowercase format
     * @type {string}
     * @memberof CreateMultisigConfigChangeOperationDtoCallsInner
     */
    to: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMultisigConfigChangeOperationDtoCallsInner
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMultisigConfigChangeOperationDtoCallsInner
     */
    data: string;
}

/**
 * Check if a given object implements the CreateMultisigConfigChangeOperationDtoCallsInner interface.
 */
export function instanceOfCreateMultisigConfigChangeOperationDtoCallsInner(value: object): value is CreateMultisigConfigChangeOperationDtoCallsInner {
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreateMultisigConfigChangeOperationDtoCallsInnerFromJSON(json: any): CreateMultisigConfigChangeOperationDtoCallsInner {
    return CreateMultisigConfigChangeOperationDtoCallsInnerFromJSONTyped(json, false);
}

export function CreateMultisigConfigChangeOperationDtoCallsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMultisigConfigChangeOperationDtoCallsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'],
        'value': json['value'],
        'data': json['data'],
    };
}

export function CreateMultisigConfigChangeOperationDtoCallsInnerToJSON(json: any): CreateMultisigConfigChangeOperationDtoCallsInner {
    return CreateMultisigConfigChangeOperationDtoCallsInnerToJSONTyped(json, false);
}

export function CreateMultisigConfigChangeOperationDtoCallsInnerToJSONTyped(value?: CreateMultisigConfigChangeOperationDtoCallsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'value': value['value'],
        'data': value['data'],
    };
}

