/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateMultisigConfigChangeOperationDtoCallsInner } from './create-multisig-config-change-operation-dto-calls-inner';
import {
    CreateMultisigConfigChangeOperationDtoCallsInnerFromJSON,
    CreateMultisigConfigChangeOperationDtoCallsInnerFromJSONTyped,
    CreateMultisigConfigChangeOperationDtoCallsInnerToJSON,
    CreateMultisigConfigChangeOperationDtoCallsInnerToJSONTyped,
} from './create-multisig-config-change-operation-dto-calls-inner';
import type { UniversalAddress } from './universal-address';
import {
    UniversalAddressFromJSON,
    UniversalAddressFromJSONTyped,
    UniversalAddressToJSON,
    UniversalAddressToJSONTyped,
} from './universal-address';

/**
 * 
 * @export
 * @interface CreateMultisigConfigChangeOperationDto
 */
export interface CreateMultisigConfigChangeOperationDto {
    /**
     * 
     * @type {Array<UniversalAddress>}
     * @memberof CreateMultisigConfigChangeOperationDto
     */
    approvers: Array<UniversalAddress>;
    /**
     * 
     * @type {number}
     * @memberof CreateMultisigConfigChangeOperationDto
     */
    threshold: number;
    /**
     * 
     * @type {Array<CreateMultisigConfigChangeOperationDtoCallsInner>}
     * @memberof CreateMultisigConfigChangeOperationDto
     */
    calls: Array<CreateMultisigConfigChangeOperationDtoCallsInner>;
}

/**
 * Check if a given object implements the CreateMultisigConfigChangeOperationDto interface.
 */
export function instanceOfCreateMultisigConfigChangeOperationDto(value: object): value is CreateMultisigConfigChangeOperationDto {
    if (!('approvers' in value) || value['approvers'] === undefined) return false;
    if (!('threshold' in value) || value['threshold'] === undefined) return false;
    if (!('calls' in value) || value['calls'] === undefined) return false;
    return true;
}

export function CreateMultisigConfigChangeOperationDtoFromJSON(json: any): CreateMultisigConfigChangeOperationDto {
    return CreateMultisigConfigChangeOperationDtoFromJSONTyped(json, false);
}

export function CreateMultisigConfigChangeOperationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMultisigConfigChangeOperationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'approvers': ((json['approvers'] as Array<any>).map(UniversalAddressFromJSON)),
        'threshold': json['threshold'],
        'calls': ((json['calls'] as Array<any>).map(CreateMultisigConfigChangeOperationDtoCallsInnerFromJSON)),
    };
}

export function CreateMultisigConfigChangeOperationDtoToJSON(json: any): CreateMultisigConfigChangeOperationDto {
    return CreateMultisigConfigChangeOperationDtoToJSONTyped(json, false);
}

export function CreateMultisigConfigChangeOperationDtoToJSONTyped(value?: CreateMultisigConfigChangeOperationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'approvers': ((value['approvers'] as Array<any>).map(UniversalAddressToJSON)),
        'threshold': value['threshold'],
        'calls': ((value['calls'] as Array<any>).map(CreateMultisigConfigChangeOperationDtoCallsInnerToJSON)),
    };
}

