/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCowswapOperationDto
 */
export interface CreateCowswapOperationDto {
    /**
     * CoW Protocol order uid to pre-sign (`0x` + 56 bytes)
     * @type {string}
     * @memberof CreateCowswapOperationDto
     */
    orderUid: string;
    /**
     * Order expiry (`validTo`) as a unix timestamp in seconds
     * @type {number}
     * @memberof CreateCowswapOperationDto
     */
    expiry: number;
    /**
     * Nonce (transaction ordering) as a non-negative integer string
     * @type {string}
     * @memberof CreateCowswapOperationDto
     */
    nonce?: string;
}

/**
 * Check if a given object implements the CreateCowswapOperationDto interface.
 */
export function instanceOfCreateCowswapOperationDto(value: object): value is CreateCowswapOperationDto {
    if (!('orderUid' in value) || value['orderUid'] === undefined) return false;
    if (!('expiry' in value) || value['expiry'] === undefined) return false;
    return true;
}

export function CreateCowswapOperationDtoFromJSON(json: any): CreateCowswapOperationDto {
    return CreateCowswapOperationDtoFromJSONTyped(json, false);
}

export function CreateCowswapOperationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCowswapOperationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'orderUid': json['orderUid'],
        'expiry': json['expiry'],
        'nonce': json['nonce'] == null ? undefined : json['nonce'],
    };
}

export function CreateCowswapOperationDtoToJSON(json: any): CreateCowswapOperationDto {
    return CreateCowswapOperationDtoToJSONTyped(json, false);
}

export function CreateCowswapOperationDtoToJSONTyped(value?: CreateCowswapOperationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderUid': value['orderUid'],
        'expiry': value['expiry'],
        'nonce': value['nonce'],
    };
}

