/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreditsOverviewResponseDtoUnitPricesInner } from './credits-overview-response-dto-unit-prices-inner';
import {
    CreditsOverviewResponseDtoUnitPricesInnerFromJSON,
    CreditsOverviewResponseDtoUnitPricesInnerFromJSONTyped,
    CreditsOverviewResponseDtoUnitPricesInnerToJSON,
    CreditsOverviewResponseDtoUnitPricesInnerToJSONTyped,
} from './credits-overview-response-dto-unit-prices-inner';

/**
 * 
 * @export
 * @interface CreditsOverviewResponseDto
 */
export interface CreditsOverviewResponseDto {
    /**
     * 
     * @type {number}
     * @memberof CreditsOverviewResponseDto
     */
    balance: number;
    /**
     * 
     * @type {number}
     * @memberof CreditsOverviewResponseDto
     */
    creditUsage: number;
    /**
     * 
     * @type {number}
     * @memberof CreditsOverviewResponseDto
     */
    creditTopUp: number;
    /**
     * 
     * @type {Array<CreditsOverviewResponseDtoUnitPricesInner>}
     * @memberof CreditsOverviewResponseDto
     */
    unitPrices: Array<CreditsOverviewResponseDtoUnitPricesInner>;
}

/**
 * Check if a given object implements the CreditsOverviewResponseDto interface.
 */
export function instanceOfCreditsOverviewResponseDto(value: object): value is CreditsOverviewResponseDto {
    if (!('balance' in value) || value['balance'] === undefined) return false;
    if (!('creditUsage' in value) || value['creditUsage'] === undefined) return false;
    if (!('creditTopUp' in value) || value['creditTopUp'] === undefined) return false;
    if (!('unitPrices' in value) || value['unitPrices'] === undefined) return false;
    return true;
}

export function CreditsOverviewResponseDtoFromJSON(json: any): CreditsOverviewResponseDto {
    return CreditsOverviewResponseDtoFromJSONTyped(json, false);
}

export function CreditsOverviewResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditsOverviewResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'balance': json['balance'],
        'creditUsage': json['creditUsage'],
        'creditTopUp': json['creditTopUp'],
        'unitPrices': ((json['unitPrices'] as Array<any>).map(CreditsOverviewResponseDtoUnitPricesInnerFromJSON)),
    };
}

export function CreditsOverviewResponseDtoToJSON(json: any): CreditsOverviewResponseDto {
    return CreditsOverviewResponseDtoToJSONTyped(json, false);
}

export function CreditsOverviewResponseDtoToJSONTyped(value?: CreditsOverviewResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'balance': value['balance'],
        'creditUsage': value['creditUsage'],
        'creditTopUp': value['creditTopUp'],
        'unitPrices': ((value['unitPrices'] as Array<any>).map(CreditsOverviewResponseDtoUnitPricesInnerToJSON)),
    };
}

