/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreditsOverviewResponseDtoUnitPricesInnerDiscountsInner } from './credits-overview-response-dto-unit-prices-inner-discounts-inner';
import {
    CreditsOverviewResponseDtoUnitPricesInnerDiscountsInnerFromJSON,
    CreditsOverviewResponseDtoUnitPricesInnerDiscountsInnerFromJSONTyped,
    CreditsOverviewResponseDtoUnitPricesInnerDiscountsInnerToJSON,
    CreditsOverviewResponseDtoUnitPricesInnerDiscountsInnerToJSONTyped,
} from './credits-overview-response-dto-unit-prices-inner-discounts-inner';

/**
 * 
 * @export
 * @interface CreditsOverviewResponseDtoUnitPricesInner
 */
export interface CreditsOverviewResponseDtoUnitPricesInner {
    /**
     * 
     * @type {string}
     * @memberof CreditsOverviewResponseDtoUnitPricesInner
     */
    currencyId: string;
    /**
     * 
     * @type {string}
     * @memberof CreditsOverviewResponseDtoUnitPricesInner
     */
    price: string;
    /**
     * 
     * @type {Array<CreditsOverviewResponseDtoUnitPricesInnerDiscountsInner>}
     * @memberof CreditsOverviewResponseDtoUnitPricesInner
     */
    discounts: Array<CreditsOverviewResponseDtoUnitPricesInnerDiscountsInner>;
}

/**
 * Check if a given object implements the CreditsOverviewResponseDtoUnitPricesInner interface.
 */
export function instanceOfCreditsOverviewResponseDtoUnitPricesInner(value: object): value is CreditsOverviewResponseDtoUnitPricesInner {
    if (!('currencyId' in value) || value['currencyId'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('discounts' in value) || value['discounts'] === undefined) return false;
    return true;
}

export function CreditsOverviewResponseDtoUnitPricesInnerFromJSON(json: any): CreditsOverviewResponseDtoUnitPricesInner {
    return CreditsOverviewResponseDtoUnitPricesInnerFromJSONTyped(json, false);
}

export function CreditsOverviewResponseDtoUnitPricesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditsOverviewResponseDtoUnitPricesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'currencyId': json['currencyId'],
        'price': json['price'],
        'discounts': ((json['discounts'] as Array<any>).map(CreditsOverviewResponseDtoUnitPricesInnerDiscountsInnerFromJSON)),
    };
}

export function CreditsOverviewResponseDtoUnitPricesInnerToJSON(json: any): CreditsOverviewResponseDtoUnitPricesInner {
    return CreditsOverviewResponseDtoUnitPricesInnerToJSONTyped(json, false);
}

export function CreditsOverviewResponseDtoUnitPricesInnerToJSONTyped(value?: CreditsOverviewResponseDtoUnitPricesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currencyId': value['currencyId'],
        'price': value['price'],
        'discounts': ((value['discounts'] as Array<any>).map(CreditsOverviewResponseDtoUnitPricesInnerDiscountsInnerToJSON)),
    };
}

