/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CrossChainUserStepDtoTransaction
 */
export interface CrossChainUserStepDtoTransaction {
    /**
     * 
     * @type {string}
     * @memberof CrossChainUserStepDtoTransaction
     */
    to: string;
    /**
     * 
     * @type {string}
     * @memberof CrossChainUserStepDtoTransaction
     */
    data: string;
    /**
     * 
     * @type {string}
     * @memberof CrossChainUserStepDtoTransaction
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof CrossChainUserStepDtoTransaction
     */
    gasLimit?: string;
}

/**
 * Check if a given object implements the CrossChainUserStepDtoTransaction interface.
 */
export function instanceOfCrossChainUserStepDtoTransaction(value: object): value is CrossChainUserStepDtoTransaction {
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function CrossChainUserStepDtoTransactionFromJSON(json: any): CrossChainUserStepDtoTransaction {
    return CrossChainUserStepDtoTransactionFromJSONTyped(json, false);
}

export function CrossChainUserStepDtoTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrossChainUserStepDtoTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'],
        'data': json['data'],
        'value': json['value'],
        'gasLimit': json['gasLimit'] == null ? undefined : json['gasLimit'],
    };
}

export function CrossChainUserStepDtoTransactionToJSON(json: any): CrossChainUserStepDtoTransaction {
    return CrossChainUserStepDtoTransactionToJSONTyped(json, false);
}

export function CrossChainUserStepDtoTransactionToJSONTyped(value?: CrossChainUserStepDtoTransaction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'data': value['data'],
        'value': value['value'],
        'gasLimit': value['gasLimit'],
    };
}

