/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UniversalAddress } from './universal-address';
import {
    UniversalAddressFromJSON,
    UniversalAddressFromJSONTyped,
    UniversalAddressToJSON,
    UniversalAddressToJSONTyped,
} from './universal-address';
import type { CurrencyResponseDto } from './currency-response-dto';
import {
    CurrencyResponseDtoFromJSON,
    CurrencyResponseDtoFromJSONTyped,
    CurrencyResponseDtoToJSON,
    CurrencyResponseDtoToJSONTyped,
} from './currency-response-dto';

/**
 * 
 * @export
 * @interface CrossChainTransferResponseDto
 */
export interface CrossChainTransferResponseDto {
    /**
     * Entity unique identifier
     * @type {string}
     * @memberof CrossChainTransferResponseDto
     */
    id: string;
    /**
     * Operation status
     * @type {string}
     * @memberof CrossChainTransferResponseDto
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof CrossChainTransferResponseDto
     */
    createdAt: string;
    /**
     * 
     * @type {UniversalAddress}
     * @memberof CrossChainTransferResponseDto
     */
    createdBy: UniversalAddress;
    /**
     * 
     * @type {string}
     * @memberof CrossChainTransferResponseDto
     */
    quoteId: string;
    /**
     * 
     * @type {string}
     * @memberof CrossChainTransferResponseDto
     */
    routeType: string;
    /**
     * 
     * @type {CurrencyResponseDto}
     * @memberof CrossChainTransferResponseDto
     */
    srcCurrency: CurrencyResponseDto;
    /**
     * Source amount in raw smallest units (wei / sun). Deprecated: use `srcAmountFormatted`.
     * @type {string}
     * @memberof CrossChainTransferResponseDto
     * @deprecated
     */
    srcAmount: string;
    /**
     * Source amount converted to `srcCurrency.decimals`; null when the raw value cannot be parsed
     * @type {string}
     * @memberof CrossChainTransferResponseDto
     */
    srcAmountFormatted: string | null;
    /**
     * 
     * @type {CurrencyResponseDto}
     * @memberof CrossChainTransferResponseDto
     */
    dstCurrency: CurrencyResponseDto;
    /**
     * Destination amount in raw smallest units. Deprecated: use `dstAmountFormatted`.
     * @type {string}
     * @memberof CrossChainTransferResponseDto
     * @deprecated
     */
    dstAmount: string;
    /**
     * Destination amount converted to `dstCurrency.decimals`; null when the raw value cannot be parsed
     * @type {string}
     * @memberof CrossChainTransferResponseDto
     */
    dstAmountFormatted: string | null;
    /**
     * 
     * @type {UniversalAddress}
     * @memberof CrossChainTransferResponseDto
     */
    dstWalletAddress: UniversalAddress;
    /**
     * 
     * @type {string}
     * @memberof CrossChainTransferResponseDto
     */
    feeUsd: string | null;
    /**
     * 
     * @type {string}
     * @memberof CrossChainTransferResponseDto
     */
    feePercent: string | null;
    /**
     * 
     * @type {number}
     * @memberof CrossChainTransferResponseDto
     */
    estimatedDurationMs: number | null;
    /**
     * Entity unique identifier
     * @type {string}
     * @memberof CrossChainTransferResponseDto
     */
    queueOperationId: string;
    /**
     * 
     * @type {string}
     * @memberof CrossChainTransferResponseDto
     */
    nonce: string;
}

/**
 * Check if a given object implements the CrossChainTransferResponseDto interface.
 */
export function instanceOfCrossChainTransferResponseDto(value: object): value is CrossChainTransferResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('quoteId' in value) || value['quoteId'] === undefined) return false;
    if (!('routeType' in value) || value['routeType'] === undefined) return false;
    if (!('srcCurrency' in value) || value['srcCurrency'] === undefined) return false;
    if (!('srcAmount' in value) || value['srcAmount'] === undefined) return false;
    if (!('srcAmountFormatted' in value) || value['srcAmountFormatted'] === undefined) return false;
    if (!('dstCurrency' in value) || value['dstCurrency'] === undefined) return false;
    if (!('dstAmount' in value) || value['dstAmount'] === undefined) return false;
    if (!('dstAmountFormatted' in value) || value['dstAmountFormatted'] === undefined) return false;
    if (!('dstWalletAddress' in value) || value['dstWalletAddress'] === undefined) return false;
    if (!('feeUsd' in value) || value['feeUsd'] === undefined) return false;
    if (!('feePercent' in value) || value['feePercent'] === undefined) return false;
    if (!('estimatedDurationMs' in value) || value['estimatedDurationMs'] === undefined) return false;
    if (!('queueOperationId' in value) || value['queueOperationId'] === undefined) return false;
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    return true;
}

export function CrossChainTransferResponseDtoFromJSON(json: any): CrossChainTransferResponseDto {
    return CrossChainTransferResponseDtoFromJSONTyped(json, false);
}

export function CrossChainTransferResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrossChainTransferResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'createdAt': json['createdAt'],
        'createdBy': UniversalAddressFromJSON(json['createdBy']),
        'quoteId': json['quoteId'],
        'routeType': json['routeType'],
        'srcCurrency': CurrencyResponseDtoFromJSON(json['srcCurrency']),
        'srcAmount': json['srcAmount'],
        'srcAmountFormatted': json['srcAmountFormatted'],
        'dstCurrency': CurrencyResponseDtoFromJSON(json['dstCurrency']),
        'dstAmount': json['dstAmount'],
        'dstAmountFormatted': json['dstAmountFormatted'],
        'dstWalletAddress': UniversalAddressFromJSON(json['dstWalletAddress']),
        'feeUsd': json['feeUsd'],
        'feePercent': json['feePercent'],
        'estimatedDurationMs': json['estimatedDurationMs'],
        'queueOperationId': json['queueOperationId'],
        'nonce': json['nonce'],
    };
}

export function CrossChainTransferResponseDtoToJSON(json: any): CrossChainTransferResponseDto {
    return CrossChainTransferResponseDtoToJSONTyped(json, false);
}

export function CrossChainTransferResponseDtoToJSONTyped(value?: CrossChainTransferResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'createdAt': value['createdAt'],
        'createdBy': UniversalAddressToJSON(value['createdBy']),
        'quoteId': value['quoteId'],
        'routeType': value['routeType'],
        'srcCurrency': CurrencyResponseDtoToJSON(value['srcCurrency']),
        'srcAmount': value['srcAmount'],
        'srcAmountFormatted': value['srcAmountFormatted'],
        'dstCurrency': CurrencyResponseDtoToJSON(value['dstCurrency']),
        'dstAmount': value['dstAmount'],
        'dstAmountFormatted': value['dstAmountFormatted'],
        'dstWalletAddress': UniversalAddressToJSON(value['dstWalletAddress']),
        'feeUsd': value['feeUsd'],
        'feePercent': value['feePercent'],
        'estimatedDurationMs': value['estimatedDurationMs'],
        'queueOperationId': value['queueOperationId'],
        'nonce': value['nonce'],
    };
}

