/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrencyResponseDto
 */
export interface CurrencyResponseDto {
    /**
     * The unique ID of the currency, ("{chainId}-{contractAddress}")
     * @type {string}
     * @memberof CurrencyResponseDto
     */
    id: string;
    /**
     * The symbol of the Currency
     * @type {string}
     * @memberof CurrencyResponseDto
     */
    symbol: string;
    /**
     * The name of the Currency
     * @type {string}
     * @memberof CurrencyResponseDto
     */
    name: string;
    /**
     * Chain ID
     * @type {string}
     * @memberof CurrencyResponseDto
     */
    chainId: string;
    /**
     * The currency address, or null for coins
     * @type {string}
     * @memberof CurrencyResponseDto
     */
    address: string | null;
    /**
     * Number of decimal places for the currency
     * @type {number}
     * @memberof CurrencyResponseDto
     */
    decimals: number;
    /**
     * Is currency scam or not
     * @type {boolean}
     * @memberof CurrencyResponseDto
     */
    isScam: boolean;
    /**
     * Whether the currency is verified
     * @type {boolean}
     * @memberof CurrencyResponseDto
     */
    isVerified: boolean;
}

/**
 * Check if a given object implements the CurrencyResponseDto interface.
 */
export function instanceOfCurrencyResponseDto(value: object): value is CurrencyResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    if (!('isScam' in value) || value['isScam'] === undefined) return false;
    if (!('isVerified' in value) || value['isVerified'] === undefined) return false;
    return true;
}

export function CurrencyResponseDtoFromJSON(json: any): CurrencyResponseDto {
    return CurrencyResponseDtoFromJSONTyped(json, false);
}

export function CurrencyResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrencyResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'symbol': json['symbol'],
        'name': json['name'],
        'chainId': json['chainId'],
        'address': json['address'],
        'decimals': json['decimals'],
        'isScam': json['isScam'],
        'isVerified': json['isVerified'],
    };
}

export function CurrencyResponseDtoToJSON(json: any): CurrencyResponseDto {
    return CurrencyResponseDtoToJSONTyped(json, false);
}

export function CurrencyResponseDtoToJSONTyped(value?: CurrencyResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'symbol': value['symbol'],
        'name': value['name'],
        'chainId': value['chainId'],
        'address': value['address'],
        'decimals': value['decimals'],
        'isScam': value['isScam'],
        'isVerified': value['isVerified'],
    };
}

