/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DappTransactionPayload
 */
export interface DappTransactionPayload {
    /**
     * Decoded operation details from frontend
     * @type {Array<any>}
     * @memberof DappTransactionPayload
     */
    decodedOperations?: Array<any>;
}

/**
 * Check if a given object implements the DappTransactionPayload interface.
 */
export function instanceOfDappTransactionPayload(value: object): value is DappTransactionPayload {
    return true;
}

export function DappTransactionPayloadFromJSON(json: any): DappTransactionPayload {
    return DappTransactionPayloadFromJSONTyped(json, false);
}

export function DappTransactionPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): DappTransactionPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'decodedOperations': json['decodedOperations'] == null ? undefined : json['decodedOperations'],
    };
}

export function DappTransactionPayloadToJSON(json: any): DappTransactionPayload {
    return DappTransactionPayloadToJSONTyped(json, false);
}

export function DappTransactionPayloadToJSONTyped(value?: DappTransactionPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'decodedOperations': value['decodedOperations'],
    };
}

