/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceDetailsDtoInvoiceBlockedAmountsInner
 */
export interface InvoiceDetailsDtoInvoiceBlockedAmountsInner {
    /**
     * Currency ID of the blocked deposit
     * @type {string}
     * @memberof InvoiceDetailsDtoInvoiceBlockedAmountsInner
     */
    currencyId: string;
    /**
     * Total blocked amount in this currency, in the currency decimals (sum of BLOCKED deposit operations)
     * @type {string}
     * @memberof InvoiceDetailsDtoInvoiceBlockedAmountsInner
     */
    amount: string;
}

/**
 * Check if a given object implements the InvoiceDetailsDtoInvoiceBlockedAmountsInner interface.
 */
export function instanceOfInvoiceDetailsDtoInvoiceBlockedAmountsInner(value: object): value is InvoiceDetailsDtoInvoiceBlockedAmountsInner {
    if (!('currencyId' in value) || value['currencyId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function InvoiceDetailsDtoInvoiceBlockedAmountsInnerFromJSON(json: any): InvoiceDetailsDtoInvoiceBlockedAmountsInner {
    return InvoiceDetailsDtoInvoiceBlockedAmountsInnerFromJSONTyped(json, false);
}

export function InvoiceDetailsDtoInvoiceBlockedAmountsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceDetailsDtoInvoiceBlockedAmountsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'currencyId': json['currencyId'],
        'amount': json['amount'],
    };
}

export function InvoiceDetailsDtoInvoiceBlockedAmountsInnerToJSON(json: any): InvoiceDetailsDtoInvoiceBlockedAmountsInner {
    return InvoiceDetailsDtoInvoiceBlockedAmountsInnerToJSONTyped(json, false);
}

export function InvoiceDetailsDtoInvoiceBlockedAmountsInnerToJSONTyped(value?: InvoiceDetailsDtoInvoiceBlockedAmountsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currencyId': value['currencyId'],
        'amount': value['amount'],
    };
}

