/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrencyResponseDto } from './currency-response-dto';
import {
    CurrencyResponseDtoFromJSON,
    CurrencyResponseDtoFromJSONTyped,
    CurrencyResponseDtoToJSON,
    CurrencyResponseDtoToJSONTyped,
} from './currency-response-dto';

/**
 * 
 * @export
 * @interface InvoiceResponseDto
 */
export interface InvoiceResponseDto {
    /**
     * Requested payment amount
     * @type {string}
     * @memberof InvoiceResponseDto
     */
    requestedAmount: string | null;
    /**
     * Available currencies for this invoice
     * @type {Array<CurrencyResponseDto>}
     * @memberof InvoiceResponseDto
     */
    availableCurrencies: Array<CurrencyResponseDto>;
    /**
     * Custom payment page button URL
     * @type {string}
     * @memberof InvoiceResponseDto
     */
    paymentPageButtonUrl: string | null;
    /**
     * Custom payment page button text
     * @type {string}
     * @memberof InvoiceResponseDto
     */
    paymentPageButtonText: string | null;
    /**
     * Payment page URL for the invoice
     * @type {string}
     * @memberof InvoiceResponseDto
     */
    paymentPageUrl: string;
    /**
     * Invoice status
     * @type {string}
     * @memberof InvoiceResponseDto
     */
    status: InvoiceResponseDtoStatusEnum;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof InvoiceResponseDto
     */
    createdAt: string;
    /**
     * Whether the entity relates to Tron (TVM)
     * @type {boolean}
     * @memberof InvoiceResponseDto
     */
    isTron: boolean;
    /**
     * Entity unique identifier
     * @type {string}
     * @memberof InvoiceResponseDto
     */
    id: string;
    /**
     * Invoice public identifier (Snowflake ID)
     * @type {string}
     * @memberof InvoiceResponseDto
     */
    publicId: string;
    /**
     * Invoice payment address
     * @type {string}
     * @memberof InvoiceResponseDto
     */
    invoiceAddress: string;
    /**
     * Paid amount in crypto; null for multi-currency invoices (see paidAmountBaseCurrency)
     * @type {string}
     * @memberof InvoiceResponseDto
     */
    paidAmount: string | null;
    /**
     * Paid amount converted to user base currency (2 decimals) for multi-currency invoices; null otherwise
     * @type {string}
     * @memberof InvoiceResponseDto
     */
    paidAmountBaseCurrency: string | null;
    /**
     * Tracking identifier
     * @type {string}
     * @memberof InvoiceResponseDto
     */
    trackingId: string | null;
    /**
     * Callback URL for notifications
     * @type {string}
     * @memberof InvoiceResponseDto
     */
    callbackUrl: string | null;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof InvoiceResponseDto
     */
    updatedAt: string;
}


/**
 * @export
 */
export const InvoiceResponseDtoStatusEnum = {
    Created: 'CREATED',
    Paid: 'PAID',
    Unresolved: 'UNRESOLVED'
} as const;
export type InvoiceResponseDtoStatusEnum = typeof InvoiceResponseDtoStatusEnum[keyof typeof InvoiceResponseDtoStatusEnum];


/**
 * Check if a given object implements the InvoiceResponseDto interface.
 */
export function instanceOfInvoiceResponseDto(value: object): value is InvoiceResponseDto {
    if (!('requestedAmount' in value) || value['requestedAmount'] === undefined) return false;
    if (!('availableCurrencies' in value) || value['availableCurrencies'] === undefined) return false;
    if (!('paymentPageButtonUrl' in value) || value['paymentPageButtonUrl'] === undefined) return false;
    if (!('paymentPageButtonText' in value) || value['paymentPageButtonText'] === undefined) return false;
    if (!('paymentPageUrl' in value) || value['paymentPageUrl'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('isTron' in value) || value['isTron'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('publicId' in value) || value['publicId'] === undefined) return false;
    if (!('invoiceAddress' in value) || value['invoiceAddress'] === undefined) return false;
    if (!('paidAmount' in value) || value['paidAmount'] === undefined) return false;
    if (!('paidAmountBaseCurrency' in value) || value['paidAmountBaseCurrency'] === undefined) return false;
    if (!('trackingId' in value) || value['trackingId'] === undefined) return false;
    if (!('callbackUrl' in value) || value['callbackUrl'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function InvoiceResponseDtoFromJSON(json: any): InvoiceResponseDto {
    return InvoiceResponseDtoFromJSONTyped(json, false);
}

export function InvoiceResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'requestedAmount': json['requestedAmount'],
        'availableCurrencies': ((json['availableCurrencies'] as Array<any>).map(CurrencyResponseDtoFromJSON)),
        'paymentPageButtonUrl': json['paymentPageButtonUrl'],
        'paymentPageButtonText': json['paymentPageButtonText'],
        'paymentPageUrl': json['paymentPageUrl'],
        'status': json['status'],
        'createdAt': json['createdAt'],
        'isTron': json['isTron'],
        'id': json['id'],
        'publicId': json['publicId'],
        'invoiceAddress': json['invoiceAddress'],
        'paidAmount': json['paidAmount'],
        'paidAmountBaseCurrency': json['paidAmountBaseCurrency'],
        'trackingId': json['trackingId'],
        'callbackUrl': json['callbackUrl'],
        'updatedAt': json['updatedAt'],
    };
}

export function InvoiceResponseDtoToJSON(json: any): InvoiceResponseDto {
    return InvoiceResponseDtoToJSONTyped(json, false);
}

export function InvoiceResponseDtoToJSONTyped(value?: InvoiceResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requestedAmount': value['requestedAmount'],
        'availableCurrencies': ((value['availableCurrencies'] as Array<any>).map(CurrencyResponseDtoToJSON)),
        'paymentPageButtonUrl': value['paymentPageButtonUrl'],
        'paymentPageButtonText': value['paymentPageButtonText'],
        'paymentPageUrl': value['paymentPageUrl'],
        'status': value['status'],
        'createdAt': value['createdAt'],
        'isTron': value['isTron'],
        'id': value['id'],
        'publicId': value['publicId'],
        'invoiceAddress': value['invoiceAddress'],
        'paidAmount': value['paidAmount'],
        'paidAmountBaseCurrency': value['paidAmountBaseCurrency'],
        'trackingId': value['trackingId'],
        'callbackUrl': value['callbackUrl'],
        'updatedAt': value['updatedAt'],
    };
}

