/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MultisigConfigChangePayload
 */
export interface MultisigConfigChangePayload {
    /**
     * New list of approver addresses
     * @type {Array<string>}
     * @memberof MultisigConfigChangePayload
     */
    approvers: Array<string>;
    /**
     * Required number of signatures
     * @type {number}
     * @memberof MultisigConfigChangePayload
     */
    threshold: number;
}

/**
 * Check if a given object implements the MultisigConfigChangePayload interface.
 */
export function instanceOfMultisigConfigChangePayload(value: object): value is MultisigConfigChangePayload {
    if (!('approvers' in value) || value['approvers'] === undefined) return false;
    if (!('threshold' in value) || value['threshold'] === undefined) return false;
    return true;
}

export function MultisigConfigChangePayloadFromJSON(json: any): MultisigConfigChangePayload {
    return MultisigConfigChangePayloadFromJSONTyped(json, false);
}

export function MultisigConfigChangePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultisigConfigChangePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'approvers': json['approvers'],
        'threshold': json['threshold'],
    };
}

export function MultisigConfigChangePayloadToJSON(json: any): MultisigConfigChangePayload {
    return MultisigConfigChangePayloadToJSONTyped(json, false);
}

export function MultisigConfigChangePayloadToJSONTyped(value?: MultisigConfigChangePayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'approvers': value['approvers'],
        'threshold': value['threshold'],
    };
}

