/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NetworkShortResponseDto
 */
export interface NetworkShortResponseDto {
    /**
     * Chain ID
     * @type {string}
     * @memberof NetworkShortResponseDto
     */
    chainId: string;
    /**
     * Human-readable network name
     * @type {string}
     * @memberof NetworkShortResponseDto
     */
    name: string;
    /**
     * Whether this is a testnet
     * @type {boolean}
     * @memberof NetworkShortResponseDto
     */
    isTestnet: boolean;
}

/**
 * Check if a given object implements the NetworkShortResponseDto interface.
 */
export function instanceOfNetworkShortResponseDto(value: object): value is NetworkShortResponseDto {
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('isTestnet' in value) || value['isTestnet'] === undefined) return false;
    return true;
}

export function NetworkShortResponseDtoFromJSON(json: any): NetworkShortResponseDto {
    return NetworkShortResponseDtoFromJSONTyped(json, false);
}

export function NetworkShortResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkShortResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'chainId': json['chainId'],
        'name': json['name'],
        'isTestnet': json['isTestnet'],
    };
}

export function NetworkShortResponseDtoToJSON(json: any): NetworkShortResponseDto {
    return NetworkShortResponseDtoToJSONTyped(json, false);
}

export function NetworkShortResponseDtoToJSONTyped(value?: NetworkShortResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chainId': value['chainId'],
        'name': value['name'],
        'isTestnet': value['isTestnet'],
    };
}

