/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PayoutPayload
 */
export interface PayoutPayload {
    /**
     * Reference to the payout entity
     * @type {string}
     * @memberof PayoutPayload
     */
    payoutId: string;
}

/**
 * Check if a given object implements the PayoutPayload interface.
 */
export function instanceOfPayoutPayload(value: object): value is PayoutPayload {
    if (!('payoutId' in value) || value['payoutId'] === undefined) return false;
    return true;
}

export function PayoutPayloadFromJSON(json: any): PayoutPayload {
    return PayoutPayloadFromJSONTyped(json, false);
}

export function PayoutPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayoutPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'payoutId': json['payoutId'],
    };
}

export function PayoutPayloadToJSON(json: any): PayoutPayload {
    return PayoutPayloadToJSONTyped(json, false);
}

export function PayoutPayloadToJSONTyped(value?: PayoutPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payoutId': value['payoutId'],
    };
}

