/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UniversalAddress } from './universal-address';
import {
    UniversalAddressFromJSON,
    UniversalAddressFromJSONTyped,
    UniversalAddressToJSON,
    UniversalAddressToJSONTyped,
} from './universal-address';
import type { CurrencyResponseDto } from './currency-response-dto';
import {
    CurrencyResponseDtoFromJSON,
    CurrencyResponseDtoFromJSONTyped,
    CurrencyResponseDtoToJSON,
    CurrencyResponseDtoToJSONTyped,
} from './currency-response-dto';

/**
 * 
 * @export
 * @interface PayoutDetailResponseDto
 */
export interface PayoutDetailResponseDto {
    /**
     * Entity unique identifier
     * @type {string}
     * @memberof PayoutDetailResponseDto
     */
    id: string;
    /**
     * The unique ID of the currency, ("{chainId}" or "{chainId}-{contractAddress}")
     * @type {string}
     * @memberof PayoutDetailResponseDto
     */
    currencyId: string;
    /**
     * Amount to be paid out
     * @type {string}
     * @memberof PayoutDetailResponseDto
     */
    amount: string;
    /**
     * 
     * @type {UniversalAddress}
     * @memberof PayoutDetailResponseDto
     */
    toAddress: UniversalAddress;
    /**
     * Whether the entity relates to Tron (TVM)
     * @type {boolean}
     * @memberof PayoutDetailResponseDto
     */
    isTron: boolean;
    /**
     * Deployment unique identifier
     * @type {string}
     * @memberof PayoutDetailResponseDto
     */
    deploymentId: string;
    /**
     * Tracking identifier
     * @type {string}
     * @memberof PayoutDetailResponseDto
     */
    trackingId: string | null;
    /**
     * Callback URL for notifications
     * @type {string}
     * @memberof PayoutDetailResponseDto
     */
    callbackUrl: string | null;
    /**
     * Queue operation ID associated with this payout
     * @type {string}
     * @memberof PayoutDetailResponseDto
     */
    queueOperationId: string | null;
    /**
     * Nonce for transaction ordering
     * @type {string}
     * @memberof PayoutDetailResponseDto
     */
    nonce: string;
    /**
     * Current status of the payout
     * @type {PayoutDetailResponseDtoStatusEnum}
     * @memberof PayoutDetailResponseDto
     */
    status: PayoutDetailResponseDtoStatusEnum;
    /**
     * 
     * @type {UniversalAddress}
     * @memberof PayoutDetailResponseDto
     */
    createdBy: UniversalAddress;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof PayoutDetailResponseDto
     */
    createdAt: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof PayoutDetailResponseDto
     */
    updatedAt: string;
    /**
     * 
     * @type {CurrencyResponseDto}
     * @memberof PayoutDetailResponseDto
     */
    currency: CurrencyResponseDto;
}


/**
 * @export
 */
export const PayoutDetailResponseDtoStatusEnum = {
    Created: 'CREATED',
    Signed: 'SIGNED',
    Sent: 'SENT',
    Executed: 'EXECUTED',
    Failed: 'FAILED',
    Canceled: 'CANCELED'
} as const;
export type PayoutDetailResponseDtoStatusEnum = typeof PayoutDetailResponseDtoStatusEnum[keyof typeof PayoutDetailResponseDtoStatusEnum];


/**
 * Check if a given object implements the PayoutDetailResponseDto interface.
 */
export function instanceOfPayoutDetailResponseDto(value: object): value is PayoutDetailResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('currencyId' in value) || value['currencyId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('toAddress' in value) || value['toAddress'] === undefined) return false;
    if (!('isTron' in value) || value['isTron'] === undefined) return false;
    if (!('deploymentId' in value) || value['deploymentId'] === undefined) return false;
    if (!('trackingId' in value) || value['trackingId'] === undefined) return false;
    if (!('callbackUrl' in value) || value['callbackUrl'] === undefined) return false;
    if (!('queueOperationId' in value) || value['queueOperationId'] === undefined) return false;
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function PayoutDetailResponseDtoFromJSON(json: any): PayoutDetailResponseDto {
    return PayoutDetailResponseDtoFromJSONTyped(json, false);
}

export function PayoutDetailResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayoutDetailResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'currencyId': json['currencyId'],
        'amount': json['amount'],
        'toAddress': UniversalAddressFromJSON(json['toAddress']),
        'isTron': json['isTron'],
        'deploymentId': json['deploymentId'],
        'trackingId': json['trackingId'],
        'callbackUrl': json['callbackUrl'],
        'queueOperationId': json['queueOperationId'],
        'nonce': json['nonce'],
        'status': json['status'],
        'createdBy': UniversalAddressFromJSON(json['createdBy']),
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'currency': CurrencyResponseDtoFromJSON(json['currency']),
    };
}

export function PayoutDetailResponseDtoToJSON(json: any): PayoutDetailResponseDto {
    return PayoutDetailResponseDtoToJSONTyped(json, false);
}

export function PayoutDetailResponseDtoToJSONTyped(value?: PayoutDetailResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'currencyId': value['currencyId'],
        'amount': value['amount'],
        'toAddress': UniversalAddressToJSON(value['toAddress']),
        'isTron': value['isTron'],
        'deploymentId': value['deploymentId'],
        'trackingId': value['trackingId'],
        'callbackUrl': value['callbackUrl'],
        'queueOperationId': value['queueOperationId'],
        'nonce': value['nonce'],
        'status': value['status'],
        'createdBy': UniversalAddressToJSON(value['createdBy']),
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'currency': CurrencyResponseDtoToJSON(value['currency']),
    };
}

