/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PayoutResponseDto } from './payout-response-dto';
import {
    PayoutResponseDtoFromJSON,
    PayoutResponseDtoFromJSONTyped,
    PayoutResponseDtoToJSON,
    PayoutResponseDtoToJSONTyped,
} from './payout-response-dto';

/**
 * 
 * @export
 * @interface PayoutListResponseDto
 */
export interface PayoutListResponseDto {
    /**
     * Total number of items across all pages
     * @type {number}
     * @memberof PayoutListResponseDto
     */
    total: number;
    /**
     * Current page number (starts from 1)
     * @type {number}
     * @memberof PayoutListResponseDto
     */
    page: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof PayoutListResponseDto
     */
    pageSize: number;
    /**
     * Array of payouts
     * @type {Array<PayoutResponseDto>}
     * @memberof PayoutListResponseDto
     */
    items: Array<PayoutResponseDto>;
}

/**
 * Check if a given object implements the PayoutListResponseDto interface.
 */
export function instanceOfPayoutListResponseDto(value: object): value is PayoutListResponseDto {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PayoutListResponseDtoFromJSON(json: any): PayoutListResponseDto {
    return PayoutListResponseDtoFromJSONTyped(json, false);
}

export function PayoutListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayoutListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'items': ((json['items'] as Array<any>).map(PayoutResponseDtoFromJSON)),
    };
}

export function PayoutListResponseDtoToJSON(json: any): PayoutListResponseDto {
    return PayoutListResponseDtoToJSONTyped(json, false);
}

export function PayoutListResponseDtoToJSONTyped(value?: PayoutListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'items': ((value['items'] as Array<any>).map(PayoutResponseDtoToJSON)),
    };
}

