/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RatePairDto } from './rate-pair-dto';
import {
    RatePairDtoFromJSON,
    RatePairDtoFromJSONTyped,
    RatePairDtoToJSON,
    RatePairDtoToJSONTyped,
} from './rate-pair-dto';

/**
 * 
 * @export
 * @interface PostRatesBodyDto
 */
export interface PostRatesBodyDto {
    /**
     * Array of rate pairs
     * @type {Array<RatePairDto>}
     * @memberof PostRatesBodyDto
     */
    rates: Array<RatePairDto>;
}

/**
 * Check if a given object implements the PostRatesBodyDto interface.
 */
export function instanceOfPostRatesBodyDto(value: object): value is PostRatesBodyDto {
    if (!('rates' in value) || value['rates'] === undefined) return false;
    return true;
}

export function PostRatesBodyDtoFromJSON(json: any): PostRatesBodyDto {
    return PostRatesBodyDtoFromJSONTyped(json, false);
}

export function PostRatesBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostRatesBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'rates': ((json['rates'] as Array<any>).map(RatePairDtoFromJSON)),
    };
}

export function PostRatesBodyDtoToJSON(json: any): PostRatesBodyDto {
    return PostRatesBodyDtoToJSONTyped(json, false);
}

export function PostRatesBodyDtoToJSONTyped(value?: PostRatesBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rates': ((value['rates'] as Array<any>).map(RatePairDtoToJSON)),
    };
}

