/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicTransactionResponseDto } from './public-transaction-response-dto';
import {
    PublicTransactionResponseDtoFromJSON,
    PublicTransactionResponseDtoFromJSONTyped,
    PublicTransactionResponseDtoToJSON,
    PublicTransactionResponseDtoToJSONTyped,
} from './public-transaction-response-dto';

/**
 * 
 * @export
 * @interface PublicTransactionListResponseDto
 */
export interface PublicTransactionListResponseDto {
    /**
     * List of transactions
     * @type {Array<PublicTransactionResponseDto>}
     * @memberof PublicTransactionListResponseDto
     */
    items: Array<PublicTransactionResponseDto>;
    /**
     * Total number of items
     * @type {number}
     * @memberof PublicTransactionListResponseDto
     */
    total: number;
    /**
     * Current page number
     * @type {number}
     * @memberof PublicTransactionListResponseDto
     */
    page: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof PublicTransactionListResponseDto
     */
    pageSize: number;
}

/**
 * Check if a given object implements the PublicTransactionListResponseDto interface.
 */
export function instanceOfPublicTransactionListResponseDto(value: object): value is PublicTransactionListResponseDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    return true;
}

export function PublicTransactionListResponseDtoFromJSON(json: any): PublicTransactionListResponseDto {
    return PublicTransactionListResponseDtoFromJSONTyped(json, false);
}

export function PublicTransactionListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicTransactionListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PublicTransactionResponseDtoFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
    };
}

export function PublicTransactionListResponseDtoToJSON(json: any): PublicTransactionListResponseDto {
    return PublicTransactionListResponseDtoToJSONTyped(json, false);
}

export function PublicTransactionListResponseDtoToJSONTyped(value?: PublicTransactionListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(PublicTransactionResponseDtoToJSON)),
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
    };
}

