/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrencyResponseDto } from './currency-response-dto';
import {
    CurrencyResponseDtoFromJSON,
    CurrencyResponseDtoFromJSONTyped,
    CurrencyResponseDtoToJSON,
    CurrencyResponseDtoToJSONTyped,
} from './currency-response-dto';

/**
 * 
 * @export
 * @interface PublicTransactionResponseDto
 */
export interface PublicTransactionResponseDto {
    /**
     * Entity unique identifier
     * @type {string}
     * @memberof PublicTransactionResponseDto
     */
    id: string;
    /**
     * Transaction direction (IN for deposits, OUT for claims/payouts)
     * @type {string}
     * @memberof PublicTransactionResponseDto
     * @deprecated
     */
    direction: PublicTransactionResponseDtoDirectionEnum;
    /**
     * Transaction status
     * @type {string}
     * @memberof PublicTransactionResponseDto
     */
    status: PublicTransactionResponseDtoStatusEnum;
    /**
     * Chain ID
     * @type {string}
     * @memberof PublicTransactionResponseDto
     */
    chainId: string;
    /**
     * Blockchain transaction hash
     * @type {string}
     * @memberof PublicTransactionResponseDto
     */
    txHash: string;
    /**
     * The unique ID of the currency, ("{chainId}-{contractAddress}")
     * @type {string}
     * @memberof PublicTransactionResponseDto
     */
    currencyId: string;
    /**
     * Amount value
     * @type {string}
     * @memberof PublicTransactionResponseDto
     */
    amount: string;
    /**
     * Receiver address
     * @type {string}
     * @memberof PublicTransactionResponseDto
     */
    toAddress: string;
    /**
     * Block number of deployment
     * @type {number}
     * @memberof PublicTransactionResponseDto
     */
    blockNumber: number | null;
    /**
     * Number of blockchain confirmations
     * @type {number}
     * @memberof PublicTransactionResponseDto
     */
    confirmations: number;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof PublicTransactionResponseDto
     */
    createdAt: string;
    /**
     * Currency details
     * @type {CurrencyResponseDto}
     * @memberof PublicTransactionResponseDto
     */
    currency: CurrencyResponseDto;
}


/**
 * @export
 */
export const PublicTransactionResponseDtoDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type PublicTransactionResponseDtoDirectionEnum = typeof PublicTransactionResponseDtoDirectionEnum[keyof typeof PublicTransactionResponseDtoDirectionEnum];

/**
 * @export
 */
export const PublicTransactionResponseDtoStatusEnum = {
    Pending: 'PENDING',
    Executed: 'EXECUTED',
    Confirmed: 'CONFIRMED',
    Failed: 'FAILED'
} as const;
export type PublicTransactionResponseDtoStatusEnum = typeof PublicTransactionResponseDtoStatusEnum[keyof typeof PublicTransactionResponseDtoStatusEnum];


/**
 * Check if a given object implements the PublicTransactionResponseDto interface.
 */
export function instanceOfPublicTransactionResponseDto(value: object): value is PublicTransactionResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    if (!('txHash' in value) || value['txHash'] === undefined) return false;
    if (!('currencyId' in value) || value['currencyId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('toAddress' in value) || value['toAddress'] === undefined) return false;
    if (!('blockNumber' in value) || value['blockNumber'] === undefined) return false;
    if (!('confirmations' in value) || value['confirmations'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function PublicTransactionResponseDtoFromJSON(json: any): PublicTransactionResponseDto {
    return PublicTransactionResponseDtoFromJSONTyped(json, false);
}

export function PublicTransactionResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicTransactionResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'direction': json['direction'],
        'status': json['status'],
        'chainId': json['chainId'],
        'txHash': json['txHash'],
        'currencyId': json['currencyId'],
        'amount': json['amount'],
        'toAddress': json['toAddress'],
        'blockNumber': json['blockNumber'],
        'confirmations': json['confirmations'],
        'createdAt': json['createdAt'],
        'currency': CurrencyResponseDtoFromJSON(json['currency']),
    };
}

export function PublicTransactionResponseDtoToJSON(json: any): PublicTransactionResponseDto {
    return PublicTransactionResponseDtoToJSONTyped(json, false);
}

export function PublicTransactionResponseDtoToJSONTyped(value?: PublicTransactionResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'direction': value['direction'],
        'status': value['status'],
        'chainId': value['chainId'],
        'txHash': value['txHash'],
        'currencyId': value['currencyId'],
        'amount': value['amount'],
        'toAddress': value['toAddress'],
        'blockNumber': value['blockNumber'],
        'confirmations': value['confirmations'],
        'createdAt': value['createdAt'],
        'currency': CurrencyResponseDtoToJSON(value['currency']),
    };
}

