/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OperationSignatureDto } from './operation-signature-dto';
import {
    OperationSignatureDtoFromJSON,
    OperationSignatureDtoFromJSONTyped,
    OperationSignatureDtoToJSON,
    OperationSignatureDtoToJSONTyped,
} from './operation-signature-dto';
import type { CallDto } from './call-dto';
import {
    CallDtoFromJSON,
    CallDtoFromJSONTyped,
    CallDtoToJSON,
    CallDtoToJSONTyped,
} from './call-dto';

/**
 * 
 * @export
 * @interface QueueOperationResponseDto
 */
export interface QueueOperationResponseDto {
    /**
     * Queue operation unique identifier
     * @type {string}
     * @memberof QueueOperationResponseDto
     */
    id: string;
    /**
     * Operation identifier formatted as bytes32 for smart contract execution, should be used as id in smart contract operation
     * @type {string}
     * @memberof QueueOperationResponseDto
     */
    executeOperationId: string;
    /**
     * Network-specific transaction nonce
     * @type {string}
     * @memberof QueueOperationResponseDto
     */
    nonce: string;
    /**
     * Type of operation to execute
     * @type {string}
     * @memberof QueueOperationResponseDto
     */
    operationType: QueueOperationResponseDtoOperationTypeEnum;
    /**
     * Current operation status
     * @type {string}
     * @memberof QueueOperationResponseDto
     */
    status: QueueOperationResponseDtoStatusEnum;
    /**
     * Array of blockchain calls to execute atomically
     * @type {Array<CallDto>}
     * @memberof QueueOperationResponseDto
     */
    calls: Array<CallDto>;
    /**
     * Operation-specific data (team config changes, reject details, etc.)
     * @type {{ [key: string]: any; }}
     * @memberof QueueOperationResponseDto
     */
    payload: { [key: string]: any; };
    /**
     * Number of signatures collected
     * @type {number}
     * @memberof QueueOperationResponseDto
     */
    signaturesCollected: number;
    /**
     * Blockchain transaction hash
     * @type {string}
     * @memberof QueueOperationResponseDto
     */
    txHash: string | null;
    /**
     * Number of signatures required
     * @type {number}
     * @memberof QueueOperationResponseDto
     */
    signaturesRequired: number;
    /**
     * Whether current user has signed
     * @type {boolean}
     * @memberof QueueOperationResponseDto
     */
    userSigned: boolean;
    /**
     * Whether current user can sign
     * @type {boolean}
     * @memberof QueueOperationResponseDto
     */
    canSign: boolean;
    /**
     * Whether operation can be executed
     * @type {boolean}
     * @memberof QueueOperationResponseDto
     */
    canExecute: boolean;
    /**
     * Whether current user can delete this operation (PENDING or READY status only)
     * @type {boolean}
     * @memberof QueueOperationResponseDto
     */
    canDelete: boolean;
    /**
     * Whether current user can create a reject operation for this nonce
     * @type {boolean}
     * @memberof QueueOperationResponseDto
     */
    canReject: boolean;
    /**
     * Whether operation is blocked by earlier nonce
     * @type {boolean}
     * @memberof QueueOperationResponseDto
     */
    isBlocked: boolean;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof QueueOperationResponseDto
     */
    createdAt: string;
    /**
     * Wallet address (Ethereum 0x... or Tron TVM T...)
     * @type {string}
     * @memberof QueueOperationResponseDto
     */
    createdBy: string;
    /**
     * Array of signatures for this operation
     * @type {Array<OperationSignatureDto>}
     * @memberof QueueOperationResponseDto
     */
    signatures: Array<OperationSignatureDto>;
}


/**
 * @export
 */
export const QueueOperationResponseDtoOperationTypeEnum = {
    MultisigConfigChange: 'MULTISIG_CONFIG_CHANGE',
    Reject: 'REJECT',
    Payout: 'PAYOUT'
} as const;
export type QueueOperationResponseDtoOperationTypeEnum = typeof QueueOperationResponseDtoOperationTypeEnum[keyof typeof QueueOperationResponseDtoOperationTypeEnum];

/**
 * @export
 */
export const QueueOperationResponseDtoStatusEnum = {
    Pending: 'PENDING',
    Ready: 'READY',
    Executing: 'EXECUTING',
    Executed: 'EXECUTED',
    Failed: 'FAILED',
    Cancelled: 'CANCELLED'
} as const;
export type QueueOperationResponseDtoStatusEnum = typeof QueueOperationResponseDtoStatusEnum[keyof typeof QueueOperationResponseDtoStatusEnum];


/**
 * Check if a given object implements the QueueOperationResponseDto interface.
 */
export function instanceOfQueueOperationResponseDto(value: object): value is QueueOperationResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('executeOperationId' in value) || value['executeOperationId'] === undefined) return false;
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    if (!('operationType' in value) || value['operationType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('calls' in value) || value['calls'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('signaturesCollected' in value) || value['signaturesCollected'] === undefined) return false;
    if (!('txHash' in value) || value['txHash'] === undefined) return false;
    if (!('signaturesRequired' in value) || value['signaturesRequired'] === undefined) return false;
    if (!('userSigned' in value) || value['userSigned'] === undefined) return false;
    if (!('canSign' in value) || value['canSign'] === undefined) return false;
    if (!('canExecute' in value) || value['canExecute'] === undefined) return false;
    if (!('canDelete' in value) || value['canDelete'] === undefined) return false;
    if (!('canReject' in value) || value['canReject'] === undefined) return false;
    if (!('isBlocked' in value) || value['isBlocked'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('signatures' in value) || value['signatures'] === undefined) return false;
    return true;
}

export function QueueOperationResponseDtoFromJSON(json: any): QueueOperationResponseDto {
    return QueueOperationResponseDtoFromJSONTyped(json, false);
}

export function QueueOperationResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueOperationResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'executeOperationId': json['executeOperationId'],
        'nonce': json['nonce'],
        'operationType': json['operationType'],
        'status': json['status'],
        'calls': ((json['calls'] as Array<any>).map(CallDtoFromJSON)),
        'payload': json['payload'],
        'signaturesCollected': json['signaturesCollected'],
        'txHash': json['txHash'],
        'signaturesRequired': json['signaturesRequired'],
        'userSigned': json['userSigned'],
        'canSign': json['canSign'],
        'canExecute': json['canExecute'],
        'canDelete': json['canDelete'],
        'canReject': json['canReject'],
        'isBlocked': json['isBlocked'],
        'createdAt': json['createdAt'],
        'createdBy': json['createdBy'],
        'signatures': ((json['signatures'] as Array<any>).map(OperationSignatureDtoFromJSON)),
    };
}

export function QueueOperationResponseDtoToJSON(json: any): QueueOperationResponseDto {
    return QueueOperationResponseDtoToJSONTyped(json, false);
}

export function QueueOperationResponseDtoToJSONTyped(value?: QueueOperationResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'executeOperationId': value['executeOperationId'],
        'nonce': value['nonce'],
        'operationType': value['operationType'],
        'status': value['status'],
        'calls': ((value['calls'] as Array<any>).map(CallDtoToJSON)),
        'payload': value['payload'],
        'signaturesCollected': value['signaturesCollected'],
        'txHash': value['txHash'],
        'signaturesRequired': value['signaturesRequired'],
        'userSigned': value['userSigned'],
        'canSign': value['canSign'],
        'canExecute': value['canExecute'],
        'canDelete': value['canDelete'],
        'canReject': value['canReject'],
        'isBlocked': value['isBlocked'],
        'createdAt': value['createdAt'],
        'createdBy': value['createdBy'],
        'signatures': ((value['signatures'] as Array<any>).map(OperationSignatureDtoToJSON)),
    };
}

