/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RateResultDto } from './rate-result-dto';
import {
    RateResultDtoFromJSON,
    RateResultDtoFromJSONTyped,
    RateResultDtoToJSON,
    RateResultDtoToJSONTyped,
} from './rate-result-dto';

/**
 * 
 * @export
 * @interface RatesResponseDto
 */
export interface RatesResponseDto {
    /**
     * 
     * @type {Array<RateResultDto>}
     * @memberof RatesResponseDto
     */
    results: Array<RateResultDto>;
}

/**
 * Check if a given object implements the RatesResponseDto interface.
 */
export function instanceOfRatesResponseDto(value: object): value is RatesResponseDto {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function RatesResponseDtoFromJSON(json: any): RatesResponseDto {
    return RatesResponseDtoFromJSONTyped(json, false);
}

export function RatesResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RatesResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(RateResultDtoFromJSON)),
    };
}

export function RatesResponseDtoToJSON(json: any): RatesResponseDto {
    return RatesResponseDtoToJSONTyped(json, false);
}

export function RatesResponseDtoToJSONTyped(value?: RatesResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(RateResultDtoToJSON)),
    };
}

