/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResendCallbacksResponseDto
 */
export interface ResendCallbacksResponseDto {
    /**
     * Number of callbacks re-queued for delivery
     * @type {number}
     * @memberof ResendCallbacksResponseDto
     */
    requeuedCount: number;
}

/**
 * Check if a given object implements the ResendCallbacksResponseDto interface.
 */
export function instanceOfResendCallbacksResponseDto(value: object): value is ResendCallbacksResponseDto {
    if (!('requeuedCount' in value) || value['requeuedCount'] === undefined) return false;
    return true;
}

export function ResendCallbacksResponseDtoFromJSON(json: any): ResendCallbacksResponseDto {
    return ResendCallbacksResponseDtoFromJSONTyped(json, false);
}

export function ResendCallbacksResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResendCallbacksResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'requeuedCount': json['requeuedCount'],
    };
}

export function ResendCallbacksResponseDtoToJSON(json: any): ResendCallbacksResponseDto {
    return ResendCallbacksResponseDtoToJSONTyped(json, false);
}

export function ResendCallbacksResponseDtoToJSONTyped(value?: ResendCallbacksResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requeuedCount': value['requeuedCount'],
    };
}

