/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StakingDelegationsResponseItemsInner } from './staking-delegations-response-items-inner';
import {
    StakingDelegationsResponseItemsInnerFromJSON,
    StakingDelegationsResponseItemsInnerFromJSONTyped,
    StakingDelegationsResponseItemsInnerToJSON,
    StakingDelegationsResponseItemsInnerToJSONTyped,
} from './staking-delegations-response-items-inner';

/**
 * 
 * @export
 * @interface StakingDelegationsResponse
 */
export interface StakingDelegationsResponse {
    /**
     * Total number of items across all pages
     * @type {number}
     * @memberof StakingDelegationsResponse
     */
    total: number;
    /**
     * Current page number (starts from 1)
     * @type {number}
     * @memberof StakingDelegationsResponse
     */
    page: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof StakingDelegationsResponse
     */
    pageSize: number;
    /**
     * 
     * @type {Array<StakingDelegationsResponseItemsInner>}
     * @memberof StakingDelegationsResponse
     */
    items: Array<StakingDelegationsResponseItemsInner>;
}

/**
 * Check if a given object implements the StakingDelegationsResponse interface.
 */
export function instanceOfStakingDelegationsResponse(value: object): value is StakingDelegationsResponse {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function StakingDelegationsResponseFromJSON(json: any): StakingDelegationsResponse {
    return StakingDelegationsResponseFromJSONTyped(json, false);
}

export function StakingDelegationsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StakingDelegationsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'items': ((json['items'] as Array<any>).map(StakingDelegationsResponseItemsInnerFromJSON)),
    };
}

export function StakingDelegationsResponseToJSON(json: any): StakingDelegationsResponse {
    return StakingDelegationsResponseToJSONTyped(json, false);
}

export function StakingDelegationsResponseToJSONTyped(value?: StakingDelegationsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'items': ((value['items'] as Array<any>).map(StakingDelegationsResponseItemsInnerToJSON)),
    };
}

