/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StakingSummaryResponsePendingUnstakesInner } from './staking-summary-response-pending-unstakes-inner';
import {
    StakingSummaryResponsePendingUnstakesInnerFromJSON,
    StakingSummaryResponsePendingUnstakesInnerFromJSONTyped,
    StakingSummaryResponsePendingUnstakesInnerToJSON,
    StakingSummaryResponsePendingUnstakesInnerToJSONTyped,
} from './staking-summary-response-pending-unstakes-inner';

/**
 * 
 * @export
 * @interface StakingSummaryResponse
 */
export interface StakingSummaryResponse {
    /**
     * Total staked TRX
     * @type {string}
     * @memberof StakingSummaryResponse
     */
    totalStakedTrx: string;
    /**
     * Available Energy units
     * @type {string}
     * @memberof StakingSummaryResponse
     */
    energy: string;
    /**
     * Available Bandwidth units
     * @type {string}
     * @memberof StakingSummaryResponse
     */
    bandwidth: string;
    /**
     * Spendable TRX balance
     * @type {string}
     * @memberof StakingSummaryResponse
     */
    availableTrx: string;
    /**
     * Pending unstake entries from on-chain state
     * @type {Array<StakingSummaryResponsePendingUnstakesInner>}
     * @memberof StakingSummaryResponse
     */
    pendingUnstakes: Array<StakingSummaryResponsePendingUnstakesInner>;
}

/**
 * Check if a given object implements the StakingSummaryResponse interface.
 */
export function instanceOfStakingSummaryResponse(value: object): value is StakingSummaryResponse {
    if (!('totalStakedTrx' in value) || value['totalStakedTrx'] === undefined) return false;
    if (!('energy' in value) || value['energy'] === undefined) return false;
    if (!('bandwidth' in value) || value['bandwidth'] === undefined) return false;
    if (!('availableTrx' in value) || value['availableTrx'] === undefined) return false;
    if (!('pendingUnstakes' in value) || value['pendingUnstakes'] === undefined) return false;
    return true;
}

export function StakingSummaryResponseFromJSON(json: any): StakingSummaryResponse {
    return StakingSummaryResponseFromJSONTyped(json, false);
}

export function StakingSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StakingSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalStakedTrx': json['totalStakedTrx'],
        'energy': json['energy'],
        'bandwidth': json['bandwidth'],
        'availableTrx': json['availableTrx'],
        'pendingUnstakes': ((json['pendingUnstakes'] as Array<any>).map(StakingSummaryResponsePendingUnstakesInnerFromJSON)),
    };
}

export function StakingSummaryResponseToJSON(json: any): StakingSummaryResponse {
    return StakingSummaryResponseToJSONTyped(json, false);
}

export function StakingSummaryResponseToJSONTyped(value?: StakingSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalStakedTrx': value['totalStakedTrx'],
        'energy': value['energy'],
        'bandwidth': value['bandwidth'],
        'availableTrx': value['availableTrx'],
        'pendingUnstakes': ((value['pendingUnstakes'] as Array<any>).map(StakingSummaryResponsePendingUnstakesInnerToJSON)),
    };
}

