/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StakeResourcePayload
 */
export interface StakeResourcePayload {
    /**
     * TRX amount (decimal)
     * @type {string}
     * @memberof StakeResourcePayload
     */
    amount: string;
    /**
     * Resource type
     * @type {StakeResourcePayloadResourceTypeEnum}
     * @memberof StakeResourcePayload
     */
    resourceType: StakeResourcePayloadResourceTypeEnum;
}


/**
 * @export
 */
export const StakeResourcePayloadResourceTypeEnum = {
    Bandwidth: 'BANDWIDTH',
    Energy: 'ENERGY'
} as const;
export type StakeResourcePayloadResourceTypeEnum = typeof StakeResourcePayloadResourceTypeEnum[keyof typeof StakeResourcePayloadResourceTypeEnum];


/**
 * Check if a given object implements the StakeResourcePayload interface.
 */
export function instanceOfStakeResourcePayload(value: object): value is StakeResourcePayload {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('resourceType' in value) || value['resourceType'] === undefined) return false;
    return true;
}

export function StakeResourcePayloadFromJSON(json: any): StakeResourcePayload {
    return StakeResourcePayloadFromJSONTyped(json, false);
}

export function StakeResourcePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): StakeResourcePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'resourceType': json['resourceType'],
    };
}

export function StakeResourcePayloadToJSON(json: any): StakeResourcePayload {
    return StakeResourcePayloadToJSONTyped(json, false);
}

export function StakeResourcePayloadToJSONTyped(value?: StakeResourcePayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'resourceType': value['resourceType'],
    };
}

