/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmitSignatureDto
 */
export interface SubmitSignatureDto {
    /**
     * 
     * @type {string}
     * @memberof SubmitSignatureDto
     */
    signature: string;
}

/**
 * Check if a given object implements the SubmitSignatureDto interface.
 */
export function instanceOfSubmitSignatureDto(value: object): value is SubmitSignatureDto {
    if (!('signature' in value) || value['signature'] === undefined) return false;
    return true;
}

export function SubmitSignatureDtoFromJSON(json: any): SubmitSignatureDto {
    return SubmitSignatureDtoFromJSONTyped(json, false);
}

export function SubmitSignatureDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitSignatureDto {
    if (json == null) {
        return json;
    }
    return {
        
        'signature': json['signature'],
    };
}

export function SubmitSignatureDtoToJSON(json: any): SubmitSignatureDto {
    return SubmitSignatureDtoToJSONTyped(json, false);
}

export function SubmitSignatureDtoToJSONTyped(value?: SubmitSignatureDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signature': value['signature'],
    };
}

