/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SuperRepresentativesResponseItemsInner } from './super-representatives-response-items-inner';
import {
    SuperRepresentativesResponseItemsInnerFromJSON,
    SuperRepresentativesResponseItemsInnerFromJSONTyped,
    SuperRepresentativesResponseItemsInnerToJSON,
    SuperRepresentativesResponseItemsInnerToJSONTyped,
} from './super-representatives-response-items-inner';

/**
 * 
 * @export
 * @interface SuperRepresentativesResponse
 */
export interface SuperRepresentativesResponse {
    /**
     * The 27 active SuperRepresentatives
     * @type {Array<SuperRepresentativesResponseItemsInner>}
     * @memberof SuperRepresentativesResponse
     */
    items: Array<SuperRepresentativesResponseItemsInner>;
}

/**
 * Check if a given object implements the SuperRepresentativesResponse interface.
 */
export function instanceOfSuperRepresentativesResponse(value: object): value is SuperRepresentativesResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function SuperRepresentativesResponseFromJSON(json: any): SuperRepresentativesResponse {
    return SuperRepresentativesResponseFromJSONTyped(json, false);
}

export function SuperRepresentativesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuperRepresentativesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(SuperRepresentativesResponseItemsInnerFromJSON)),
    };
}

export function SuperRepresentativesResponseToJSON(json: any): SuperRepresentativesResponse {
    return SuperRepresentativesResponseToJSONTyped(json, false);
}

export function SuperRepresentativesResponseToJSONTyped(value?: SuperRepresentativesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(SuperRepresentativesResponseItemsInnerToJSON)),
    };
}

