/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TopUpsResponseDtoItemsInner } from './top-ups-response-dto-items-inner';
import {
    TopUpsResponseDtoItemsInnerFromJSON,
    TopUpsResponseDtoItemsInnerFromJSONTyped,
    TopUpsResponseDtoItemsInnerToJSON,
    TopUpsResponseDtoItemsInnerToJSONTyped,
} from './top-ups-response-dto-items-inner';

/**
 * 
 * @export
 * @interface TopUpsResponseDto
 */
export interface TopUpsResponseDto {
    /**
     * 
     * @type {number}
     * @memberof TopUpsResponseDto
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof TopUpsResponseDto
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof TopUpsResponseDto
     */
    pageSize: number;
    /**
     * 
     * @type {Array<TopUpsResponseDtoItemsInner>}
     * @memberof TopUpsResponseDto
     */
    items: Array<TopUpsResponseDtoItemsInner>;
}

/**
 * Check if a given object implements the TopUpsResponseDto interface.
 */
export function instanceOfTopUpsResponseDto(value: object): value is TopUpsResponseDto {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function TopUpsResponseDtoFromJSON(json: any): TopUpsResponseDto {
    return TopUpsResponseDtoFromJSONTyped(json, false);
}

export function TopUpsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopUpsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'items': ((json['items'] as Array<any>).map(TopUpsResponseDtoItemsInnerFromJSON)),
    };
}

export function TopUpsResponseDtoToJSON(json: any): TopUpsResponseDto {
    return TopUpsResponseDtoToJSONTyped(json, false);
}

export function TopUpsResponseDtoToJSONTyped(value?: TopUpsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'items': ((value['items'] as Array<any>).map(TopUpsResponseDtoItemsInnerToJSON)),
    };
}

