/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UniversalAddress } from './universal-address';
import {
    UniversalAddressFromJSON,
    UniversalAddressFromJSONTyped,
    UniversalAddressToJSON,
    UniversalAddressToJSONTyped,
} from './universal-address';

/**
 * 
 * @export
 * @interface TopUpsResponseDtoItemsInnerCurrency
 */
export interface TopUpsResponseDtoItemsInnerCurrency {
    /**
     * 
     * @type {string}
     * @memberof TopUpsResponseDtoItemsInnerCurrency
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TopUpsResponseDtoItemsInnerCurrency
     */
    symbol: string;
    /**
     * 
     * @type {string}
     * @memberof TopUpsResponseDtoItemsInnerCurrency
     */
    name: string;
    /**
     * Chain ID
     * @type {string}
     * @memberof TopUpsResponseDtoItemsInnerCurrency
     */
    chainId: string;
    /**
     * 
     * @type {UniversalAddress}
     * @memberof TopUpsResponseDtoItemsInnerCurrency
     */
    address: UniversalAddress | null;
    /**
     * 
     * @type {number}
     * @memberof TopUpsResponseDtoItemsInnerCurrency
     */
    decimals: number;
    /**
     * 
     * @type {boolean}
     * @memberof TopUpsResponseDtoItemsInnerCurrency
     */
    isScam: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TopUpsResponseDtoItemsInnerCurrency
     */
    isVerified: boolean;
}

/**
 * Check if a given object implements the TopUpsResponseDtoItemsInnerCurrency interface.
 */
export function instanceOfTopUpsResponseDtoItemsInnerCurrency(value: object): value is TopUpsResponseDtoItemsInnerCurrency {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('decimals' in value) || value['decimals'] === undefined) return false;
    if (!('isScam' in value) || value['isScam'] === undefined) return false;
    if (!('isVerified' in value) || value['isVerified'] === undefined) return false;
    return true;
}

export function TopUpsResponseDtoItemsInnerCurrencyFromJSON(json: any): TopUpsResponseDtoItemsInnerCurrency {
    return TopUpsResponseDtoItemsInnerCurrencyFromJSONTyped(json, false);
}

export function TopUpsResponseDtoItemsInnerCurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopUpsResponseDtoItemsInnerCurrency {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'symbol': json['symbol'],
        'name': json['name'],
        'chainId': json['chainId'],
        'address': UniversalAddressFromJSON(json['address']),
        'decimals': json['decimals'],
        'isScam': json['isScam'],
        'isVerified': json['isVerified'],
    };
}

export function TopUpsResponseDtoItemsInnerCurrencyToJSON(json: any): TopUpsResponseDtoItemsInnerCurrency {
    return TopUpsResponseDtoItemsInnerCurrencyToJSONTyped(json, false);
}

export function TopUpsResponseDtoItemsInnerCurrencyToJSONTyped(value?: TopUpsResponseDtoItemsInnerCurrency | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'symbol': value['symbol'],
        'name': value['name'],
        'chainId': value['chainId'],
        'address': UniversalAddressToJSON(value['address']),
        'decimals': value['decimals'],
        'isScam': value['isScam'],
        'isVerified': value['isVerified'],
    };
}

