/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TopUpsResponseDtoItemsInnerCurrency } from './top-ups-response-dto-items-inner-currency';
import {
    TopUpsResponseDtoItemsInnerCurrencyFromJSON,
    TopUpsResponseDtoItemsInnerCurrencyFromJSONTyped,
    TopUpsResponseDtoItemsInnerCurrencyToJSON,
    TopUpsResponseDtoItemsInnerCurrencyToJSONTyped,
} from './top-ups-response-dto-items-inner-currency';

/**
 * 
 * @export
 * @interface TopUpsResponseDtoItemsInner
 */
export interface TopUpsResponseDtoItemsInner {
    /**
     * 
     * @type {string}
     * @memberof TopUpsResponseDtoItemsInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TopUpsResponseDtoItemsInner
     */
    accountId: string;
    /**
     * 
     * @type {string}
     * @memberof TopUpsResponseDtoItemsInner
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof TopUpsResponseDtoItemsInner
     */
    currencyId: string;
    /**
     * 
     * @type {TopUpsResponseDtoItemsInnerCurrency}
     * @memberof TopUpsResponseDtoItemsInner
     */
    currency: TopUpsResponseDtoItemsInnerCurrency;
    /**
     * 
     * @type {number}
     * @memberof TopUpsResponseDtoItemsInner
     */
    creditsGranted: number;
    /**
     * 
     * @type {Date}
     * @memberof TopUpsResponseDtoItemsInner
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the TopUpsResponseDtoItemsInner interface.
 */
export function instanceOfTopUpsResponseDtoItemsInner(value: object): value is TopUpsResponseDtoItemsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currencyId' in value) || value['currencyId'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('creditsGranted' in value) || value['creditsGranted'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function TopUpsResponseDtoItemsInnerFromJSON(json: any): TopUpsResponseDtoItemsInner {
    return TopUpsResponseDtoItemsInnerFromJSONTyped(json, false);
}

export function TopUpsResponseDtoItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopUpsResponseDtoItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'accountId': json['accountId'],
        'amount': json['amount'],
        'currencyId': json['currencyId'],
        'currency': TopUpsResponseDtoItemsInnerCurrencyFromJSON(json['currency']),
        'creditsGranted': json['creditsGranted'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function TopUpsResponseDtoItemsInnerToJSON(json: any): TopUpsResponseDtoItemsInner {
    return TopUpsResponseDtoItemsInnerToJSONTyped(json, false);
}

export function TopUpsResponseDtoItemsInnerToJSONTyped(value?: TopUpsResponseDtoItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'accountId': value['accountId'],
        'amount': value['amount'],
        'currencyId': value['currencyId'],
        'currency': TopUpsResponseDtoItemsInnerCurrencyToJSON(value['currency']),
        'creditsGranted': value['creditsGranted'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

