/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Present only for UNSTAKE transfers
 * @export
 * @interface TransactionListResponseDtoItemsInnerUnstake
 */
export interface TransactionListResponseDtoItemsInnerUnstake {
    /**
     * Unstaked TRX
     * @type {string}
     * @memberof TransactionListResponseDtoItemsInnerUnstake
     */
    amount: string;
    /**
     * Resource type
     * @type {TransactionListResponseDtoItemsInnerUnstakeResourceTypeEnum}
     * @memberof TransactionListResponseDtoItemsInnerUnstake
     */
    resourceType: TransactionListResponseDtoItemsInnerUnstakeResourceTypeEnum;
}


/**
 * @export
 */
export const TransactionListResponseDtoItemsInnerUnstakeResourceTypeEnum = {
    Bandwidth: 'BANDWIDTH',
    Energy: 'ENERGY'
} as const;
export type TransactionListResponseDtoItemsInnerUnstakeResourceTypeEnum = typeof TransactionListResponseDtoItemsInnerUnstakeResourceTypeEnum[keyof typeof TransactionListResponseDtoItemsInnerUnstakeResourceTypeEnum];


/**
 * Check if a given object implements the TransactionListResponseDtoItemsInnerUnstake interface.
 */
export function instanceOfTransactionListResponseDtoItemsInnerUnstake(value: object): value is TransactionListResponseDtoItemsInnerUnstake {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('resourceType' in value) || value['resourceType'] === undefined) return false;
    return true;
}

export function TransactionListResponseDtoItemsInnerUnstakeFromJSON(json: any): TransactionListResponseDtoItemsInnerUnstake {
    return TransactionListResponseDtoItemsInnerUnstakeFromJSONTyped(json, false);
}

export function TransactionListResponseDtoItemsInnerUnstakeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionListResponseDtoItemsInnerUnstake {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'resourceType': json['resourceType'],
    };
}

export function TransactionListResponseDtoItemsInnerUnstakeToJSON(json: any): TransactionListResponseDtoItemsInnerUnstake {
    return TransactionListResponseDtoItemsInnerUnstakeToJSONTyped(json, false);
}

export function TransactionListResponseDtoItemsInnerUnstakeToJSONTyped(value?: TransactionListResponseDtoItemsInnerUnstake | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'resourceType': value['resourceType'],
    };
}

