/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Present only for RECLAIM transfers
 * @export
 * @interface TransactionListResponseDtoItemsInnerReclaim
 */
export interface TransactionListResponseDtoItemsInnerReclaim {
    /**
     * Reclaimed TRX
     * @type {string}
     * @memberof TransactionListResponseDtoItemsInnerReclaim
     */
    amount: string;
    /**
     * Resource type
     * @type {TransactionListResponseDtoItemsInnerReclaimResourceTypeEnum}
     * @memberof TransactionListResponseDtoItemsInnerReclaim
     */
    resourceType: TransactionListResponseDtoItemsInnerReclaimResourceTypeEnum;
    /**
     * TRON base58 source address
     * @type {string}
     * @memberof TransactionListResponseDtoItemsInnerReclaim
     */
    recipient: string;
}


/**
 * @export
 */
export const TransactionListResponseDtoItemsInnerReclaimResourceTypeEnum = {
    Bandwidth: 'BANDWIDTH',
    Energy: 'ENERGY'
} as const;
export type TransactionListResponseDtoItemsInnerReclaimResourceTypeEnum = typeof TransactionListResponseDtoItemsInnerReclaimResourceTypeEnum[keyof typeof TransactionListResponseDtoItemsInnerReclaimResourceTypeEnum];


/**
 * Check if a given object implements the TransactionListResponseDtoItemsInnerReclaim interface.
 */
export function instanceOfTransactionListResponseDtoItemsInnerReclaim(value: object): value is TransactionListResponseDtoItemsInnerReclaim {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('resourceType' in value) || value['resourceType'] === undefined) return false;
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    return true;
}

export function TransactionListResponseDtoItemsInnerReclaimFromJSON(json: any): TransactionListResponseDtoItemsInnerReclaim {
    return TransactionListResponseDtoItemsInnerReclaimFromJSONTyped(json, false);
}

export function TransactionListResponseDtoItemsInnerReclaimFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionListResponseDtoItemsInnerReclaim {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'resourceType': json['resourceType'],
        'recipient': json['recipient'],
    };
}

export function TransactionListResponseDtoItemsInnerReclaimToJSON(json: any): TransactionListResponseDtoItemsInnerReclaim {
    return TransactionListResponseDtoItemsInnerReclaimToJSONTyped(json, false);
}

export function TransactionListResponseDtoItemsInnerReclaimToJSONTyped(value?: TransactionListResponseDtoItemsInnerReclaim | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'resourceType': value['resourceType'],
        'recipient': value['recipient'],
    };
}

