/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Present only for DELEGATE transfers
 * @export
 * @interface TransactionListResponseDtoItemsInnerDelegate
 */
export interface TransactionListResponseDtoItemsInnerDelegate {
    /**
     * Delegated TRX
     * @type {string}
     * @memberof TransactionListResponseDtoItemsInnerDelegate
     */
    amount: string;
    /**
     * Resource type
     * @type {TransactionListResponseDtoItemsInnerDelegateResourceTypeEnum}
     * @memberof TransactionListResponseDtoItemsInnerDelegate
     */
    resourceType: TransactionListResponseDtoItemsInnerDelegateResourceTypeEnum;
    /**
     * TRON base58 recipient
     * @type {string}
     * @memberof TransactionListResponseDtoItemsInnerDelegate
     */
    recipient: string;
    /**
     * Whether the delegation was locked at creation
     * @type {boolean}
     * @memberof TransactionListResponseDtoItemsInnerDelegate
     */
    isLocked: boolean;
}


/**
 * @export
 */
export const TransactionListResponseDtoItemsInnerDelegateResourceTypeEnum = {
    Bandwidth: 'BANDWIDTH',
    Energy: 'ENERGY'
} as const;
export type TransactionListResponseDtoItemsInnerDelegateResourceTypeEnum = typeof TransactionListResponseDtoItemsInnerDelegateResourceTypeEnum[keyof typeof TransactionListResponseDtoItemsInnerDelegateResourceTypeEnum];


/**
 * Check if a given object implements the TransactionListResponseDtoItemsInnerDelegate interface.
 */
export function instanceOfTransactionListResponseDtoItemsInnerDelegate(value: object): value is TransactionListResponseDtoItemsInnerDelegate {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('resourceType' in value) || value['resourceType'] === undefined) return false;
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    if (!('isLocked' in value) || value['isLocked'] === undefined) return false;
    return true;
}

export function TransactionListResponseDtoItemsInnerDelegateFromJSON(json: any): TransactionListResponseDtoItemsInnerDelegate {
    return TransactionListResponseDtoItemsInnerDelegateFromJSONTyped(json, false);
}

export function TransactionListResponseDtoItemsInnerDelegateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionListResponseDtoItemsInnerDelegate {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'resourceType': json['resourceType'],
        'recipient': json['recipient'],
        'isLocked': json['isLocked'],
    };
}

export function TransactionListResponseDtoItemsInnerDelegateToJSON(json: any): TransactionListResponseDtoItemsInnerDelegate {
    return TransactionListResponseDtoItemsInnerDelegateToJSONTyped(json, false);
}

export function TransactionListResponseDtoItemsInnerDelegateToJSONTyped(value?: TransactionListResponseDtoItemsInnerDelegate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'resourceType': value['resourceType'],
        'recipient': value['recipient'],
        'isLocked': value['isLocked'],
    };
}

