/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionResponseDto } from './transaction-response-dto';
import {
    TransactionResponseDtoFromJSON,
    TransactionResponseDtoFromJSONTyped,
    TransactionResponseDtoToJSON,
    TransactionResponseDtoToJSONTyped,
} from './transaction-response-dto';

/**
 * 
 * @export
 * @interface TransactionListResponseDto
 */
export interface TransactionListResponseDto {
    /**
     * Total number of items across all pages
     * @type {number}
     * @memberof TransactionListResponseDto
     */
    total: number;
    /**
     * Current page number (starts from 1)
     * @type {number}
     * @memberof TransactionListResponseDto
     */
    page: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof TransactionListResponseDto
     */
    pageSize: number;
    /**
     * Array of transaction items
     * @type {Array<TransactionResponseDto>}
     * @memberof TransactionListResponseDto
     */
    items: Array<TransactionResponseDto>;
}

/**
 * Check if a given object implements the TransactionListResponseDto interface.
 */
export function instanceOfTransactionListResponseDto(value: object): value is TransactionListResponseDto {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function TransactionListResponseDtoFromJSON(json: any): TransactionListResponseDto {
    return TransactionListResponseDtoFromJSONTyped(json, false);
}

export function TransactionListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'items': ((json['items'] as Array<any>).map(TransactionResponseDtoFromJSON)),
    };
}

export function TransactionListResponseDtoToJSON(json: any): TransactionListResponseDto {
    return TransactionListResponseDtoToJSONTyped(json, false);
}

export function TransactionListResponseDtoToJSONTyped(value?: TransactionListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'items': ((value['items'] as Array<any>).map(TransactionResponseDtoToJSON)),
    };
}

