/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type TransactionsControllerGetTransactionsV1IsClaimedParameter
 * 
 * @export
 */
export type TransactionsControllerGetTransactionsV1IsClaimedParameter = boolean | string;

export function TransactionsControllerGetTransactionsV1IsClaimedParameterFromJSON(json: any): TransactionsControllerGetTransactionsV1IsClaimedParameter {
    return TransactionsControllerGetTransactionsV1IsClaimedParameterFromJSONTyped(json, false);
}

export function TransactionsControllerGetTransactionsV1IsClaimedParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionsControllerGetTransactionsV1IsClaimedParameter {
    if (json == null) {
        return json;
    }
    if (typeof json === 'boolean') {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function TransactionsControllerGetTransactionsV1IsClaimedParameterToJSON(json: any): any {
    return TransactionsControllerGetTransactionsV1IsClaimedParameterToJSONTyped(json, false);
}

export function TransactionsControllerGetTransactionsV1IsClaimedParameterToJSONTyped(value?: TransactionsControllerGetTransactionsV1IsClaimedParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'boolean') {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

