/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionDappMetadata
 */
export interface TransactionDappMetadata {
    /**
     * Dapp display name
     * @type {string}
     * @memberof TransactionDappMetadata
     */
    dappName?: string;
    /**
     * Dapp URL
     * @type {string}
     * @memberof TransactionDappMetadata
     */
    dappUrl?: string;
    /**
     * Dapp icon URL
     * @type {string}
     * @memberof TransactionDappMetadata
     */
    icon?: string;
}

/**
 * Check if a given object implements the TransactionDappMetadata interface.
 */
export function instanceOfTransactionDappMetadata(value: object): value is TransactionDappMetadata {
    return true;
}

export function TransactionDappMetadataFromJSON(json: any): TransactionDappMetadata {
    return TransactionDappMetadataFromJSONTyped(json, false);
}

export function TransactionDappMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionDappMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'dappName': json['dappName'] == null ? undefined : json['dappName'],
        'dappUrl': json['dappUrl'] == null ? undefined : json['dappUrl'],
        'icon': json['icon'] == null ? undefined : json['icon'],
    };
}

export function TransactionDappMetadataToJSON(json: any): TransactionDappMetadata {
    return TransactionDappMetadataToJSONTyped(json, false);
}

export function TransactionDappMetadataToJSONTyped(value?: TransactionDappMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dappName': value['dappName'],
        'dappUrl': value['dappUrl'],
        'icon': value['icon'],
    };
}

