/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UniversalAddress } from './universal-address';
import {
    UniversalAddressFromJSON,
    UniversalAddressFromJSONTyped,
    UniversalAddressToJSON,
    UniversalAddressToJSONTyped,
} from './universal-address';
import type { TransactionListResponseDtoItemsInnerInvoice } from './transaction-list-response-dto-items-inner-invoice';
import {
    TransactionListResponseDtoItemsInnerInvoiceFromJSON,
    TransactionListResponseDtoItemsInnerInvoiceFromJSONTyped,
    TransactionListResponseDtoItemsInnerInvoiceToJSON,
    TransactionListResponseDtoItemsInnerInvoiceToJSONTyped,
} from './transaction-list-response-dto-items-inner-invoice';
import type { TransactionDappMetadata } from './transaction-dapp-metadata';
import {
    TransactionDappMetadataFromJSON,
    TransactionDappMetadataFromJSONTyped,
    TransactionDappMetadataToJSON,
    TransactionDappMetadataToJSONTyped,
} from './transaction-dapp-metadata';
import type { TransactionListResponseDtoItemsInnerCallsInner } from './transaction-list-response-dto-items-inner-calls-inner';
import {
    TransactionListResponseDtoItemsInnerCallsInnerFromJSON,
    TransactionListResponseDtoItemsInnerCallsInnerFromJSONTyped,
    TransactionListResponseDtoItemsInnerCallsInnerToJSON,
    TransactionListResponseDtoItemsInnerCallsInnerToJSONTyped,
} from './transaction-list-response-dto-items-inner-calls-inner';
import type { CurrencyResponseDto } from './currency-response-dto';
import {
    CurrencyResponseDtoFromJSON,
    CurrencyResponseDtoFromJSONTyped,
    CurrencyResponseDtoToJSON,
    CurrencyResponseDtoToJSONTyped,
} from './currency-response-dto';

/**
 * 
 * @export
 * @interface TransactionListResponseDtoItemsInner
 */
export interface TransactionListResponseDtoItemsInner {
    /**
     * Entity unique identifier
     * @type {string}
     * @memberof TransactionListResponseDtoItemsInner
     */
    id: string;
    /**
     * Transaction direction (IN for deposits, OUT for claims/payouts)
     * @type {TransactionListResponseDtoItemsInnerDirectionEnum}
     * @memberof TransactionListResponseDtoItemsInner
     */
    direction: TransactionListResponseDtoItemsInnerDirectionEnum;
    /**
     * Transaction status
     * @type {TransactionListResponseDtoItemsInnerStatusEnum}
     * @memberof TransactionListResponseDtoItemsInner
     */
    status: TransactionListResponseDtoItemsInnerStatusEnum;
    /**
     * Chain ID
     * @type {string}
     * @memberof TransactionListResponseDtoItemsInner
     */
    chainId: string;
    /**
     * Blockchain transaction hash. EVM chains use the `0x`-prefixed 32-byte hex form; TVM (Tron) chains use a bare 64-hex string without the `0x` prefix.
     * @type {string}
     * @memberof TransactionListResponseDtoItemsInner
     */
    txHash: string;
    /**
     * The unique ID of the currency, ("{chainId}" or "{chainId}-{contractAddress}")
     * @type {string}
     * @memberof TransactionListResponseDtoItemsInner
     */
    currencyId: string | null;
    /**
     * Cryptocurrency amount with sign for display
     * @type {string}
     * @memberof TransactionListResponseDtoItemsInner
     */
    amount: string;
    /**
     * 
     * @type {UniversalAddress}
     * @memberof TransactionListResponseDtoItemsInner
     */
    fromAddress: UniversalAddress | null;
    /**
     * 
     * @type {UniversalAddress}
     * @memberof TransactionListResponseDtoItemsInner
     */
    toAddress: UniversalAddress | null;
    /**
     * Queue operation unique identifier
     * @type {string}
     * @memberof TransactionListResponseDtoItemsInner
     */
    operationId: string | null;
    /**
     * Type of operation this transaction belongs to
     * @type {TransactionListResponseDtoItemsInnerOperationTypeEnum}
     * @memberof TransactionListResponseDtoItemsInner
     */
    operationType: TransactionListResponseDtoItemsInnerOperationTypeEnum | null;
    /**
     * Block number of the transaction
     * @type {string}
     * @memberof TransactionListResponseDtoItemsInner
     */
    blockNumber: string | null;
    /**
     * Blockchain transaction fee
     * @type {string}
     * @memberof TransactionListResponseDtoItemsInner
     */
    blockchainFee: string;
    /**
     * Number of blockchain confirmations
     * @type {number}
     * @memberof TransactionListResponseDtoItemsInner
     */
    confirmations: number;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof TransactionListResponseDtoItemsInner
     */
    createdAt: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof TransactionListResponseDtoItemsInner
     */
    updatedAt: string;
    /**
     * Can this invoice be claimed
     * @type {boolean}
     * @memberof TransactionListResponseDtoItemsInner
     */
    canClaim: boolean;
    /**
     * Whether this transaction has been claimed
     * @type {boolean}
     * @memberof TransactionListResponseDtoItemsInner
     */
    isClaimed: boolean;
    /**
     * For IN transactions, same as operationId
     * @type {string}
     * @memberof TransactionListResponseDtoItemsInner
     */
    invoiceId: string | null;
    /**
     * Timestamp when transfer was confirmed
     * @type {string}
     * @memberof TransactionListResponseDtoItemsInner
     */
    confirmedAt: string | null;
    /**
     * 
     * @type {TransactionListResponseDtoItemsInnerInvoice}
     * @memberof TransactionListResponseDtoItemsInner
     */
    invoice?: TransactionListResponseDtoItemsInnerInvoice | null;
    /**
     * 
     * @type {CurrencyResponseDto}
     * @memberof TransactionListResponseDtoItemsInner
     */
    currency: CurrencyResponseDto | null;
    /**
     * 
     * @type {TransactionDappMetadata}
     * @memberof TransactionListResponseDtoItemsInner
     */
    dappMetadata?: TransactionDappMetadata;
    /**
     * Executed inner calls (atomic multicall payload from queue_operation) for dapp-originated transactions. Omitted when transaction is not dapp-originated.
     * @type {Array<TransactionListResponseDtoItemsInnerCallsInner>}
     * @memberof TransactionListResponseDtoItemsInner
     */
    calls?: Array<TransactionListResponseDtoItemsInnerCallsInner>;
}


/**
 * @export
 */
export const TransactionListResponseDtoItemsInnerDirectionEnum = {
    In: 'IN',
    Out: 'OUT'
} as const;
export type TransactionListResponseDtoItemsInnerDirectionEnum = typeof TransactionListResponseDtoItemsInnerDirectionEnum[keyof typeof TransactionListResponseDtoItemsInnerDirectionEnum];

/**
 * @export
 */
export const TransactionListResponseDtoItemsInnerStatusEnum = {
    Pending: 'PENDING',
    Executed: 'EXECUTED',
    Confirmed: 'CONFIRMED',
    Failed: 'FAILED'
} as const;
export type TransactionListResponseDtoItemsInnerStatusEnum = typeof TransactionListResponseDtoItemsInnerStatusEnum[keyof typeof TransactionListResponseDtoItemsInnerStatusEnum];

/**
 * @export
 */
export const TransactionListResponseDtoItemsInnerOperationTypeEnum = {
    Invoice: 'invoice',
    DirectDeposit: 'direct_deposit',
    SetConfig: 'set_config',
    Claim: 'claim',
    Payout: 'payout',
    Reject: 'reject',
    Deploy: 'deploy',
    DappTransaction: 'dapp_transaction'
} as const;
export type TransactionListResponseDtoItemsInnerOperationTypeEnum = typeof TransactionListResponseDtoItemsInnerOperationTypeEnum[keyof typeof TransactionListResponseDtoItemsInnerOperationTypeEnum];


/**
 * Check if a given object implements the TransactionListResponseDtoItemsInner interface.
 */
export function instanceOfTransactionListResponseDtoItemsInner(value: object): value is TransactionListResponseDtoItemsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    if (!('txHash' in value) || value['txHash'] === undefined) return false;
    if (!('currencyId' in value) || value['currencyId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('fromAddress' in value) || value['fromAddress'] === undefined) return false;
    if (!('toAddress' in value) || value['toAddress'] === undefined) return false;
    if (!('operationId' in value) || value['operationId'] === undefined) return false;
    if (!('operationType' in value) || value['operationType'] === undefined) return false;
    if (!('blockNumber' in value) || value['blockNumber'] === undefined) return false;
    if (!('blockchainFee' in value) || value['blockchainFee'] === undefined) return false;
    if (!('confirmations' in value) || value['confirmations'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('canClaim' in value) || value['canClaim'] === undefined) return false;
    if (!('isClaimed' in value) || value['isClaimed'] === undefined) return false;
    if (!('invoiceId' in value) || value['invoiceId'] === undefined) return false;
    if (!('confirmedAt' in value) || value['confirmedAt'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function TransactionListResponseDtoItemsInnerFromJSON(json: any): TransactionListResponseDtoItemsInner {
    return TransactionListResponseDtoItemsInnerFromJSONTyped(json, false);
}

export function TransactionListResponseDtoItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionListResponseDtoItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'direction': json['direction'],
        'status': json['status'],
        'chainId': json['chainId'],
        'txHash': json['txHash'],
        'currencyId': json['currencyId'],
        'amount': json['amount'],
        'fromAddress': UniversalAddressFromJSON(json['fromAddress']),
        'toAddress': UniversalAddressFromJSON(json['toAddress']),
        'operationId': json['operationId'],
        'operationType': json['operationType'],
        'blockNumber': json['blockNumber'],
        'blockchainFee': json['blockchainFee'],
        'confirmations': json['confirmations'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'canClaim': json['canClaim'],
        'isClaimed': json['isClaimed'],
        'invoiceId': json['invoiceId'],
        'confirmedAt': json['confirmedAt'],
        'invoice': json['invoice'] == null ? undefined : TransactionListResponseDtoItemsInnerInvoiceFromJSON(json['invoice']),
        'currency': CurrencyResponseDtoFromJSON(json['currency']),
        'dappMetadata': json['dappMetadata'] == null ? undefined : TransactionDappMetadataFromJSON(json['dappMetadata']),
        'calls': json['calls'] == null ? undefined : ((json['calls'] as Array<any>).map(TransactionListResponseDtoItemsInnerCallsInnerFromJSON)),
    };
}

export function TransactionListResponseDtoItemsInnerToJSON(json: any): TransactionListResponseDtoItemsInner {
    return TransactionListResponseDtoItemsInnerToJSONTyped(json, false);
}

export function TransactionListResponseDtoItemsInnerToJSONTyped(value?: TransactionListResponseDtoItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'direction': value['direction'],
        'status': value['status'],
        'chainId': value['chainId'],
        'txHash': value['txHash'],
        'currencyId': value['currencyId'],
        'amount': value['amount'],
        'fromAddress': UniversalAddressToJSON(value['fromAddress']),
        'toAddress': UniversalAddressToJSON(value['toAddress']),
        'operationId': value['operationId'],
        'operationType': value['operationType'],
        'blockNumber': value['blockNumber'],
        'blockchainFee': value['blockchainFee'],
        'confirmations': value['confirmations'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'canClaim': value['canClaim'],
        'isClaimed': value['isClaimed'],
        'invoiceId': value['invoiceId'],
        'confirmedAt': value['confirmedAt'],
        'invoice': TransactionListResponseDtoItemsInnerInvoiceToJSON(value['invoice']),
        'currency': CurrencyResponseDtoToJSON(value['currency']),
        'dappMetadata': TransactionDappMetadataToJSON(value['dappMetadata']),
        'calls': value['calls'] == null ? undefined : ((value['calls'] as Array<any>).map(TransactionListResponseDtoItemsInnerCallsInnerToJSON)),
    };
}

