/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Related invoice information
 * @export
 * @interface TransactionListResponseDtoItemsInnerInvoice
 */
export interface TransactionListResponseDtoItemsInnerInvoice {
    /**
     * Entity unique identifier
     * @type {string}
     * @memberof TransactionListResponseDtoItemsInnerInvoice
     */
    id: string;
    /**
     * Tracking identifier
     * @type {string}
     * @memberof TransactionListResponseDtoItemsInnerInvoice
     */
    trackingId: string | null;
    /**
     * Invoice status
     * @type {TransactionListResponseDtoItemsInnerInvoiceStatusEnum}
     * @memberof TransactionListResponseDtoItemsInnerInvoice
     */
    status: TransactionListResponseDtoItemsInnerInvoiceStatusEnum;
}


/**
 * @export
 */
export const TransactionListResponseDtoItemsInnerInvoiceStatusEnum = {
    Created: 'CREATED',
    Paid: 'PAID',
    Unresolved: 'UNRESOLVED'
} as const;
export type TransactionListResponseDtoItemsInnerInvoiceStatusEnum = typeof TransactionListResponseDtoItemsInnerInvoiceStatusEnum[keyof typeof TransactionListResponseDtoItemsInnerInvoiceStatusEnum];


/**
 * Check if a given object implements the TransactionListResponseDtoItemsInnerInvoice interface.
 */
export function instanceOfTransactionListResponseDtoItemsInnerInvoice(value: object): value is TransactionListResponseDtoItemsInnerInvoice {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('trackingId' in value) || value['trackingId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function TransactionListResponseDtoItemsInnerInvoiceFromJSON(json: any): TransactionListResponseDtoItemsInnerInvoice {
    return TransactionListResponseDtoItemsInnerInvoiceFromJSONTyped(json, false);
}

export function TransactionListResponseDtoItemsInnerInvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionListResponseDtoItemsInnerInvoice {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'trackingId': json['trackingId'],
        'status': json['status'],
    };
}

export function TransactionListResponseDtoItemsInnerInvoiceToJSON(json: any): TransactionListResponseDtoItemsInnerInvoice {
    return TransactionListResponseDtoItemsInnerInvoiceToJSONTyped(json, false);
}

export function TransactionListResponseDtoItemsInnerInvoiceToJSONTyped(value?: TransactionListResponseDtoItemsInnerInvoice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'trackingId': value['trackingId'],
        'status': value['status'],
    };
}

