/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionInvoiceResponseDto
 */
export interface TransactionInvoiceResponseDto {
    /**
     * Entity unique identifier
     * @type {string}
     * @memberof TransactionInvoiceResponseDto
     */
    id: string;
    /**
     * Tracking identifier
     * @type {string}
     * @memberof TransactionInvoiceResponseDto
     */
    trackingId: string | null;
    /**
     * Invoice status
     * @type {string}
     * @memberof TransactionInvoiceResponseDto
     */
    status: string;
}

/**
 * Check if a given object implements the TransactionInvoiceResponseDto interface.
 */
export function instanceOfTransactionInvoiceResponseDto(value: object): value is TransactionInvoiceResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('trackingId' in value) || value['trackingId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function TransactionInvoiceResponseDtoFromJSON(json: any): TransactionInvoiceResponseDto {
    return TransactionInvoiceResponseDtoFromJSONTyped(json, false);
}

export function TransactionInvoiceResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionInvoiceResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'trackingId': json['trackingId'],
        'status': json['status'],
    };
}

export function TransactionInvoiceResponseDtoToJSON(json: any): TransactionInvoiceResponseDto {
    return TransactionInvoiceResponseDtoToJSONTyped(json, false);
}

export function TransactionInvoiceResponseDtoToJSONTyped(value?: TransactionInvoiceResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'trackingId': value['trackingId'],
        'status': value['status'],
    };
}

