/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type UniversalAddress
 * Blockchain address in either Ethereum or Tron format (depending on the context)
 * @export
 */
export type UniversalAddress = string;

export function UniversalAddressFromJSON(json: any): UniversalAddress {
    return UniversalAddressFromJSONTyped(json, false);
}

export function UniversalAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): UniversalAddress {
    if (json == null) {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function UniversalAddressToJSON(json: any): any {
    return UniversalAddressToJSONTyped(json, false);
}

export function UniversalAddressToJSONTyped(value?: UniversalAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

