/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnstakeBodyDto
 */
export interface UnstakeBodyDto {
    /**
     * TRX amount to unstake (decimal)
     * @type {string}
     * @memberof UnstakeBodyDto
     */
    amount: string;
    /**
     * Resource type
     * @type {UnstakeBodyDtoResourceTypeEnum}
     * @memberof UnstakeBodyDto
     */
    resourceType: UnstakeBodyDtoResourceTypeEnum;
}


/**
 * @export
 */
export const UnstakeBodyDtoResourceTypeEnum = {
    Bandwidth: 'BANDWIDTH',
    Energy: 'ENERGY'
} as const;
export type UnstakeBodyDtoResourceTypeEnum = typeof UnstakeBodyDtoResourceTypeEnum[keyof typeof UnstakeBodyDtoResourceTypeEnum];


/**
 * Check if a given object implements the UnstakeBodyDto interface.
 */
export function instanceOfUnstakeBodyDto(value: object): value is UnstakeBodyDto {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('resourceType' in value) || value['resourceType'] === undefined) return false;
    return true;
}

export function UnstakeBodyDtoFromJSON(json: any): UnstakeBodyDto {
    return UnstakeBodyDtoFromJSONTyped(json, false);
}

export function UnstakeBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnstakeBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'resourceType': json['resourceType'],
    };
}

export function UnstakeBodyDtoToJSON(json: any): UnstakeBodyDto {
    return UnstakeBodyDtoToJSONTyped(json, false);
}

export function UnstakeBodyDtoToJSONTyped(value?: UnstakeBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'resourceType': value['resourceType'],
    };
}

