/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAccountDto
 */
export interface UpdateAccountDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountDto
     */
    name: string;
}

/**
 * Check if a given object implements the UpdateAccountDto interface.
 */
export function instanceOfUpdateAccountDto(value: object): value is UpdateAccountDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateAccountDtoFromJSON(json: any): UpdateAccountDto {
    return UpdateAccountDtoFromJSONTyped(json, false);
}

export function UpdateAccountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAccountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UpdateAccountDtoToJSON(json: any): UpdateAccountDto {
    return UpdateAccountDtoToJSONTyped(json, false);
}

export function UpdateAccountDtoToJSONTyped(value?: UpdateAccountDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

