/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProfileRequestDto
 */
export interface UpdateProfileRequestDto {
    /**
     * Base currency for conversion
     * @type {string}
     * @memberof UpdateProfileRequestDto
     */
    baseCurrency?: UpdateProfileRequestDtoBaseCurrencyEnum;
    /**
     * Whether unverified currencies are hidden for the current user by default
     * @type {boolean}
     * @memberof UpdateProfileRequestDto
     */
    hideUnverifiedCurrencies?: boolean;
}


/**
 * @export
 */
export const UpdateProfileRequestDtoBaseCurrencyEnum = {
    Usd: 'usd',
    Eur: 'eur',
    Cny: 'cny'
} as const;
export type UpdateProfileRequestDtoBaseCurrencyEnum = typeof UpdateProfileRequestDtoBaseCurrencyEnum[keyof typeof UpdateProfileRequestDtoBaseCurrencyEnum];


/**
 * Check if a given object implements the UpdateProfileRequestDto interface.
 */
export function instanceOfUpdateProfileRequestDto(value: object): value is UpdateProfileRequestDto {
    return true;
}

export function UpdateProfileRequestDtoFromJSON(json: any): UpdateProfileRequestDto {
    return UpdateProfileRequestDtoFromJSONTyped(json, false);
}

export function UpdateProfileRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfileRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'baseCurrency': json['baseCurrency'] == null ? undefined : json['baseCurrency'],
        'hideUnverifiedCurrencies': json['hideUnverifiedCurrencies'] == null ? undefined : json['hideUnverifiedCurrencies'],
    };
}

export function UpdateProfileRequestDtoToJSON(json: any): UpdateProfileRequestDto {
    return UpdateProfileRequestDtoToJSONTyped(json, false);
}

export function UpdateProfileRequestDtoToJSONTyped(value?: UpdateProfileRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'baseCurrency': value['baseCurrency'],
        'hideUnverifiedCurrencies': value['hideUnverifiedCurrencies'],
    };
}

