/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateOperationNonceDto
 */
export interface UpdateOperationNonceDto {
    /**
     * Nonce (transaction ordering) as a non-negative integer string
     * @type {string}
     * @memberof UpdateOperationNonceDto
     */
    nonce: string;
}

/**
 * Check if a given object implements the UpdateOperationNonceDto interface.
 */
export function instanceOfUpdateOperationNonceDto(value: object): value is UpdateOperationNonceDto {
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    return true;
}

export function UpdateOperationNonceDtoFromJSON(json: any): UpdateOperationNonceDto {
    return UpdateOperationNonceDtoFromJSONTyped(json, false);
}

export function UpdateOperationNonceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOperationNonceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'nonce': json['nonce'],
    };
}

export function UpdateOperationNonceDtoToJSON(json: any): UpdateOperationNonceDto {
    return UpdateOperationNonceDtoToJSONTyped(json, false);
}

export function UpdateOperationNonceDtoToJSONTyped(value?: UpdateOperationNonceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nonce': value['nonce'],
    };
}

