/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserResponseDto
 */
export interface UserResponseDto {
    /**
     * Entity unique identifier
     * @type {string}
     * @memberof UserResponseDto
     */
    id: string;
    /**
     * Wallet address (Ethereum 0x... or Tron TVM T...)
     * @type {string}
     * @memberof UserResponseDto
     */
    address: string;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof UserResponseDto
     */
    createdAt: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof UserResponseDto
     */
    updatedAt: string;
    /**
     * Last login timestamp
     * @type {string}
     * @memberof UserResponseDto
     */
    lastLoginAt: string | null;
    /**
     * Whether unverified currencies are hidden for the current user by default
     * @type {boolean}
     * @memberof UserResponseDto
     */
    hideUnverifiedCurrencies: boolean;
}

/**
 * Check if a given object implements the UserResponseDto interface.
 */
export function instanceOfUserResponseDto(value: object): value is UserResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('lastLoginAt' in value) || value['lastLoginAt'] === undefined) return false;
    if (!('hideUnverifiedCurrencies' in value) || value['hideUnverifiedCurrencies'] === undefined) return false;
    return true;
}

export function UserResponseDtoFromJSON(json: any): UserResponseDto {
    return UserResponseDtoFromJSONTyped(json, false);
}

export function UserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'address': json['address'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'lastLoginAt': json['lastLoginAt'],
        'hideUnverifiedCurrencies': json['hideUnverifiedCurrencies'],
    };
}

export function UserResponseDtoToJSON(json: any): UserResponseDto {
    return UserResponseDtoToJSONTyped(json, false);
}

export function UserResponseDtoToJSONTyped(value?: UserResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'address': value['address'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
        'lastLoginAt': value['lastLoginAt'],
        'hideUnverifiedCurrencies': value['hideUnverifiedCurrencies'],
    };
}

