/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountDetailsDto,
  AccountResponseDto,
  AssetBalanceShortResponseDto,
  AssetBalancesResponseDto,
  BalanceSummaryResponseDto,
  CurrenciesControllerFindAllV1IsNativeParameter,
  DeploymentParamsResponseDto,
  NonceInfoResponseDto,
  TransactionsControllerGetTransactionsV1CurrencyIsScamParameter,
  UpdateAccountDto,
} from '../models/index';
import {
    AccountDetailsDtoFromJSON,
    AccountDetailsDtoToJSON,
    AccountResponseDtoFromJSON,
    AccountResponseDtoToJSON,
    AssetBalanceShortResponseDtoFromJSON,
    AssetBalanceShortResponseDtoToJSON,
    AssetBalancesResponseDtoFromJSON,
    AssetBalancesResponseDtoToJSON,
    BalanceSummaryResponseDtoFromJSON,
    BalanceSummaryResponseDtoToJSON,
    CurrenciesControllerFindAllV1IsNativeParameterFromJSON,
    CurrenciesControllerFindAllV1IsNativeParameterToJSON,
    DeploymentParamsResponseDtoFromJSON,
    DeploymentParamsResponseDtoToJSON,
    NonceInfoResponseDtoFromJSON,
    NonceInfoResponseDtoToJSON,
    TransactionsControllerGetTransactionsV1CurrencyIsScamParameterFromJSON,
    TransactionsControllerGetTransactionsV1CurrencyIsScamParameterToJSON,
    UpdateAccountDtoFromJSON,
    UpdateAccountDtoToJSON,
} from '../models/index';

export interface AccountDeploymentsControllerGetNonceInfoV1Request {
    deploymentId: string;
}

export interface AccountsControllerFindAccountByIdV1Request {
    accountId: string;
}

export interface AccountsControllerFindUserAccountsV1Request {
    isHidden?: TransactionsControllerGetTransactionsV1CurrencyIsScamParameter;
}

export interface AccountsControllerGetAssetBalancesV1Request {
    accountId: string;
    baseCurrency: AccountsControllerGetAssetBalancesV1BaseCurrencyEnum;
    chainId: string;
    page?: number;
    pageSize?: number;
    sortBy?: AccountsControllerGetAssetBalancesV1SortByEnum;
    sortOrder?: AccountsControllerGetAssetBalancesV1SortOrderEnum;
    currencyIds?: Array<string>;
    isScam?: CurrenciesControllerFindAllV1IsNativeParameter;
    isVerified?: CurrenciesControllerFindAllV1IsNativeParameter;
    isHidden?: CurrenciesControllerFindAllV1IsNativeParameter;
}

export interface AccountsControllerGetBalanceSummaryV1Request {
    accountId: string;
    baseCurrency: AccountsControllerGetBalanceSummaryV1BaseCurrencyEnum;
    chainId: string;
}

export interface AccountsControllerGetDeploymentInfoV1Request {
    accountId: string;
}

export interface AccountsControllerGetShortAssetBalancesV1Request {
    accountId: string;
    chainId: string;
    currencyIds?: Array<string>;
    isScam?: CurrenciesControllerFindAllV1IsNativeParameter;
    isVerified?: CurrenciesControllerFindAllV1IsNativeParameter;
    isHidden?: CurrenciesControllerFindAllV1IsNativeParameter;
}

export interface AccountsControllerUpdateAccountV1Request {
    accountId: string;
    updateAccountDto: UpdateAccountDto;
}

/**
 * 
 */
export class AccountsApi extends runtime.BaseAPI {

    /**
     * Returns current nonce and last executed nonce for the deployment
     * Get nonce information
     */
    async accountDeploymentsControllerGetNonceInfoV1Raw(requestParameters: AccountDeploymentsControllerGetNonceInfoV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NonceInfoResponseDto>> {
        if (requestParameters['deploymentId'] == null) {
            throw new runtime.RequiredError(
                'deploymentId',
                'Required parameter "deploymentId" was null or undefined when calling accountDeploymentsControllerGetNonceInfoV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/accounts/deployments/{deploymentId}/nonce-info`;
        urlPath = urlPath.replace(`{${"deploymentId"}}`, encodeURIComponent(String(requestParameters['deploymentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NonceInfoResponseDtoFromJSON(jsonValue));
    }

    /**
     * Returns current nonce and last executed nonce for the deployment
     * Get nonce information
     */
    async accountDeploymentsControllerGetNonceInfoV1(requestParameters: AccountDeploymentsControllerGetNonceInfoV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NonceInfoResponseDto> {
        const response = await this.accountDeploymentsControllerGetNonceInfoV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get entity by ID
     * Get by ID
     */
    async accountsControllerFindAccountByIdV1Raw(requestParameters: AccountsControllerFindAccountByIdV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountDetailsDto>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling accountsControllerFindAccountByIdV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/accounts/{accountId}`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountDetailsDtoFromJSON(jsonValue));
    }

    /**
     * Get entity by ID
     * Get by ID
     */
    async accountsControllerFindAccountByIdV1(requestParameters: AccountsControllerFindAccountByIdV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountDetailsDto> {
        const response = await this.accountsControllerFindAccountByIdV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get list of entities
     * Get list
     */
    async accountsControllerFindUserAccountsV1Raw(requestParameters: AccountsControllerFindUserAccountsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AccountResponseDto>>> {
        const queryParameters: any = {};

        if (requestParameters['isHidden'] != null) {
            queryParameters['isHidden'] = requestParameters['isHidden'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/accounts`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AccountResponseDtoFromJSON));
    }

    /**
     * Get list of entities
     * Get list
     */
    async accountsControllerFindUserAccountsV1(requestParameters: AccountsControllerFindUserAccountsV1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AccountResponseDto>> {
        const response = await this.accountsControllerFindUserAccountsV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns balances for each asset with conversion to base currency for a specific network with pagination
     * Get asset balances
     */
    async accountsControllerGetAssetBalancesV1Raw(requestParameters: AccountsControllerGetAssetBalancesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AssetBalancesResponseDto>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling accountsControllerGetAssetBalancesV1().'
            );
        }

        if (requestParameters['baseCurrency'] == null) {
            throw new runtime.RequiredError(
                'baseCurrency',
                'Required parameter "baseCurrency" was null or undefined when calling accountsControllerGetAssetBalancesV1().'
            );
        }

        if (requestParameters['chainId'] == null) {
            throw new runtime.RequiredError(
                'chainId',
                'Required parameter "chainId" was null or undefined when calling accountsControllerGetAssetBalancesV1().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['sortOrder'] != null) {
            queryParameters['sortOrder'] = requestParameters['sortOrder'];
        }

        if (requestParameters['baseCurrency'] != null) {
            queryParameters['baseCurrency'] = requestParameters['baseCurrency'];
        }

        if (requestParameters['chainId'] != null) {
            queryParameters['chainId'] = requestParameters['chainId'];
        }

        if (requestParameters['currencyIds'] != null) {
            queryParameters['currencyIds'] = requestParameters['currencyIds'];
        }

        if (requestParameters['isScam'] != null) {
            queryParameters['isScam'] = requestParameters['isScam'];
        }

        if (requestParameters['isVerified'] != null) {
            queryParameters['isVerified'] = requestParameters['isVerified'];
        }

        if (requestParameters['isHidden'] != null) {
            queryParameters['isHidden'] = requestParameters['isHidden'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/accounts/{accountId}/balance/assets`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssetBalancesResponseDtoFromJSON(jsonValue));
    }

    /**
     * Returns balances for each asset with conversion to base currency for a specific network with pagination
     * Get asset balances
     */
    async accountsControllerGetAssetBalancesV1(requestParameters: AccountsControllerGetAssetBalancesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AssetBalancesResponseDto> {
        const response = await this.accountsControllerGetAssetBalancesV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns total balance, uncollected balance and count of uncollected invoices for a team on a specific network
     * Get balance summary
     */
    async accountsControllerGetBalanceSummaryV1Raw(requestParameters: AccountsControllerGetBalanceSummaryV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BalanceSummaryResponseDto>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling accountsControllerGetBalanceSummaryV1().'
            );
        }

        if (requestParameters['baseCurrency'] == null) {
            throw new runtime.RequiredError(
                'baseCurrency',
                'Required parameter "baseCurrency" was null or undefined when calling accountsControllerGetBalanceSummaryV1().'
            );
        }

        if (requestParameters['chainId'] == null) {
            throw new runtime.RequiredError(
                'chainId',
                'Required parameter "chainId" was null or undefined when calling accountsControllerGetBalanceSummaryV1().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['baseCurrency'] != null) {
            queryParameters['baseCurrency'] = requestParameters['baseCurrency'];
        }

        if (requestParameters['chainId'] != null) {
            queryParameters['chainId'] = requestParameters['chainId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/accounts/{accountId}/balance/summary`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BalanceSummaryResponseDtoFromJSON(jsonValue));
    }

    /**
     * Returns total balance, uncollected balance and count of uncollected invoices for a team on a specific network
     * Get balance summary
     */
    async accountsControllerGetBalanceSummaryV1(requestParameters: AccountsControllerGetBalanceSummaryV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BalanceSummaryResponseDto> {
        const response = await this.accountsControllerGetBalanceSummaryV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get parameters required to deploy the team including bytecode, initializer bytecode, and nonce
     * Get deployment params
     */
    async accountsControllerGetDeploymentInfoV1Raw(requestParameters: AccountsControllerGetDeploymentInfoV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeploymentParamsResponseDto>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling accountsControllerGetDeploymentInfoV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/accounts/{accountId}/deploy-params`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeploymentParamsResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get parameters required to deploy the team including bytecode, initializer bytecode, and nonce
     * Get deployment params
     */
    async accountsControllerGetDeploymentInfoV1(requestParameters: AccountsControllerGetDeploymentInfoV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeploymentParamsResponseDto> {
        const response = await this.accountsControllerGetDeploymentInfoV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns asset balances without conversion and pagination. Response is a flat array of items.
     * Get asset balances (short)
     */
    async accountsControllerGetShortAssetBalancesV1Raw(requestParameters: AccountsControllerGetShortAssetBalancesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AssetBalanceShortResponseDto>>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling accountsControllerGetShortAssetBalancesV1().'
            );
        }

        if (requestParameters['chainId'] == null) {
            throw new runtime.RequiredError(
                'chainId',
                'Required parameter "chainId" was null or undefined when calling accountsControllerGetShortAssetBalancesV1().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['currencyIds'] != null) {
            queryParameters['currencyIds'] = requestParameters['currencyIds'];
        }

        if (requestParameters['isScam'] != null) {
            queryParameters['isScam'] = requestParameters['isScam'];
        }

        if (requestParameters['isVerified'] != null) {
            queryParameters['isVerified'] = requestParameters['isVerified'];
        }

        if (requestParameters['isHidden'] != null) {
            queryParameters['isHidden'] = requestParameters['isHidden'];
        }

        if (requestParameters['chainId'] != null) {
            queryParameters['chainId'] = requestParameters['chainId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/accounts/{accountId}/balances`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AssetBalanceShortResponseDtoFromJSON));
    }

    /**
     * Returns asset balances without conversion and pagination. Response is a flat array of items.
     * Get asset balances (short)
     */
    async accountsControllerGetShortAssetBalancesV1(requestParameters: AccountsControllerGetShortAssetBalancesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AssetBalanceShortResponseDto>> {
        const response = await this.accountsControllerGetShortAssetBalancesV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update entity
     * Update
     */
    async accountsControllerUpdateAccountV1Raw(requestParameters: AccountsControllerUpdateAccountV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountResponseDto>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling accountsControllerUpdateAccountV1().'
            );
        }

        if (requestParameters['updateAccountDto'] == null) {
            throw new runtime.RequiredError(
                'updateAccountDto',
                'Required parameter "updateAccountDto" was null or undefined when calling accountsControllerUpdateAccountV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/accounts/{accountId}`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAccountDtoToJSON(requestParameters['updateAccountDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountResponseDtoFromJSON(jsonValue));
    }

    /**
     * Update entity
     * Update
     */
    async accountsControllerUpdateAccountV1(requestParameters: AccountsControllerUpdateAccountV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountResponseDto> {
        const response = await this.accountsControllerUpdateAccountV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const AccountsControllerGetAssetBalancesV1BaseCurrencyEnum = {
    Usd: 'usd',
    Eur: 'eur',
    Cny: 'cny'
} as const;
export type AccountsControllerGetAssetBalancesV1BaseCurrencyEnum = typeof AccountsControllerGetAssetBalancesV1BaseCurrencyEnum[keyof typeof AccountsControllerGetAssetBalancesV1BaseCurrencyEnum];
/**
 * @export
 */
export const AccountsControllerGetAssetBalancesV1SortByEnum = {
    Balance: 'balance',
    ConvertedBalance: 'converted_balance'
} as const;
export type AccountsControllerGetAssetBalancesV1SortByEnum = typeof AccountsControllerGetAssetBalancesV1SortByEnum[keyof typeof AccountsControllerGetAssetBalancesV1SortByEnum];
/**
 * @export
 */
export const AccountsControllerGetAssetBalancesV1SortOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type AccountsControllerGetAssetBalancesV1SortOrderEnum = typeof AccountsControllerGetAssetBalancesV1SortOrderEnum[keyof typeof AccountsControllerGetAssetBalancesV1SortOrderEnum];
/**
 * @export
 */
export const AccountsControllerGetBalanceSummaryV1BaseCurrencyEnum = {
    Usd: 'usd',
    Eur: 'eur',
    Cny: 'cny'
} as const;
export type AccountsControllerGetBalanceSummaryV1BaseCurrencyEnum = typeof AccountsControllerGetBalanceSummaryV1BaseCurrencyEnum[keyof typeof AccountsControllerGetBalanceSummaryV1BaseCurrencyEnum];
