/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetCallbacksResponseDto,
  ResendCallbacksBodyDto,
  ResendCallbacksResponseDto,
} from '../models/index';
import {
    GetCallbacksResponseDtoFromJSON,
    GetCallbacksResponseDtoToJSON,
    ResendCallbacksBodyDtoFromJSON,
    ResendCallbacksBodyDtoToJSON,
    ResendCallbacksResponseDtoFromJSON,
    ResendCallbacksResponseDtoToJSON,
} from '../models/index';

export interface CallbacksControllerGetCallbacksV1Request {
    operationId: string;
    page?: number;
    pageSize?: number;
}

export interface CallbacksControllerResendCallbacksV1Request {
    resendCallbacksBodyDto: ResendCallbacksBodyDto;
}

/**
 * 
 */
export class CallbacksApi extends runtime.BaseAPI {

    /**
     * Retrieve a paginated list of callbacks for a specific operation ID
     * Get callbacks by operation ID
     */
    async callbacksControllerGetCallbacksV1Raw(requestParameters: CallbacksControllerGetCallbacksV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCallbacksResponseDto>> {
        if (requestParameters['operationId'] == null) {
            throw new runtime.RequiredError(
                'operationId',
                'Required parameter "operationId" was null or undefined when calling callbacksControllerGetCallbacksV1().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['operationId'] != null) {
            queryParameters['operationId'] = requestParameters['operationId'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/callbacks`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCallbacksResponseDtoFromJSON(jsonValue));
    }

    /**
     * Retrieve a paginated list of callbacks for a specific operation ID
     * Get callbacks by operation ID
     */
    async callbacksControllerGetCallbacksV1(requestParameters: CallbacksControllerGetCallbacksV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCallbacksResponseDto> {
        const response = await this.callbacksControllerGetCallbacksV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Re-queue failed callbacks for delivery by resetting their status. Only FAILED callbacks owned by the current user are eligible.
     * Resend failed callbacks
     */
    async callbacksControllerResendCallbacksV1Raw(requestParameters: CallbacksControllerResendCallbacksV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResendCallbacksResponseDto>> {
        if (requestParameters['resendCallbacksBodyDto'] == null) {
            throw new runtime.RequiredError(
                'resendCallbacksBodyDto',
                'Required parameter "resendCallbacksBodyDto" was null or undefined when calling callbacksControllerResendCallbacksV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/callbacks/resend`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResendCallbacksBodyDtoToJSON(requestParameters['resendCallbacksBodyDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResendCallbacksResponseDtoFromJSON(jsonValue));
    }

    /**
     * Re-queue failed callbacks for delivery by resetting their status. Only FAILED callbacks owned by the current user are eligible.
     * Resend failed callbacks
     */
    async callbacksControllerResendCallbacksV1(requestParameters: CallbacksControllerResendCallbacksV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResendCallbacksResponseDto> {
        const response = await this.callbacksControllerResendCallbacksV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
