/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateCrossChainTransferDto,
    CreateCrossChainTransferDtoFromJSON,
    CreateCrossChainTransferDtoToJSON,
} from '../models/create-cross-chain-transfer-dto';
import {
    type CrossChainChainResponseDto,
    CrossChainChainResponseDtoFromJSON,
    CrossChainChainResponseDtoToJSON,
} from '../models/cross-chain-chain-response-dto';
import {
    type CrossChainQuotesResponseDto,
    CrossChainQuotesResponseDtoFromJSON,
    CrossChainQuotesResponseDtoToJSON,
} from '../models/cross-chain-quotes-response-dto';
import {
    type CrossChainTransferResponseDto,
    CrossChainTransferResponseDtoFromJSON,
    CrossChainTransferResponseDtoToJSON,
} from '../models/cross-chain-transfer-response-dto';
import {
    type CurrencyResponseDto,
    CurrencyResponseDtoFromJSON,
    CurrencyResponseDtoToJSON,
} from '../models/currency-response-dto';
import {
    type QuoteRequestDto,
    QuoteRequestDtoFromJSON,
    QuoteRequestDtoToJSON,
} from '../models/quote-request-dto';

export interface CrossChainControllerListDestinationCurrenciesV1Request {
    deploymentId?: string;
    srcCurrencyId?: string;
}

export interface DeploymentCrossChainControllerCreateTransferV1Request {
    deploymentId: string;
    createCrossChainTransferDto: CreateCrossChainTransferDto;
}

export interface DeploymentCrossChainControllerGetQuoteV1Request {
    deploymentId: string;
    quoteRequestDto: QuoteRequestDto;
}

export interface DeploymentCrossChainControllerListSourceCurrenciesV1Request {
    deploymentId: string;
}

/**
 * 
 */
export class CrossChainTransfersApi extends runtime.BaseAPI {

    /**
     * Creates request options for crossChainControllerListChainsV1 without sending the request
     */
    async crossChainControllerListChainsV1RequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/cross-chain/chains`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List LayerZero-supported chains available on the platform
     */
    async crossChainControllerListChainsV1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CrossChainChainResponseDto>>> {
        const requestOptions = await this.crossChainControllerListChainsV1RequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CrossChainChainResponseDtoFromJSON));
    }

    /**
     * List LayerZero-supported chains available on the platform
     */
    async crossChainControllerListChainsV1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CrossChainChainResponseDto>> {
        const response = await this.crossChainControllerListChainsV1Raw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for crossChainControllerListDestinationCurrenciesV1 without sending the request
     */
    async crossChainControllerListDestinationCurrenciesV1RequestOpts(requestParameters: CrossChainControllerListDestinationCurrenciesV1Request): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['deploymentId'] != null) {
            queryParameters['deploymentId'] = requestParameters['deploymentId'];
        }

        if (requestParameters['srcCurrencyId'] != null) {
            queryParameters['srcCurrencyId'] = requestParameters['srcCurrencyId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/cross-chain/destination-currencies`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List destination currencies, optionally filtered by source deployment + currency
     */
    async crossChainControllerListDestinationCurrenciesV1Raw(requestParameters: CrossChainControllerListDestinationCurrenciesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CurrencyResponseDto>>> {
        const requestOptions = await this.crossChainControllerListDestinationCurrenciesV1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CurrencyResponseDtoFromJSON));
    }

    /**
     * List destination currencies, optionally filtered by source deployment + currency
     */
    async crossChainControllerListDestinationCurrenciesV1(requestParameters: CrossChainControllerListDestinationCurrenciesV1Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CurrencyResponseDto>> {
        const response = await this.crossChainControllerListDestinationCurrenciesV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deploymentCrossChainControllerCreateTransferV1 without sending the request
     */
    async deploymentCrossChainControllerCreateTransferV1RequestOpts(requestParameters: DeploymentCrossChainControllerCreateTransferV1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['deploymentId'] == null) {
            throw new runtime.RequiredError(
                'deploymentId',
                'Required parameter "deploymentId" was null or undefined when calling deploymentCrossChainControllerCreateTransferV1().'
            );
        }

        if (requestParameters['createCrossChainTransferDto'] == null) {
            throw new runtime.RequiredError(
                'createCrossChainTransferDto',
                'Required parameter "createCrossChainTransferDto" was null or undefined when calling deploymentCrossChainControllerCreateTransferV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/deployments/{deploymentId}/cross-chain`;
        urlPath = urlPath.replace('{deploymentId}', encodeURIComponent(String(requestParameters['deploymentId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCrossChainTransferDtoToJSON(requestParameters['createCrossChainTransferDto']),
        };
    }

    /**
     * Create cross-chain transfer (operation + queue operation)
     */
    async deploymentCrossChainControllerCreateTransferV1Raw(requestParameters: DeploymentCrossChainControllerCreateTransferV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CrossChainTransferResponseDto>> {
        const requestOptions = await this.deploymentCrossChainControllerCreateTransferV1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CrossChainTransferResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create cross-chain transfer (operation + queue operation)
     */
    async deploymentCrossChainControllerCreateTransferV1(requestParameters: DeploymentCrossChainControllerCreateTransferV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CrossChainTransferResponseDto> {
        const response = await this.deploymentCrossChainControllerCreateTransferV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deploymentCrossChainControllerGetQuoteV1 without sending the request
     */
    async deploymentCrossChainControllerGetQuoteV1RequestOpts(requestParameters: DeploymentCrossChainControllerGetQuoteV1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['deploymentId'] == null) {
            throw new runtime.RequiredError(
                'deploymentId',
                'Required parameter "deploymentId" was null or undefined when calling deploymentCrossChainControllerGetQuoteV1().'
            );
        }

        if (requestParameters['quoteRequestDto'] == null) {
            throw new runtime.RequiredError(
                'quoteRequestDto',
                'Required parameter "quoteRequestDto" was null or undefined when calling deploymentCrossChainControllerGetQuoteV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/deployments/{deploymentId}/cross-chain/quote`;
        urlPath = urlPath.replace('{deploymentId}', encodeURIComponent(String(requestParameters['deploymentId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QuoteRequestDtoToJSON(requestParameters['quoteRequestDto']),
        };
    }

    /**
     * Request cross-chain transfer quote from LayerZero
     */
    async deploymentCrossChainControllerGetQuoteV1Raw(requestParameters: DeploymentCrossChainControllerGetQuoteV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CrossChainQuotesResponseDto>> {
        const requestOptions = await this.deploymentCrossChainControllerGetQuoteV1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CrossChainQuotesResponseDtoFromJSON(jsonValue));
    }

    /**
     * Request cross-chain transfer quote from LayerZero
     */
    async deploymentCrossChainControllerGetQuoteV1(requestParameters: DeploymentCrossChainControllerGetQuoteV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CrossChainQuotesResponseDto> {
        const response = await this.deploymentCrossChainControllerGetQuoteV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deploymentCrossChainControllerListSourceCurrenciesV1 without sending the request
     */
    async deploymentCrossChainControllerListSourceCurrenciesV1RequestOpts(requestParameters: DeploymentCrossChainControllerListSourceCurrenciesV1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['deploymentId'] == null) {
            throw new runtime.RequiredError(
                'deploymentId',
                'Required parameter "deploymentId" was null or undefined when calling deploymentCrossChainControllerListSourceCurrenciesV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/deployments/{deploymentId}/cross-chain/source-currencies`;
        urlPath = urlPath.replace('{deploymentId}', encodeURIComponent(String(requestParameters['deploymentId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List source currencies available on this deployment for cross-chain transfer
     */
    async deploymentCrossChainControllerListSourceCurrenciesV1Raw(requestParameters: DeploymentCrossChainControllerListSourceCurrenciesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CurrencyResponseDto>>> {
        const requestOptions = await this.deploymentCrossChainControllerListSourceCurrenciesV1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CurrencyResponseDtoFromJSON));
    }

    /**
     * List source currencies available on this deployment for cross-chain transfer
     */
    async deploymentCrossChainControllerListSourceCurrenciesV1(requestParameters: DeploymentCrossChainControllerListSourceCurrenciesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CurrencyResponseDto>> {
        const response = await this.deploymentCrossChainControllerListSourceCurrenciesV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
