/* tslint:disable */
/* eslint-disable */
/**
 * DeFi API (API users)
 * API surface available via API key authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateInvoiceDto,
  InvoiceDetailsDto,
  InvoiceResponseDto,
  InvoicesResponseDto,
  UpdateInvoiceDto,
} from '../models/index';
import {
    CreateInvoiceDtoFromJSON,
    CreateInvoiceDtoToJSON,
    InvoiceDetailsDtoFromJSON,
    InvoiceDetailsDtoToJSON,
    InvoiceResponseDtoFromJSON,
    InvoiceResponseDtoToJSON,
    InvoicesResponseDtoFromJSON,
    InvoicesResponseDtoToJSON,
    UpdateInvoiceDtoFromJSON,
    UpdateInvoiceDtoToJSON,
} from '../models/index';

export interface InvoicesControllerCreateInvoiceV1Request {
    deploymentId: string;
    createInvoiceDto: CreateInvoiceDto;
}

export interface InvoicesControllerFindInvoiceByIdV1Request {
    deploymentId: string;
    invoiceId: string;
}

export interface InvoicesControllerFindInvoicesByDeploymentV1Request {
    deploymentId: string;
    page?: number;
    pageSize?: number;
    sortBy?: InvoicesControllerFindInvoicesByDeploymentV1SortByEnum;
    sortOrder?: InvoicesControllerFindInvoicesByDeploymentV1SortOrderEnum;
    id?: string;
    createdFrom?: string;
    createdTo?: string;
    updatedFrom?: string;
    updatedTo?: string;
    currencyIds?: Array<string>;
    statuses?: Array<InvoicesControllerFindInvoicesByDeploymentV1StatusesEnum>;
    trackingId?: string;
}

export interface InvoicesControllerUpdateInvoiceV1Request {
    deploymentId: string;
    invoiceId: string;
    updateInvoiceDto: UpdateInvoiceDto;
}

/**
 * 
 */
export class InvoicesApi extends runtime.BaseAPI {

    /**
     * Create new entity
     * Create
     */
    async invoicesControllerCreateInvoiceV1Raw(requestParameters: InvoicesControllerCreateInvoiceV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoiceResponseDto>> {
        if (requestParameters['deploymentId'] == null) {
            throw new runtime.RequiredError(
                'deploymentId',
                'Required parameter "deploymentId" was null or undefined when calling invoicesControllerCreateInvoiceV1().'
            );
        }

        if (requestParameters['createInvoiceDto'] == null) {
            throw new runtime.RequiredError(
                'createInvoiceDto',
                'Required parameter "createInvoiceDto" was null or undefined when calling invoicesControllerCreateInvoiceV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/deployments/{deploymentId}/invoices`;
        urlPath = urlPath.replace(`{${"deploymentId"}}`, encodeURIComponent(String(requestParameters['deploymentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateInvoiceDtoToJSON(requestParameters['createInvoiceDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoiceResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create new entity
     * Create
     */
    async invoicesControllerCreateInvoiceV1(requestParameters: InvoicesControllerCreateInvoiceV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoiceResponseDto> {
        const response = await this.invoicesControllerCreateInvoiceV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get entity by ID
     * Get by ID
     */
    async invoicesControllerFindInvoiceByIdV1Raw(requestParameters: InvoicesControllerFindInvoiceByIdV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoiceDetailsDto>> {
        if (requestParameters['deploymentId'] == null) {
            throw new runtime.RequiredError(
                'deploymentId',
                'Required parameter "deploymentId" was null or undefined when calling invoicesControllerFindInvoiceByIdV1().'
            );
        }

        if (requestParameters['invoiceId'] == null) {
            throw new runtime.RequiredError(
                'invoiceId',
                'Required parameter "invoiceId" was null or undefined when calling invoicesControllerFindInvoiceByIdV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/deployments/{deploymentId}/invoices/{invoiceId}`;
        urlPath = urlPath.replace(`{${"deploymentId"}}`, encodeURIComponent(String(requestParameters['deploymentId'])));
        urlPath = urlPath.replace(`{${"invoiceId"}}`, encodeURIComponent(String(requestParameters['invoiceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoiceDetailsDtoFromJSON(jsonValue));
    }

    /**
     * Get entity by ID
     * Get by ID
     */
    async invoicesControllerFindInvoiceByIdV1(requestParameters: InvoicesControllerFindInvoiceByIdV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoiceDetailsDto> {
        const response = await this.invoicesControllerFindInvoiceByIdV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get list of entities
     * Get list
     */
    async invoicesControllerFindInvoicesByDeploymentV1Raw(requestParameters: InvoicesControllerFindInvoicesByDeploymentV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoicesResponseDto>> {
        if (requestParameters['deploymentId'] == null) {
            throw new runtime.RequiredError(
                'deploymentId',
                'Required parameter "deploymentId" was null or undefined when calling invoicesControllerFindInvoicesByDeploymentV1().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['sortOrder'] != null) {
            queryParameters['sortOrder'] = requestParameters['sortOrder'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['createdFrom'] != null) {
            queryParameters['createdFrom'] = requestParameters['createdFrom'];
        }

        if (requestParameters['createdTo'] != null) {
            queryParameters['createdTo'] = requestParameters['createdTo'];
        }

        if (requestParameters['updatedFrom'] != null) {
            queryParameters['updatedFrom'] = requestParameters['updatedFrom'];
        }

        if (requestParameters['updatedTo'] != null) {
            queryParameters['updatedTo'] = requestParameters['updatedTo'];
        }

        if (requestParameters['currencyIds'] != null) {
            queryParameters['currencyIds'] = requestParameters['currencyIds'];
        }

        if (requestParameters['statuses'] != null) {
            queryParameters['statuses'] = requestParameters['statuses'];
        }

        if (requestParameters['trackingId'] != null) {
            queryParameters['trackingId'] = requestParameters['trackingId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/deployments/{deploymentId}/invoices`;
        urlPath = urlPath.replace(`{${"deploymentId"}}`, encodeURIComponent(String(requestParameters['deploymentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoicesResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get list of entities
     * Get list
     */
    async invoicesControllerFindInvoicesByDeploymentV1(requestParameters: InvoicesControllerFindInvoicesByDeploymentV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoicesResponseDto> {
        const response = await this.invoicesControllerFindInvoicesByDeploymentV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update entity
     * Update
     */
    async invoicesControllerUpdateInvoiceV1Raw(requestParameters: InvoicesControllerUpdateInvoiceV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoiceResponseDto>> {
        if (requestParameters['deploymentId'] == null) {
            throw new runtime.RequiredError(
                'deploymentId',
                'Required parameter "deploymentId" was null or undefined when calling invoicesControllerUpdateInvoiceV1().'
            );
        }

        if (requestParameters['invoiceId'] == null) {
            throw new runtime.RequiredError(
                'invoiceId',
                'Required parameter "invoiceId" was null or undefined when calling invoicesControllerUpdateInvoiceV1().'
            );
        }

        if (requestParameters['updateInvoiceDto'] == null) {
            throw new runtime.RequiredError(
                'updateInvoiceDto',
                'Required parameter "updateInvoiceDto" was null or undefined when calling invoicesControllerUpdateInvoiceV1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/api/v1/deployments/{deploymentId}/invoices/{invoiceId}`;
        urlPath = urlPath.replace(`{${"deploymentId"}}`, encodeURIComponent(String(requestParameters['deploymentId'])));
        urlPath = urlPath.replace(`{${"invoiceId"}}`, encodeURIComponent(String(requestParameters['invoiceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateInvoiceDtoToJSON(requestParameters['updateInvoiceDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoiceResponseDtoFromJSON(jsonValue));
    }

    /**
     * Update entity
     * Update
     */
    async invoicesControllerUpdateInvoiceV1(requestParameters: InvoicesControllerUpdateInvoiceV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoiceResponseDto> {
        const response = await this.invoicesControllerUpdateInvoiceV1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const InvoicesControllerFindInvoicesByDeploymentV1SortByEnum = {
    Id: 'id',
    CreatedAt: 'createdAt',
    UpdatedAt: 'updatedAt'
} as const;
export type InvoicesControllerFindInvoicesByDeploymentV1SortByEnum = typeof InvoicesControllerFindInvoicesByDeploymentV1SortByEnum[keyof typeof InvoicesControllerFindInvoicesByDeploymentV1SortByEnum];
/**
 * @export
 */
export const InvoicesControllerFindInvoicesByDeploymentV1SortOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type InvoicesControllerFindInvoicesByDeploymentV1SortOrderEnum = typeof InvoicesControllerFindInvoicesByDeploymentV1SortOrderEnum[keyof typeof InvoicesControllerFindInvoicesByDeploymentV1SortOrderEnum];
/**
 * @export
 */
export const InvoicesControllerFindInvoicesByDeploymentV1StatusesEnum = {
    Created: 'CREATED',
    Paid: 'PAID',
    Unresolved: 'UNRESOLVED'
} as const;
export type InvoicesControllerFindInvoicesByDeploymentV1StatusesEnum = typeof InvoicesControllerFindInvoicesByDeploymentV1StatusesEnum[keyof typeof InvoicesControllerFindInvoicesByDeploymentV1StatusesEnum];
